### ISSUE TITLE
Leave team didn't remove me from sidebar

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1001]
## Issue - Bug

Repro steps on this one might be hard. But adding for documentation.

Here are the steps I took:
1. Was on team Parabol Ops (`teamId`: S1p3i86nx)
1. Went to `Team Settings` and left team
1. Team remained in sidebar
1. Logged out, logged in
1. Team remained in sidebar
1. Click on team, get duckies

I would call this "lower priority"

**Comment by mattkrick** [comment]
probably linked to #897 but i can't get this to reproduce. Since this is a newer one, it could be due to the fixed removeTeamMember mutation. I'll assume that & close for now

**Comment by mattkrick** [comment]
while this is now fixed, the fix was not retroactive. i manually fixed up terry's account, but we may want to do this the right way and write a migration.

the migration would look like this--
get the tms for each user.
for each team, get the TeamMemberId
if the person's `isNotRemoved: false`, then remove them from the tms and from auth0
