### ISSUE TITLE
Card editor: links

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1042]
## Enhancement

The card editor supports links:

- [x] Pasted URLs automatically become links that become _menu-enhanced_.
- [ ] The Markdown pattern `[link](url)` automatically becomes a link. After the initial usage of the pattern (manually, updating existing cards, integrated content, etc.) the user no longer sees MD when updating the link. It becomes _menu-enhanced_.
- Creating links (_menu-enhanced_):
  - [x] Users can type `command + k`. This opens an inline editing C~RUD~ menu with **Text** (input), **Link** (input), and **Add** (button).
  - [x] If text is selected the Text input shows that value, otherwise is empty if text is not selected.
  - [x] Hitting `tab` and `shift + tab` should focus on fields and button.
  - [x] Hitting `enter` should submit the Apply button if both fields have values
  - [x] The Apply button is disabled if either field does not have a value.
  - [x] `esc` closes the menu. No link is created when first applying a link to text, even if both fields have values. No change is made on existing linked text.
- When links are tapped:
  - [x] It opens an inline ~C~RUD menu: **Open** / **Change** / **Remove**
  - [x] User taps Open and the URL opens in a new tab
  - [x] User taps Change and an inline editing menu has the existing values for **Text** and **Link** (and **Update** button)
  - [x] Users tap Remove and the link is removed but the text remains.
- When the cursor enters linked text:
  - [x] The ~C~RUD menu shows.
  - [x] Users can add and remove characters within the link.
  - [x] Backspacing all characters removes the link.

**FUTURE IDEAS**: Consider any links as attachments on card back. Consider smart links via connected services (autocomplete: GitHub issues/PRs, Google Docs, Trello boards/cards, Dropbox files, etc.). Consider smart links as attachments on card back. Consider `+` triggering the menu to add an attachment (connected services, my computer, link). Consider documents from `My Computer` as attachments on card back. `command + k` or `+` (and select Web URL over connected services or My Computer) as the same way to add a link.

**Estimated effort**: 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

#WYSIWYG

**Comment by mattkrick** [comment]
what are you thoughts on pasted-in styles?
for example, if i paste a link & it's underlined & bold, should we keep the underlined & bold? the same applies to all pasted text, link or no. do we wanna keep the pasted colors, images, etc?

**Comment by ackernaut** [comment]
hrm, I guess the clipboard has some style meta? Not sure, I think maybe curate styles?

**Comment by mattkrick** [comment]
ah, sorry shoulda give more details
so draft-js gets 2 fields from the clipboard: text and html (for rich text).
so, if you copy a link from a website & paste it in draft, by default it's gonna look exactly like it did on the website. that's because draftjs has a "PasteProcessor" that takes the html, extracts all the styles, and converts it into its own format.

for example, if i copy the action repo link above, i'll get this
```
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<h1 class="public "
    style="box-sizing: border-box; font-size: 18px; margin: 0px; font-weight: normal; line-height: 26px; position: relative; max-width: 635px; padding-left: 18px; color: rgb(88, 96, 105); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 251, 252); text-decoration-style: initial; text-decoration-color: initial;">
    <strong itemprop="name" style="box-sizing: border-box; font-weight: 600;">
        <a
            href="https://github.com/ParabolInc/action" data-pjax="#js-repo-pjax-container"
            style="box-sizing: border-box; background-color: transparent; color: rgb(3, 102, 214); text-decoration: none;">
            action
        </a>
    </strong>
</h1>
```
as you can see, it gives us a whole bunch of everything, i'm just not sure what to take.
For speed, I'll just use the default, because if they paste in text + links, plus it'd be weird if eg the text was bold but we forced the links to be skinny.

**Comment by mattkrick** [comment]
- How should we handle links within the app? Should we still open them in a new tab, or just navigate there?
- In Google Docs, the modal showing URL | CHANGE | REMOVE is pinning to the front of the word. is it better to do that or to have it pinned to the caret?

**Comment by mattkrick** [comment]
manual tests:
- [x] after typing a valid url, it becomes a hyperlink when you hit space
- [x] after linkifying a typed url, hitting backspace removes the hyperlink
- [x] after any keypress other than backspace, the hyperlink stays & hitting backspace acts normally
- [x] if the cursor is inside or at the end of a hyperlink, the LinkViewer modal shows
- [ ] if you're at the end of a hyperlink and hit space, the LinkViewer goes away
- [x] when the LinkViewer is open and you click another link, the url changes
- [x] when the LinkVIewer is open and you click a non-link, the modal goes away
- [x] when the LinkViewer is open and you click to the right of a trigger (`: @ #`) the suggestion modal pops up
- [x] when the suggestion modal is active and you click inside a hyperlink, the LinkViewer shows up
- [x] when you navigate to a hyperlink via left/right arrows, the LinkViewer pops up
- [x] when you navigate away from a hyperlink via left/right arrows, the LinkViewer goes away

LinkChanger:
- [ ] when the selection is collapsed at the end of the text, hitting ctrl+k and filling out the form creates a new link and the caret is placed after the last letter with no entity state
- [ ] when the selection is collapsed in the middle or to the right of a word, hitting ctrl+k will autofill the text with the word and clicking Add will replace the word the text + link and the caret will be at the end of the word
- [ ] when the selection spans 2+ blocks, the LinkChanger does not have a text field, but the hyperlink is applied to each character in the selection
- [ ] when the selection is not collapsed but only spans 1 block, the entire selected area is set at the default for the text
- [ ] when the selection is within a link, the href and text is autopopulated

**Comment by mattkrick** [comment]
for future reference:
- when you add a link on google docs, it adds that link & the next key you press is not contiguous (ie it isn't blue & you can't click on it)
- in draftjs, all "MUTABLE" type entities are contiguous, meaning that after you insert the link, you can keep typing & you'll change that link text
- this is because internally, draft grabs the caret styles from the caret -1 position (as long as caret -1 is not an IMMUTABLE type, because in that case, it's just vanilla).
- there are 2 workarounds for this:
  - add a space after the link.that way, the cursor isn't blue. the downside is that the space will be added to the undo stack
  - let it be contiguous, thanks to how we linkify things, i already had to create a `space` command that breaks continuity, so if they hit space, they get what they want. this is what they want 99% of the time so we'll roll with it, it's just slightly different from google docs.
