### ISSUE TITLE
Team notes and links

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1059]
## Issue - Enhancement

We can think of this as "minimum viable team knowledge." In addition to a team's project cards, let's make a separate section that's just a big ol' draftjs editor context where team's can add notes and links for thinks like a team's purpose, roles, processes, etc. etc.

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Team Sheet may take on a different meaning, hehe, but basically team notes could be pinned to the meeting lobby and/or a new team review section of the meeting, although I like the idea of being able to pop it open from the top/bottom/side whatever at any time in the meeting. 🤔 

Also, it would be accessible from what we started to call the Team Sheet (that has all the views and goodies about a team).

Hmm…we gonna solve true Gdoc-style multiplayer editing for this one?

This one is still future for now? @jordanh

**Comment by jordanh** [comment]
If we create a note, we could configure the note to be surfaced in the meeting agenda. This will allow for a minimal meeting customization. The document could contain links to metrics, for example.

**Comment by ackernaut** [comment]
Ah, perhaps the note is view-only during the meeting? Or, perhaps anybody can edit during a meeting or outside of a meeting, but it can only have 1 editor at a time: “Terry is editing…” and let cross-talk handle the UX for the simple first pass?

**Comment by jordanh** [comment]
Those seem like reasonable constraints to start with!

**Comment by ackernaut** [comment]
So a couple of ideas that I have:

- Multiple notes could be created from the team sheet space in order to capture team knowledge. We start out with 1 editor at a time (Terry is editing…) forcing users to say “Hands up!” in Slack or during a meeting.
- If multiple notes can be created, we could allow teams to pin 1 of those notes as the official “Meeting Notes” that are accessible during the meeting.
- Any note added to the team has an action “Add Note to Agenda” where the note can be brought up for reference/editing during the agenda round. Instead of a row of cards, the note is central and can be discussed/edited (single editor at a time), then move on to the next agenda item. If any projects/tasks need to come out of it that could be handled by a basic agenda item. So if the discussion, review, or edits don’t take care of team concerns, let’s handle it with the regular agenda item workflow “sounds like an agenda item”.
- Perhaps the pinned note “Meeting Notes” is automatically the first agenda item for every meeting making use of any UI/UX work we do for raising a note as an agenda item. (It is centered instead of a row of cards)

**Comment by ackernaut** [comment]
Another idea that I have concerning the Meeting Notes:

Instead of it being a section it could be something that a user can pop up from the bottom center of the viewport at any time during the meeting, except Check-In (one editor at a time).

**Comment by ackernaut** [comment]
A user could raise a note, then pin it [871#issuecomment-308191177](https://github.com/ParabolInc/action/issues/871#issuecomment-308191177)

**Comment by ackernaut** [comment]
Here’s a quick sketch on how a team note could be seen and processed as an agenda item (but not showing the concept of the main, pinned meeting note):

![image](https://user-images.githubusercontent.com/307286/28694966-056b7062-72f2-11e7-811f-abfb85dc6f92.png)

**Comment by tayamueller** [comment]
#606

**Comment by tayamueller** [comment]
logging repeat observation:

> Another signal for wanting a note/scratchpad: “I made this doc because I felt like we just needed another whole place to offload that wasn’t Parabol or our strategy stuff, to get unstuck.” Other teammates expressed appreciation for having that freeform/longform format - how might we accommodate this signal?

I feel strongly this should be addressed as part of Meeting Enhancement b/c it's the single feature that causes several users to avoid using us (and in 2 known cases, the reason they never returned).

**Comment by jordanh** [comment]
All that's old is new again. This will be super-ceded by Team Library features

**Comment by ackernaut** [comment]
Notes and knowledge!
