### ISSUE TITLE
Markdown parser doesn't work as expected for some more complicated cases [draftjs]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1096]
## Issue - Bug

For these two test cases:
```
I am __*~bold italic strikethrough~*__
```
````
I am `__*~bold italic strikethrough code~*__` 
````

The draft markdown parser doesn't work as expected it pasted or typed directly into a Project card.

- **OS:** OSX
- **Browser:** Chrome

**Comment by mattkrick** [comment]
hurray the 2nd one works as intended!

i could really use your help with how to do this--
the original markdown support worked on both of those, but that was a gotcha for Terry because he expected the second one to look exactly like github:  `__*~bold italic strikethrough code~*__`  (codeblock with the inner triggers ignored). This is useful because backticks act as a way to escape inner markdown symbols.

What I need your help with is telling me what the desired output is for the given input & we can design from there.

Alternatively, we can just say screw markdown all together, since there is already a way to do everything without markdown (except for triple backtick code fences)

**Comment by jordanh** [comment]
So low priority, going to icebox for now
