### ISSUE TITLE
Design Remove GitHub Provider Modal

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1155]
When a user removes a GH provider, we also remove their integrations. We want to know whether we should archive the cards as read only, or whether we should convert the cards to Parabol cards. The former is useful for a guy who was the only 1 on a team working on something & now he is gone or no longer needs to work on it. The latter is good for if they decide to move away from the GitHub & just use us. While that user story may work for Asana or Trello, it probably doesn't work for GitHub. Do we really need to offer that as an option @ackernaut? What's the use case that someone wants to convert github cards to parabol cards?

Anyhow, when someone removes github from their account, we will check for any repos where they are the sole member. Then, we need to pop a modal asking them to confirm that this will remove those integrations. Then, depending on what we decide above, we'll either archive all cards or convert them to parabol cards. We need a modal that allows them to do something like check boxes or toggle switches for 1 or more integrations.

**Comment by ackernaut** [comment]
So I agree that the use case may be stronger around Trello or Asana, where it feels more like an import.

As for GitHub cards becoming Parabol cards…I’m wondering about a few things:

Would folks expect the move away from an integration to be consistent for any provider? Like “I broke away from Trello and kept my cards, why can’t I do that with my GitHub cards?” The only thing I can say is we don’t know what we don’t know as to why somebody may want to keep their cards. If the only GH integrated person left, those cards (especially enhancements and bugs) may still be very relevant to the project/product and a team lead would want to  give the cards to somebody else in the near future (replace that engineer ASAP!) or get somebody else to take over the repo and integrate (the cards could be sent back to GH the same way they were the first time). Also, a list view may help us batch update outcomes in the future (borrowing from the inbox idea).

I think it is safe to treat it the same way if we gave them options.

“Breaking the integration from [provider]? Here are your options:”

- **Archive all**
- **Assign to new owner(s)** (could use a list-style inbox view for this to multi-select etc. until the list is processed. In the meantime, we could use “Assign to team lead” so that they could reassign as they see fit which is safe right now because we don’t have a lot of usage where this would even happen yet.)
- **No change** (just no integration—this might happen with loss of an integration but not a team member—everybody keeps the same cards)

And of course, wordsmithed :)

**Comment by ackernaut** [comment]
PS. The is a pro for simplicity where the same workflow could apply to multiple providers.

If we only allowed for archiving of GitHub, however, then perhaps we give them a clear message. “You can bring these back from the archive if you integrate again”. Perhaps the provider row shows a history of repos that were integrated and shows how many archived cards could be brought back to life? (I’m thinking about a use case where the codebase needs to be picked back up again by somebody else.)

**Comment by mattkrick** [comment]
yeah, i think we could structure it in such a way that the `source` of the project is constant-- it's always github. then we have a `syncToGitHub` boolean as well, which let's folks use 1-way sync if they only want changes to propagate from GH. so if the integration is removed then `syncToGitHub` is just false. archived adds the archive tag, and assign to new owner just changes the owner. The only danger is that we're presenting folks with options that are bad ideas, which means idiots can blame us for letting them do something stupid. Like if you de-integrated github & kept the cards & i updated that card, i'd still expect the card to update to github & when it didn't, i'd be pissed at parabol.

**Comment by ackernaut** [comment]
Yeah, but that could happen with Trello or Asana, etc. Somebody might not realize the sync was broken. I think some of these things are still team communication things. We could notify the entire team under Notifications: “{provider} {integration} was removed. Cards are just cards. [GOT IT]”

**Comment by mattkrick** [comment]
Right, but that happens because folks replace trello with parabol. you don't replace github with parabol.

**Comment by ackernaut** [comment]
Based on latest conversation, I think the content (we can wordsmith!) for the modal is:

- If removing Provider: “Removing your GitHub account will also remove an integration // some integrations.”

- Message (for removing a single integration): “Are you sure you want to remove the `{repo-name}` GitHub integration? Doing so will archive any Parabol cards integrated with the repository.”

- Message (for removing  multiple integrations): “Are you sure you want to remove the following GitHub integrations? Doing so will archive any Parabol cards integrated with each repository: `{list repo names}`”

- Buttons: [ Cancel ] [ Remove ]

Then bonus points if we send a notification to each team member for each integration removed: “Terry removed the integrated GitHub repository: `{repo-name}`. **N** Parabol cards were archived.”

**Comment by ackernaut** [comment]
I can start a visual in Figma for this if you think it’s the right direction.

**Comment by mattkrick** [comment]
yeah this looks right!

**Comment by ackernaut** [comment]
good deal! 💻  ✨  🤓

**Comment by ackernaut** [comment]
We can play with the messaging based on the context (as commented above): removing provider and/or removing single/multiple integrations…

![image](https://user-images.githubusercontent.com/307286/28738170-859ed290-73b7-11e7-8dce-058e9166a4c3.png)

**Comment by mattkrick** [comment]
boom! beautiful!

**Comment by jordanh** [comment]
Nice design. I have a feeling this will come back in the future. Ice boxing for now
