### ISSUE TITLE
listen to GH hooks for CRUDing accounts/repos

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1159]
even before we link projects we can link GH in other, albeit less helpful, ways.
for example, if someone deletes their account, or they de-auth parabol, we should see if we can intercept a webhook from that event & remove their Provider.

Similarly, if someone gets invited to an org, let's see if we can add them to all the repos involving that org that are currently set up on the team.

**Comment by jordanh** [comment]
When Parabol receives a de-auth hook from GH, we send the user a notification that they need to reauthenticate, so that they can continue using GH if desired

**Comment by mattkrick** [comment]
i'm in the parabol org. i added the "testrepo" to the product team that we are all in.
you kick me out of the organization on github.
that kickout sends a webhook to parabol to kick me off the 'testrepo'.
since no other users are on testrepo, it gets removed, too.
that means, all the cards that were under test repo get removed.
all of this happens without a confirmation within parabol, since you did it all on github.
should we notify someone? everyone?
my vote is no because if those people cared about that repo, they would've been a member of it, but i wanted to see what you guys think.

**Comment by ackernaut** [comment]
I think, in general, that the minimal notifications I would send to the team:

– New [GitHub repo] **added** to the team!
– This [GitHub repo] was **removed** from the team! Cards archived!

I think the 2nd is more important (and preferred) than the 1st.

This way it is transparent to the team what is integrated and what is not. Why? Because we are trying to build around good teaming (clarity, ownership, purpose), so I would like to default to this being important for everybody on the team. Team Lead knows they can create issues now. Team Lead knows something happened to an integration. Etc.

That being said, for edge cases, I agree and can see how we throttle the notifications (some just don’t qualify as being worthy of a trigger) to keep down the noise/tests/one-offs, etc.
