### ISSUE TITLE
Recurring Dashboard tasks

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1167]
## Issue - Enhancement

**Users (particularly Executive, Ops, and Admin) frequently express a desire for the ability to mark a Dashboard task or Agenda item as "Recur Weekly/Monthly"**

This is related to but different from #871 as I believe "standing agenda items" could eventually be replaced by an option to add custom modules to the current 3-item Meeting cycle: Check-In, Updates, Agenda.

**Comment by ackernaut** [comment]
See checklist items for #weekly and #monthly in #861

**Comment by tayamueller** [comment]
Users frequently have recurring tasks that they want to track for #autonomy without retyping a lot, and for their teammates, managers, and clients for #transparency.

**Quote from Freemium-converting-to-Pro user: 

> "This is where we drop the ball the most because the recurring stuff just falls through the cracks. I need it to be automated. I don't want to keep typing & asking people 'is this working?' I want to know that daily posts are hitting every single day, and we'd like clients to see that progress without bugging us."**

**Acceptance Criteria**
-When a user creates a card it can be marked "Duplicate: Daily, Weekly, Monthly, Quarterly, Annually, Never" (D, W, M, Q, A, N) via dropdown menu [design tbd]
-Upon selection, ONE new duplicate appears automatically.
-At midnight local time each D/W/M/Q/A (as selected), ONE new duplicate card appears.
-The original card stays on the board until the user moves it to Done and processes it via a Meeting. However, only ONE duplicate is made each cycle (ie: a "daily" card would not populate to infinity. Only 1 new duplicate would be made each day.) It is the user's responsibility to make sure the tasks are completed and marked Done so they don't pile up.
-If the info on the card changes, the next duplicate reflects those changes, NOT the original content.
-This probably needs to be built after "auto due date" #1212 with each duplicate card due date following the selected recurrence cycle.
-Recurrence can be stopped at any time by selecting "Never" on any card.

**Comment by jordanh** [comment]
Estimated effort: 15 points

**Comment by tayamueller** [comment]
Re-requested by the billing leader of a Pro org with 10 active teams.

**Comment by tayamueller** [comment]
> Hi Taya! We are loving Parabol to help us keep on track with smooth running meetings but we are hoping to see a calendar and the ability to create recurring tasks synced with that calendar. It's the big piece that will get us from loving it >>> to can't live without it. Is there any news on when that might happen?

**Comment by jordanh** [comment]
Limiting scope of this from agenda and dashboard items to only include recurring task cards (they should be two separate issues).

**Comment by jordanh** [comment]
Refining acceptance criteria to specify "done" state on this one. Let's go only for hi-fi design and issues.

## Acceptance Criteria
   - A set of high-fidelity designs and implementation issues that:
      - Allow a user to create recurring Task cards
      - Task cards may recur daily, weekly, monthly, quarterly, or annually at a specified time
      - Task cards may appear in a user-specified column
      - Allow a user to find and update recurring Task cards (via a special filter?)
      - Allow a user to delete and cancel recurring Task cards

### Estimated effort: 15 points

### Blocked by:
   * #2001 
   * (likey a TBD issue for card backs)

**Comment by jordanh** [comment]
After reviewing [the hi-fi design mocks ](https://www.figma.com/file/CexaOK4w42TNrfq8l6YInFfE/Agenda-Topics-%2B-Checklist-Phase), I still prefer to starting on the pinned concept to the checklist concept. However, I hear @mattkrick's objection of "we shouldn't do this if it devalues pro." That's why I think we should make pinned agenda items a pro-only feature and iterate the design of pinned agenda items to include a state for a personal user trying to pin an agenda item and learning that they are only available if they upgrade.

Before we go there, however, I think these concepts are safe to test with external users. I'd like to propose the following criteria.

**Who and what to validate**:

* Cycle sponsors: which do you prefer (A/B/Neither)? Would you add sponsor this development?

* Pro users who've surfaced this tension (GLD, iMatter, The Product Factory). Ask which concept gets closer to addressing their original tension (A/B/Neither) and would any of you be willing to pay extra for this feature?

* Uncompensated survey of all actively meeting free users, ask which feature they prefer  (A/B/Neither)
   * If signal is strong, ask users with strong preference if we schedule time to test prototype with team in the future

**Decision tree:**

If sponsored: do it
If Pro-user signal and extra payment potential: backlog creation of high-fi mocks using current strategic filters
If Personal-user signal: backlog creation of high-fi mocks using current strategic filters

If ambivalent or no signal: icebox it

I don't want to define what "signal" means before we collect data. I think we'll have an opportunity to create a proposal for "signal" collecting the data and then making a proposal using a real example.

**Comment by jordanh** [comment]
Iceboxing for now
