### ISSUE TITLE
Discussion: should @mentions on card face assign ownership?

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1173]
## Issue - Enhancement

We witnessed a user attempt to assign ownership by @mentioning the user when typing card. Should the first @mention on a card assign ownership?

Should subsequent @mentions subscirbe and notify others? Or, should only @mentions in the card back do this?

Points to ponder...

**Comment by ackernaut** [comment]
Oh I imagine we will maintain differentiation between assigning an owner, and mentioning folks as subscription/notification triggers. But we shall see! Fun things to ponder!

**Comment by mattkrick** [comment]
yeah, i see owner & subscriber as 2 different things. by default, if you own something, you subscribe to it, very similar to how GH works.
We could add some advanced shortcuts like if you hit Tab instead of Enter, it assigns them as owner, too, but that may be too much magic.

**Comment by ackernaut** [comment]
Maybe we could put a power user move in there. Typing `o:` (oh, colon!) pops up the assign menu but inline with the cursor. With an down/up + enter you could have a new owner which would be reflected by the bottom left avatar and menu trigger once the inline menu closes. Otherwise `@` mentions have implications on getting folks’ attention via subscription/notification system.

**Comment by jordanh** [comment]
Closing until tension may re-raise.
