### ISSUE TITLE
Add New Team from dashboard views

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#118]
# Enhancement

When a user is on the dashboard, she wants to add a new team so that she can organize a new group around a new purpose.

**Estimated effort:** 3 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))
## Specs:

When a user wants to add a team they:
### MVP
- [x] Click on the "ADD NEW TEAM" button
- [x] The right nav navigates to a new team view containing form elements to create the new team
- [x] The "ADD NEW TEAM" button is disabled.
- [x] The user names the team.
- [x] The user enters one or more emails to invite to the new team.
- [ ] The name field shows an error if empty when the form is submitted.
- [ ] The email(s) field shows appropriate error messages if there are bad email addresses.
- [x] The user presses "Create Team" to create the new team.
- [ ] The user is redirected to the team dashboard for the new team.
- [ ] A toast shows a success message.
- [ ] Future enhancements (below) issue created once MVP ships.

In an effort to simplify we are excluding these:
- An element appears in the list that says "New team..."
- The Create Team button is disabled until a name is added.
- If the user wishes to cancel team creation, the user presses "Cancel"
- "New team..." is replaced by the new team in the left nav, and the "ADD NEW TEAM" button is re-enabled (Bonus points for char-by-char update as the team name input is edited.)
### MVP UI concept:

![create-new-team-less-fields 2x](https://cloud.githubusercontent.com/assets/307286/19786466/b3918412-9c63-11e6-9aef-2feaf201ac2c.png)
### Future enhancements (here for context, copy these to an enhancement issue when the MVP is done):
- [ ] If the user belongs to one or more orgs, they select the org here.
- [ ] The user selects the default privacy settings for the team.
- [ ] The user selects users from the org to invite and/or can add email addresses.
- [ ] Bonus points for a single field that can auto-suggest org members and/or capture email addresses. Each invite will be an inline block of either: 1) Org Member (remove), 2) Email Address (remove)
### Future UI concept:

![create-new-team-more-fields 2x](https://cloud.githubusercontent.com/assets/307286/19786465/b38e095e-9c63-11e6-9da5-6d1a3b59cfa4.png)

**Comment by jordanh** [comment]
This issue details "what happens when I press this button?"

![image](https://cloud.githubusercontent.com/assets/103000/19573291/b31bb420-96d3-11e6-8451-aa7d2d7a8fe8.png)

Looking at Slack's interaction, they pop a modal dialog that covers the entirety of the client's view prompting the user to name the channel and set its key settings atomically. I think the atomicity simplifies things greatly.

![image](https://cloud.githubusercontent.com/assets/103000/19573390/17957ad0-96d4-11e6-9610-d0ca92a4a4b6.png)

Thoughts on journey:

1. When a user wants to add a team they:
   1. Click on the "ADD NEW TEAM" button
      1. The right nav navigates to a new team view containing form elements to create the new team
      1. The "ADD NEW TEAM" button is disabled. An element appears in the list that says "New team..."
   1. The user names the team
   1. (future) If the user belongs to one or more orgs, they select the org here
   1. (future) the user selects the default privacy settings for the team
   1. (future) the user selects users from the org to invite and/or,
   1. the user enters one or more emails to invite to the new team
   1. the user presses "create team" to create the new team or,
   1. if the user wishes to cancel team creation, the user presses "Cancel"
   1. "New team..." is replaced by the new team in the left nav, and the "ADD NEW TEAM" button is re-enabled

**Comment by ackernaut** [comment]
👍  will look at this ASAP—I like it!

**Comment by ackernaut** [comment]
Here’s the latest concept, with an effort in starting simple.

### The MVP:

- Has an `input` to add Team Name
- Has a `textarea` to add one or more emails (comma-separated) for team invites

![create-new-team-less-fields 2x](https://cloud.githubusercontent.com/assets/307286/19613979/1fece03c-97b6-11e6-94cd-9a9f592b61ad.png)

### In the future:

- The team can be added to My Personal Account or any Organizations I’m a member of (for billing purposes).
- I can control the privacy of my team.
- I would like to explore having one `textarea` that can auto-suggest team members from my organizations, otherwise capture one email at a time.

![create-new-team-more-fields 2x](https://cloud.githubusercontent.com/assets/307286/19613978/1fecd308-97b6-11e6-9dce-b81ec80d0a4d.png)

**Comment by mattkrick** [comment]
This looks so darn good.
if we keep everything on the left side, we could auto-open those tool tips on the right side. if we did that, we could remove the `What's this` trigger & the `X` which could simplify the look a little.

The only critique I can offer is that the thick border on the left side of the field tip makes me disassociate the it from the field that i'm working on. Maybe we could put it on the right or top? Maybe it's just me?

**Comment by ackernaut** [comment]
Good points @mattkrick ! —would the tool tips open when the field was active? I was also thinking that perhaps there are just help links to our wiki—or put helpful information in a footer after the buttons, or just format the info as content on the right. Also, in the future, thinking responsive, a layout like this might need to change.

**Comment by mattkrick** [comment]
Personally, I love the direction you're headed with the mockup & I _hate_ help sections. It breaks the UX flow, I get distracted from what I was originally doing. Often times it doesn't answer the question I have & 100% of the time I read more than necessary to answer my question. That's why I love the tooltips & "What's this" type stuff, for example from [booking.com](http://www.booking.com/hotel/mx/hostal-teresa.html?aid=304142;label=gen173nr-1FCAEoggJCAlhYSDNiBW5vcmVmcgV1c19nYYgBAZgBMcIBA2FibsgBDNgBAegBAfgBAqgCBA;sid=fc32e6b384b68a8cbb5a48582726bc9d;all_sr_blocks=44823301_90442167_2_0_0;checkin=2016-11-01;checkout=2016-11-02;dest_id=900049913;dest_type=city;dist=0;group_adults=2;highlighted_blocks=44823301_90442167_2_0_0;room1=A%2CA;sb_price_type=total;srfid=0a9ebaec41a59da7dd69a6a155d292553c640df7X1;type=total;ucfs=1&).

For a responsive layout, I'd argue that someone using our web view & not our native app would probably already know what they wanna do, so we don't even need to show them tips. Or we could leave it as is & just make em scroll over to see.

**Comment by ackernaut** [comment]
Yeah, I agree that inline can be helpful. It would be nice to have reusable content for that. I think we can explore the right presentational components for different contexts (forms, mobile, dash, etc.) I like your thinking! We can push it forward.

**Comment by ackernaut** [comment]
@jordanh I am going to make a few updates to the images, but this is shaping up!

**Comment by jordanh** [comment]
Brilliant! I count a couple new components – but it should be pretty straightforward. Wanna have the honor of pushing the branch?

**Comment by ackernaut** [comment]
Sure thing! I’ll get it started.

**Comment by ackernaut** [comment]
I’m ready to collaborate on #458

**Comment by ackernaut** [comment]
Question: how do we sort the teams in the dashboard nav?

For now I think it’s fine to start with the ADD NEW button toward the bottom of the list. I think it’s fine to add the new team to the bottom of the list. The placeholder nav item (while the team is being created) sits right above the disabled ADD NEW button.

There will probably be edge cases where people have a lot of teams. I think we can defer this to the future?

**Comment by ackernaut** [comment]
Latest:

![screenshot 2016-10-27 16 43 51](https://cloud.githubusercontent.com/assets/307286/19786668/be20a0d8-9c64-11e6-98de-925b279fb7a4.png)
![screenshot 2016-10-27 16 44 06](https://cloud.githubusercontent.com/assets/307286/19786669/be21ebb4-9c64-11e6-8659-1c0a4fe506e3.png)

**Comment by mattkrick** [comment]
I agree, I don't think we should design for there being more than... 6 teams?

I'm not sure I like the `New Team...` thing though. I'd rather we add it after they click Create Team. Then, we could animate it in (I'm thinking a highlight that fades away is 300ms... kinda like a stack overflow response.

**Comment by mattkrick** [comment]
or a compromise: The "New Team..." is bound to the content of the text box, so as you type, the team name updates. Only problem there is sorting in the future... we don't want it jumpin all around as the sort if it's alphanumeric.

**Comment by mattkrick** [comment]
If we nuke the "New Team..." then we can also kill the cancel button. Cancel buttons are so 90s :smile: If ya like it, ya hit submit. If ya don't you just navigate away.

**Comment by mattkrick** [comment]
Last one: let's kill the `*Disabled (add Team Name)`. Reading is punishment. Don't punish me for looking at an empty form. Instead, in the future, we can add form validation. If a field isn't valid, then we outline it in red or something & add an error message to it. That way, we only punish folks when they do something wrong.

**Comment by ackernaut** [comment]
@mattkrick 

I think updating the left nav on the fly would look slick, but otherwise I’m okay yanking the New Team placeholder and the cancel button! Maybe we put an (x) in the top right if somebody just has to feel they canceled the task?

Yeah we can ditch the inline tip on the disabled button. Our custom field component has a place for help text that can be set to error color. So we can send it down in props for now until we get more sophisticated form validation.

**Comment by mattkrick** [comment]
@jordanh what say you?
- "New Team..." as is, with cancel button
- "The Beat..." change as you type, with cancel button
- Nothing until submitted, then animate in, no cancel button

**Comment by ackernaut** [comment]
An updated design:
![create-new-team-mvp-updated 2x](https://cloud.githubusercontent.com/assets/307286/19824610/a5bc1ab8-9d36-11e6-9e7f-43b1e0eb77ad.png)

**Comment by jordanh** [comment]
Interesting idea to get rid of the cancel buttons. I can see how they are superfluous considering what other navigation elements we provide. I suppose on mobile, we wouldn't have "cancel" either, we'd probably use the "back" navigation provided by the phone.

I think losing the cancel buttons is safe to try. Let's do it!
