### ISSUE TITLE
Search for issue from within meeting

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1189]
## Issue - Enhancement

From user feedback: while in a meeting and I know another project card exists that I want to add information to, I want to surface that card, so that I can append the information

We could add capability to search for a card and surface it during agenda processing. This issue should likely be added to a "search" epic.

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
This is good. I’ve been pondering a few ways to surface outcomes in the agenda.

1. Have an action on a card menu or card footer, perhaps a comment bubble with dots or plus. We pull the first 3 or 4 words (as the agenda placeholder), perhaps drop a card icon on the agenda item, perhaps link to the card back in the future. When we get to that issue the card is already populated. No confusion on the truncated placeholder because the rest of the text is naturally in the card.

2. There are SO many things we consider doing to agenda items. What if I can type my text and then command K to link to something. What if there was a clear way that autocomplete was within certain contexts? What if I could autocomplete to a card (with a link to full card for reference). This might be similar to referencing a GH issue.

I’m starting to think all things in our system are the same, just different UX:

- agenda: editor + links/mentions/references to cards/tags
- project/task: editor + links/mentions/references to cards/tags
- note: editor + links/mentions/references to cards/tags

All can be added to the agenda. All can reference each other? Not sure but fun OOUX.

“[Mario](https://vimeo.com/10449855), the clouds and the bushes…they…are…the…same.”

**Comment by jordanh** [comment]
Still an important thing. Will likely resurface after we begin indexing objects in something like Algolia

**Comment by jordanh** [comment]
Iceboxing
