### ISSUE TITLE
Designated Facilitator option for consultants

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1203]
## Issue - Enhancement

When Parabol is adopted by a Consultant, vs an Internal Team Leader, the Consultant would like the option to be the Designated Facilitator.

### Acceptance Criteria
A lo-fi design that illustrates:
- Creating a Team Settings option that allows one Team Leader to be the Designated Facilitator

### Estimated Effort (12 points)

**Comment by ackernaut** [comment]
@tayamueller do consultants want to be visible team members on the team? or just be able to interact with the team? I’m thinking about one of your earlier enhancements: #1078

**Comment by tayamueller** [comment]
Good question. I'd say this is a separate issue--sometimes Consultants are active teammates with deliverables, sometimes they will want to be inactive Observers...but they almost always want to be the Designated Facilitator (ie an option to disable "first person to start meeting" feature)

**Comment by ackernaut** [comment]
Makes sense to me!!

**Comment by jordanh** [comment]
@ackernaut can you please add an estimated effort to this issue

**Comment by ackernaut** [comment]
I could design visual concepts that show a new team settings sub-view that shows a few of the v1 settings we have considered. We may have identified a handful like: designated facilitator, meeting reminder email time, use roles instead of souls, etc., make team public. The idea is to show how we use our panel and form controls to show options in context with one another. All for an estimated 12 points.

**Comment by jordanh** [comment]
Scrubbed twice. Needs AC and EE.
