### ISSUE TITLE
handle team member leaving that added slack

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1220]
slack is a 1-token-per-team kinda integration.
however, under the covers it is associated with a slack user that could be kicked off the slack team, or out of the parabol organization.
to solve for this, we need to:
- [ ] expire the token
- [ ] notify someone (team leader?) that the token expired
- [ ] keep the channels & config

**Comment by jordanh** [comment]
Here's a starting proposal:

   1. When we discover the token needs a refresh (e.g. due to a failed request), we send the Team Leader a notification that the connection to Slack needs to be refreshed and direct them via some helpful copy to re-add the integration.

   1. _Optional:_ we add some error state to the Slack integration page stating the same or similar

   1. We keep the configuration, even if the token doesn't work

Suggested notification copy:

For **Team X**, we're having some trouble communicating with Slack. You may need to refresh the credentials used to make the connection. Please go to [Team X's Slack Integration Settings](#link) and click Refresh Token.

Alternatively, we could save a step and the link in the notification could perform the refresh...

**Comment by jordanh** [comment]
Scrubbed once. Needs AC and EE

**Comment by mattkrick** [comment]
iceboxing, we'll revisit when we refactor slack integration handling
