### ISSUE TITLE
Anchor point of Project Card GH repo moves on window resize

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1231]
## Issue - Bug

See below:

![gif](http://g.recordit.co/7gTQ5Ih3Bv.gif)

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Throttle a listener for window resize and re-position?

**Comment by mattkrick** [comment]
that's what material-ui does, but it's really awful because it makes it look janky when it updates every eg 100ms. not a huge issue since a window resize is an edge case, but yeah, it should do better than this.

**Comment by mattkrick** [comment]
note that this only affects menus anchored to the top right. top left anchoring is still cool.

**Comment by mattkrick** [comment]
before: the menu was anchored to the top right, so when you shrink the window, it stays X pixels away from the right border.

after: the menu anchors to the top left on a window resize. so when you shrink the window, it stays X pixels away from the left border. in other words, it is a fixed position modal. this also affects scrolling behavior, which sucks.

in a perfect world: it would stay pinned to the toggle button. this is difficult because we currently set the coords on a setTimeout due to the async nature, that means even if we don't debounce, it's a little laggy. if we do debounce, the lag gets even worse. since a window resize is such an edge case, i think this is OK for now. in the future, we'll fix css so it loads sync so we can get rid of the setTimeout & update without lag. i think not moving is better than moving with lag (for our use case).

**Comment by mattkrick** [comment]
another alternative would be to simply listen for a scroll & close the menu when it happens.

**Comment by jordanh** [comment]
> another alternative would be to simply listen for a scroll & close the menu when it happens.

I like this approach!
