### ISSUE TITLE
URL / URI Reference to Project

### ISSUE THREAD

**Issue by oliver-zhou** [ParabolInc/action#1269]
## Issue - Enhancement

Would also love a URI / URL method of referencing any specific project. i.e., 

Hey, Oliver, have you had a chance to take a look at "https://action.parabol.co/team/HkZ_gKAyb/project/#1000"? I made some comments about a better way to do this item.

Then, clicking the link would open Parabol to the exact specific Project referred to here.

- **Estimated effort:** 13 Points

**Comment by mattkrick** [comment]
i cannot _wait_ to build this! we've got some designs already planned out with the future a single card including a way to subscribe to updates, comments, due dates, "stuck-behind", all that good stuff. If you've got any must-haves don't be shy!

**Comment by dan-f** [comment]
Reviving this, as it seems related to / blocks a lot of upcoming functionality (e.g. https://github.com/ParabolInc/action/issues/1430).

I'd like to remain UX-focused here. Technically, this should be relatively simple, since we can route by Project ID. That said, what do we want to see? A page with _just_ a card? The board with the card, but with the card scrolled-to / focused?

cc @ackernaut.

**Comment by mattkrick** [comment]
For now, I think a link like that will take you to `/me/project/:projectId` and that will auto-scroll to that card & have it highlighted. if we wanted, we could have the card be big & centered like a modal, but we may hold off on that. I'll probably avoid the `/team/:teamId/project/:projectId` functionality because soon we'll have a single kanban.

**Comment by jordanh** [comment]
Scrubbed once. Adding design label and adding to Sprint board.

**Comment by jordanh** [comment]
iceboxing, likely to come back at us when we get around to adding comments and/or card backs
