### ISSUE TITLE
Onboarding: first Dashboard view enhancements

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1278]
## Issue - Enhancement

When a Team Leader OR a new teammate first joins Parabol, the pre-populated Team Dashboard should be a light guide for the FAQ we've observed over the last 6mos:

![onboarding revision](https://user-images.githubusercontent.com/14892189/29480256-f7199f34-8444-11e7-8ad0-19a255c4c9d7.jpeg)

Are there any other ideas for the Future column? [today+21d], [today+28d], etc.?

If possible: [tricky?]
**[today+21d]** - New Team/s started. Try starting a new Team for other work groups, or start a free 1-team personal Organization or personal projects. Parabol is great for planning weddings, reunions, and other group activities. You can see all of your tasks across _all_ of your Teams by clicking on My Dashboard.

[function: even if the Team Leader/company doesn't continue use after 90-day free trial for the work team, perhaps an individual teammate will be converted & continue personal use on their own/become an evangelist.]

**Comment by ackernaut** [comment]
I like where you’re headed with this…

…does a user or team lead only get this for their first team opposed to every team?
…do we allow them to choose between a blank board or self-guided board (with these pre-populated cards) when they first complete the welcome steps?

My thoughts are “maybe yes” and “probably no” respectively.

**Comment by tayamueller** [comment]
Good Qs:

-I'd love for every user to get this view the first 5 times they join or start a team, then go 'way b/c it should be ingrained by then

-Maybe the Team Leader should get ALL the cards, and the other Teammates should only get the private cards?

-Nope. Fixed. I think the research has clearly shown that our users need more guidance to stick. Plus, it's super easy to "clear the board" if they don't need them.

**Comment by mattkrick** [comment]
k this is done, but i'm not a fan.
"Welcome, here's your wall of text" doesn't exactly seem inviting.
Personally, i am the first person to click "stop tutorial" for onboarding things. if you're making me delete a wall of cards 1 by 1, i'm jumping off board.
Anywho, this is living on the wall-of-seeds branch if you guys wanna merge.

![screenshot from 2017-09-21 18-16-30](https://user-images.githubusercontent.com/5514175/30725356-1449321c-9ef9-11e7-8e83-09a20992054f.png)

**Comment by jordanh** [comment]
Seeing this in the context of our product and outside of a spreadsheet it gives me pause. The real question is, would this be safe to try to deploy? I don't think so. I think we should gather some user feedback first – perhaps by deploying this to our development server (after we merge the rest of 6.5).

File the below in "or do you just have a better idea:"

I think the expository text on each card is too long. I think this could be fixed by creating shorter text that links to external documentation – the good news is that we have a good start to what the documentation: the text is right on the current implementation of these cards. I'll add an agenda item to our next product meeting.

**Comment by mattkrick** [comment]
agreed, it didn't look bad until it was in product!
will close for now, but i'll leave the PR up in case we edit the copy.
@jordanh this reminded me to share that Mario onboarding video with you...
https://www.youtube.com/watch?v=U5YTFt7PIdo

**Comment by tayamueller** [comment]
This is hideous. I'll take a spin on copy :)

**Comment by tayamueller** [comment]
revision: 
![onboarding edit](https://user-images.githubusercontent.com/14892189/31035881-b44a41b8-a537-11e7-8949-fce6503b10cb.jpeg)

**Comment by tayamueller** [comment]
https://docs.google.com/spreadsheets/d/1KbLBNsj5a3gNknWUhYGBsx70dc0oy8Tikhqo3mkuUaY/edit#gid=0

**Comment by jordanh** [comment]
After @ackernaut, @tayamueller, @sarakhatri, and I met this morning we came up with the following design direction. It has two parts:

1. Seed dashboard update
2. Agenda empty state design update 

## Seed dashboard update

The content now looks like this:

![image](https://user-images.githubusercontent.com/103000/31451788-e0edee26-ae61-11e7-904d-ffc85a24f6dc.png)

**Note:** two cards will be made drip marketing automations. 

```
[today] - Parabol process reviewed. Check out our Parabol 101 Guide
for info on how (and why!) it works.
```

```
[today] - Free facilitation scheduled. Click here to schedule a free 30min
live video chat to help your team get the most from Parabol.
```

## Agenda empty state design update

We repeated saw that folks weren't interacting with the agenda column and weren't sure of its intent. We came up with the following simple design changes:

![image](https://user-images.githubusercontent.com/103000/31451862-245d3446-ae62-11e7-91b9-95822d5f95bd.png)

It has the following elements:

1. Facebook-style abstract placeholder that demonstrates that this is a list of items just waiting for you to create
2. Clarifies the affordance of the input list item box, so that you see it's a thing you can type items into
3. Adds a hover tool tip that explains what the whole shebang is for

**Comment by ackernaut** [comment]
I’ll take the UI updates to the Agenda input and empty state.

**Comment by ackernaut** [comment]
I’ll take the UI updates to the Agenda input and empty state.

**Comment by ackernaut** [comment]
Here’s latest (it’s nuanced to get everything lined up and tight in the Meeting Dashbar, but I think I found a reasonable iteration). A GIF of the Dash view:

![_agenda](https://user-images.githubusercontent.com/307286/31525032-0e7082ce-af83-11e7-82d5-6b203e99da51.gif)

**Comment by ackernaut** [comment]
I do think the fakey items kind of feels like a loading state, but I’m ok experimenting with it as an empty state.

**Comment by ackernaut** [comment]
Oh, and I placed the tooltip above the input so that it wouldn’t obscure any existing agenda items.

**Comment by mattkrick** [comment]
i agree with @ackernaut, those placeholders immediately make me think loading state. see facebook, slack, linkedin, etc. If i didn't see them populate in 2 seconds, I'd assume it was an error & something didn't load right.

**Comment by ackernaut** [comment]
I agree @mattkrick gonna stick those in a loading state and add an empty state with an emoji:

![_agenda_emoji](https://user-images.githubusercontent.com/307286/31688862-4800b3a0-b353-11e7-8c39-5e9577a6db07.gif)

**Comment by mattkrick** [comment]
@ackernaut did these new seed cards get added in?

**Comment by ackernaut** [comment]
@mattkrick I didn’t touch the seed cards. You had a branch? Perhaps we merge and scrub down to the latest version (fewer cards with less copy)?

**Comment by mattkrick** [comment]
@ackernaut sure, no branch yet, let's get this merged though. where is the final version of the new seed cards?

**Comment by mattkrick** [comment]
pushing to epic 8, this is blocked for 2 reasons:
- we can't create bullet lists yet (3-4 days, estimate)
- we can't turn plaintext into rich text (links, bold, etc.) without user interaction. (3-4 days, estimate)

**Comment by tayamueller** [comment]
user suggestion: an onboarding card that reads "This card is yellow because it's #private. It is only visible to the creator [etc--insert copy]." 

[note: launch with #1363 implementation]

**Comment by jordanh** [comment]
**Estimated effort:** 11 points

**Comment by ackernaut** [comment]
Closing, this is no longer the direction we’re taking.
