### ISSUE TITLE
Animation for realtime notification UI

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1344]
## Enhancement

When a notification is sent to a user and they are using the app, let’s animate the notification icon so that it gets their attention in a subtle but delightful way. ( ht @mattkrick )

**Estimated effort**: 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by sarakhatri** [comment]
For the bell icon, I propose the Tossing or Pulse animation found on this website: http://www.justinaguilar.com/animations/#

The tossing animation is more subtle, while the pulse animation is a little more attention-grabbing. Personally, the pulse icon would get me to click on it as soon as I saw it because it would be annoying to leave it pulsing while using the app.

**Comment by ackernaut** [comment]
When the notification bell is updated in realtime, should it pulse for a brief duration, then finally stop?

**Comment by sarakhatri** [comment]
Yes, I think that would work well! If we use the tossing animation, we could just keep it animating because it's so subtle (if there aren't any issues with that on the backend side).

**Comment by mattkrick** [comment]
I almost wanna do both. Pulse grow, toss, then pulse shrink. Maybe 700ms? I wanna capture all the attention I can, then go away so they aren't distracted too much from their current task.

**Comment by sarakhatri** [comment]
[Parabol Animation Guidelines ](https://docs.google.com/a/parabol.co/document/d/1UnjHCEHsRWsmTLIsGrbBFY8hVyoiRyw0EQXPgSN4xDM/edit?usp=sharing)

**Comment by jordanh** [comment]
iceboxing
