### ISSUE TITLE
"Cancel Pending Approval" copy a little too obtuse

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1354]
## Issue - Enhancement

While running integration tests for `epic 6.5` I failed to notice that my user wasn't the billing leader on a team I was using for testing, so when I invited a new teammate via email, I couldn't for the life of me understand why I wasn't receiving an email from Parabol.

The "Cancel Pending Approval" wasn't explicit enough to cue me that this invitation was held for some reason. I think we should change it to something like "Needs Billing Leader Approval"

**Comment by jordanh** [comment]
This is less important now that Freemium is a thing. But, it'll help what paying customers we may earn.

**Comment by mattkrick** [comment]
You should have gotten a toast after inviting that person:
![screenshot from 2017-09-25 08-47-50](https://user-images.githubusercontent.com/5514175/30817656-482ec5ba-a1ce-11e7-8e1b-0b083a9a155b.png)

If you didn't then that's a bug!

I don't think it's OK to change it to "Needs Billing Leader Approval" because that doesn't tell the user what clicking it will do (cancel the pending approval).  "Cancel Pending Billing Leader Approval" seems too long, though.

**Comment by jordanh** [comment]
I got the toast. I think the specific challenge here is this user context:

When I've invited a user in the past and I need them on my team but I can't remember what "Cancel Pending Approval" means...

Any other suggestions for copy here? @tayamueller, @ackernaut ?

**Comment by ackernaut** [comment]
Perhaps we add a second line (small copy) under the button that clarifies status?

[button: Cancel Invite]
[sub-copy: Status: Pending billing leader approval]
[sub-copy: Status: Approved by billing leader! Waiting to be accepted by invitee]
[sub-copy: Status: Waiting to be accepted by invitee]

Or this might be another use case for the simple tooltip component. To clarify meaning of a button.

**Comment by mattkrick** [comment]
ahhh, sounds like a perfect place for a little (?) bubble with a friendly tooltip

**Comment by mattkrick** [comment]
#1359 will fix this

**Comment by ackernaut** [comment]
Added the new tooltip component to clarify meaning.
