### ISSUE TITLE
true #privacy

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1363]
## Issue - Enhancement

#private cards should actually be private! 

They are currently visible during creation, during the meeting, and included in the Summary.

Proposal: make them **truly** private (visible only to author) AS SOON AS the author types "#private" at any point. Do not include during creation, in meeting Agenda view, or in meeting Summary.

**Comment by mattkrick** [comment]
it's a LOT easier to do it this way. since we're refactoring projects right now, it'd make life easier to do this now.

**Comment by mattkrick** [comment]
There is a little conflict between this and #1418 that we should resolve.
what should the updates phase look like?
Let's say i have a private card on updates phase, do i see it? Probably not, because I should only report on things the team cares about.
#1418 allows me to add cards for myself during my updates phase. what if i add a private card, do i see it? Probably not, but that means the card i just created will disappear, which feels bad.

@jordanh since you were the champion of #1418 i'd like to get your input

**Comment by jordanh** [comment]
When processing an agenda item, if I add a #private card for myself it will "show private card for user, and for no one else," right?

If so, then I believe the updates phase should behave the same way.

**Comment by ackernaut** [comment]
I second this thinking, that #private cards should always be private to the user in any given context.

**Comment by ackernaut** [comment]
One more case: mention notifications

- If I mark a card private, then mention another user, they shouldn’t get a notification.
- If I mention another user, then later mark the card private, any unread mention notification should be removed for the mentioned user.

So basically: if I am mentioned, but another owns the card and the private tag is present, I should not see a mention notification.

**Comment by mattkrick** [comment]
this was fixed in epic 8, please reopen if it's still an issue!
