### ISSUE TITLE
Invitation arriving via email not notification, when already a user

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1424]
## Issue - Bug

I often give demos to folks where:

1. I have them sign up and create a team
2. I have them invite me to their team as jordan@parabol.co

When they do, I always get an email invitation, not a notification even though my email is already known by Parabol. This is a bug, ja?

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
Working as intended, I can reference the issue with the thought process later, but here's the gist:
Let's say I don't send the email since you're a current user.
What if you haven't logged in for 30/60/90 days? Do I send an email then? What happens when someone wants to resend the invitation? Does it send an email then? If it does, then is it really a "resend" because we never sent the first one? If so, does it feel like a bug because you always have to hit resend to send 1 email invite? It'd be so much nicer to say "i invited you, check your inbox" instead of "I invited you, check your inbox if you haven't logged in for the last 30 days, otherwise check your notifications" predictable actions are nice.

**Comment by jordanh** [comment]
This makes sense. Thank you! Closing...
