### ISSUE TITLE
Segment, HubSpot, marking automations & you

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1429]
## Issue - Enhancement

In our design discussion around on-boarding enhancement #1278, we agreed that some of the inial on-boarding cards would become marketing automations which would re-engage and encourage the users to take specific actions: 

```
[today] - Parabol process reviewed. Check out our Parabol 101 Guide
for info on how (and why!) it works.
```

```
[today] - Free facilitation scheduled. Click here to schedule a free 30min
live video chat to help your team get the most from Parabol.
```

I've been looking at how to support these using HubSpot. I had to open a support ticket and speak to a CSA to figure it out, but I've got a plan.

Segment.io does support HubSpot, but only HubSpot's enterprise plan supports taking actions on Segment's `track` events. The HubSpot enterprise plan is $$$.

What the CSA suggested was using `identify` events to drive our marketing automations. You see, when `identify` is called, it will update a HubSpot contact's properties. We can then use HubSpot's _Workflow_ feature to trigger automations (neat!)

To test this, I added the `avatar` contact property to HubSpot (under `Contacts` -> `Contact Settings`). I logged out and logged in to Parabol. Now I see:

![image](https://user-images.githubusercontent.com/103000/31747409-8806e7c0-b421-11e7-8a4f-b6046209c587.png)

Cool! ❄️ 

This here is a discussion. But, I have a suggestion on what to do. I think we should consider the data in our database to be the single source of truth and segment as a means of distributing it. I think we should augment our `identify` calls to segment with a few bits of information:

1. The source from where the user signed up (e.g. `affiliate_parabol.co`, `invitation_email`, ...)
2. Their team adoption level
2. Their personal meeting adoption level

More on implementation below.

## Tracking the sign-up source

We should augment our `User` table record with a field `signup_source` and then send it as an `identify` trait to Segment.

We should set this source when an account is created. We'll use the following table:

| Referring Route  | `signup_source` |
| ------------- | ------------- |
| `/` | `affiliate_parabol.co`  |
| `/invitation`  | `invitation_email`  |

## Team adoption level

Each time we would call identify, we calculate the highest team adoption level the user has achieved:

| Parabol database condition | `team_adoption_level` |
| ------------- | ------------- |
| user has more than one team  | `4_second_team_created`  |
| at least one team has more than user as member | `3_team_members_added`  |
| user has created at least one project | `2_project_added`  |
| belongs to at least one team | `1_team_joined`  |

## Meeting adoption level

Each time we would call identify, we calculate the meeting team adoption level the user has achieved:

| Parabol database condition | `meeting_adoption_level` |
| ------------- | ------------- |
| user has participated in at least 3 meetings  | `3_meetings_held_several`  |
| ... in exactly 2 meetings | `2_meetings_held_two`  |
| ... in 1 meeting | `1_meetings_held_one`  |
| ... in no meetings | `0_meetings_held_none`  |

How could we make this better?

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I could also see us doing an "integration" adoption level too. But, I think these are the two first dimensions to consider tracking...

**Comment by dan-f** [comment]
@jordanh this looks real good to me.

I've got a suggestion regarding "adoption levels". Since the processes of joining a team, adding project cards, and managing teams are unordered, I recommend remodeling the notion of "adoption levels" into "product adoptions". Taking this idea to implementation, we'd move from a sequence of adoption states over time to a sequence of _sets_ of adopted product features over time. Also, as a nitpick, it may be useful to attempt to define a taxonomy of traits in terms of namespacing; e.g. `adoptions.team` and `adoptions.meeting`. For example:

Parabol database condition | `adoptions` | Marketing outreach
-|-|-
user has more than one team, but has not yet invited any team members | `Set { 'team_joined', 'team_created' }` | "Hey, how about creating some project cards?"
user has created at least one project | `Set { 'team_joined', 'project_added' }` | "Psst! Remember you can add your teammates and create your own teams!"
belongs to at least one team | `Set { 'team_joined' }` | "Hey, welcome to Parabol! Here are some things you can do..."

In this case, we'd just have to figure out how to send this data to Hubspot. I'm not familiar with them, so I'll take a look and see if it's possible. Worst-case scenario would be to serialize the sets as CSV.

**Comment by jordanh** [comment]
For now I think we can close this issue. It turns our that our Google Analytics -> HubSpot integration synchronizes page visit information include stuff like `...parabol.co/welcome` and `...parabol.co/meeting` and that give us just enough information in order to meet our re-engagement goals. I'm going to create a number of marketing automations, start there, and can always reopen this if we have a need for finer-grained information we need stored on the HubSpot contact.
