### ISSUE TITLE
Batch notification emails v1

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1442]
## Enhancement

Inspired by #982 

>When I haven't configured my notification preferences, I want all of my offline notifications to be delivered via email, so that I don't miss anything

>When I don't want notification emails from Parabol and I have a Slack team, I want the option to configure my offline notifications to be sent to me on Slack, so that I can avoid getting too many emails

>When my offline notifications are configured to be delivered via email, I want to batch up the last 5 minutes worth, so that I don't get too many emails.

**Details**:
- When 24 hours have passed without a user signing in
- and the user has new notifications
- we send an email saying that they have new notifications with a means of linking to the notifications view (the purpose is re-engagement, so tease them by not giving the notification content)

**Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
So i've seen 2 email frequencies here: 1 is batching every 5 mins, the other is batching every 24 hours.

Since the frequency (FREQ) is uncertain, we'll take the more robust implementation path:
- when a card gets updated, diff the owner & the mentions. to see what has changed.
- for all additions, make a new record in a `NotificationEmailQueue` database table. something like `{id, projectId, type: OWNER, userId, createdAt}`. we're not filtering out for lastSeenAt here because it won't be accurate & it'll cause extra lookups.
- for all deletions from the diff, remove any rows from the email queue table for that projectId
- in a cron job that runs every 24 hours, grab all the records in that table, grouped by  userId
- for each user, grab the `lastSeenAt` field, filter out all notifications where createdAt > lastSeenAt
- if they were last seen > 24h ago, then build an email with all the projects in the queue
- if they have logged in within 24 hours, then delete all the rows where createdAt > lastSeenAt
- create emails, delete all items except the ones that lastSeenAt < createdAt but the difference is < 24h

**Comment by mattkrick** [comment]
@dan-f the mutation will probably live here src/server/graphql/models/IntranetJobs/intranetJobsQuery.js

**Comment by dan-f** [comment]
Thanks @mattkrick!

**Comment by dan-f** [comment]
@mattkrick - should I work off the epic8 branch, or another?

**Comment by mattkrick** [comment]
@dan-f you can work off of the add-notif-types if you want, we may want to refactor the `publishChangeNotifications` so we can use the info it generates to feed the emails
