### ISSUE TITLE
Regression: sidebar teams fail to update after /welcome, /inivitation

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#146]
## Issue - Bug

Testing this morning, it appears we've got two regressions related to keeping a user's team memberships in cashay in sync with the backend.

- [ ] When processing an invitation (e.g. http://action-staging.parabol.co/invitation/mhEv0FC23lGT6Y), the invitation is accepted successfully but the team does not appear in the dashboard sidebar after the redirect to `/me/settings`.

- [ ] When creating a new team via the `/welcome` wizard, the new team does not appear in the sidebar after the wizard is completed.

For `/invitation`, this is odd as the `acceptInvitation` handler looks correct. This will take a little debugging.

For `/welcome`, I think it's because we lost the tucked-away mutation handler for `createTeam` that was in [getAuthedUser.js](https://github.com/ParabolInc/action/blob/b5e07e2f2df98501b08f1427d80473796f27ab90/src/universal/redux/getAuthedUser.js).

- **OS:** OSX
- **Browser:** Chrome
- **Node version:** v6.2.0
- **NPM version:** 3.8.9
- **RethinkDB version:** rethinkdb 2.3.4 (CLANG 7.3.0 (clang-703.0.31))
- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
i noticed this, too. since we're gonna socketize `/team` it doesn't really matter though. The `/team` route is gonna subscribe to a LOT of stuff.

**Comment by jordanh** [comment]
Ah. That's a fair point. I have some silly reasons for fixing this: 1) showing off what we've made to friends 2) gif recording purposes. Imma going to have a look into it, but cap my time at 90 minutes.

**Comment by mattkrick** [comment]
just put a `cashay.query` on that component's container that gets all the `teamMembers { team { id, name}}` by `userId`.

**Comment by jordanh** [comment]
Oh sure, a workaround. That's a good idear.

Should I be pragmatic and add a mutation handler for `createTeam`? There's a weird part of my personality that hates it when the cache gets out of sync...

**Comment by mattkrick** [comment]
nah, i think it'd be the orthodox way of doing things. The reason it broke is because we were using the same query for EVERYTHING and just growing that query. Instead, it'd be cleaner to have each container request just the data that its component needs. It'll all get minimized & normalized anyways, so you don't have to query sparingly.

Eventually, we will be able to `createTeam` from within the teamDashboard, right? In that case, yeah it make perfect sense to write a mutationHandler. Any time 2 components might share the screen, a mutationHandler is the way to go.
