### ISSUE TITLE
task request "Done" notification

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1530]
## Issue - Enhancement

When an team member ASKS a team member to DO a task in the form of assigning a card:

Asker would like to know when the task is Done without checking in constantly
Do-er wold like Asker to know the task is Done without typing a Slack msg to them

Recommendation:
A system to ping the Asker when the Do-er moves the card to their Done column. 

Open question: how does the card know who the Asker is? ("the person who typed it" won't work b/c cards are typed by many people during mtgs; sometimes a Do-er types the card for the Asker). Perhaps if someone/s is @mentioned in a card they get notified?

**Comment by ackernaut** [comment]
Some systems have an affordance for both a “Requester” and an owner (or multiple owners).

I think a short-term solution may be what was suggested, that mentioned folks get notified when marked as Done. Not ideal, because it is manual and has to be learned.

We could optionally add a block of text at the end of the content “Request by {PreferredName}” where the `PreferredName` is the last owner who assigned it to the current owner. The last owner gets notified on the Done event. The text would only show on cards where ownership has changed at least once.

I imagine many cards only change hands once.

**Comment by jordanh** [comment]
I always imagined we'd have a way to allow a user to subscribe to or watch a card.

**Comment by tayamueller** [comment]
see #296
