### ISSUE TITLE
Solo Updates prompt enhancement

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1535]
## Enhancement

**Idea**: Update the copy of the Solo Updates prompt from:

>Quick updates only, please.

to:

>Quick updates, please. Add agenda items for discussion/next steps.

Users can tap “Add agenda items” to focus the input in the left nav, like pressing `+` or tapping on the input.

**Concept**:

![solo updates prompt](https://user-images.githubusercontent.com/307286/33505277-587389ee-d6b0-11e7-97f0-63e121a21483.png)

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tayamueller** [comment]
riffing on this per observed behavior today:

_for teammates:_
## **Terry, what's changed since our last meeting?**
(It's Terry's turn to share. Please add any questions or discussion topics to Agenda Queue.)

_for speaker:_
## **Terry, what's changed since our last meeting?**
(It's your turn to share.)

This would replace need for 2nd "Waiting for Terry to give Solo Updates" box, which is already perhaps visually redundant:
![quick](https://user-images.githubusercontent.com/14892189/33736549-018ca93e-db61-11e7-9fc9-7f888da947a3.jpeg)

**Comment by ackernaut** [comment]
@mattkrick @dan-f is there a clean way to focus on the agenda input by tapping text in the Updates prompt? (If we indeed add this enhancement) Alternatively, I can move forward without that functionality and just update the hint copy.

**Comment by mattkrick** [comment]
like i click a thing & the focus goes to the agenda item input? that's easy enough

**Comment by ackernaut** [comment]
yep “Add an agenda item” as part of the hint in the updates prompt! part of the 8.5 enhancements have been to meeting prompts and hints, so I want to give a little more love to the updates while I’m working on it.

**Comment by dan-f** [comment]
Yeah, shouldn't be too difficult.
