### ISSUE TITLE
Sticky conditional prompt for Solo Updates phase

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1595]
>If it is my updates phase
and i have 1+ cards
It should not encourage me to add more cards. It just tell me to update items quickly

### Latest
Current conditions in Solo Updates prompt are based on:
- boolean for marked as “Not Present”
- boolean for owning any cards

**The results**:
- If no cards, you and others see “What are you working on?”
- If no cards and marked not present, others see “What is Terry working on?” giving opportunities for agenda topics to be added. You see “What are you working on?” (if you are online, but marked Not Present you still get a sensible prompt).
- If cards, you and others see “What’s changed with your tasks?”
- If cards and marked not present, others see “What’s changed with Terry’s tasks”. You see the same question in case you are seeing the view but were marked as not present.
- The tips are also conditional including prompts to add cards or add agenda topics.

**Acceptance criteria**:
- the prompt sticky based on whatever state it is in when first arriving to a user’s update round. That way if a first card is added to a user’s empty board, the prompt doesn’t change and ask “what’s changed?”

effort: 11 points

**Comment by ackernaut** [comment]
I’ll add another here:

“What are you working on?” shouldn’t change to “What’s changed” when you add your first task.

**Comment by ackernaut** [comment]
@mattkrick so here is my latest idea on how to freeze the Solo Updates prompt question per round/user:

A user might go ahead of the facilitator and add some projects etc. but as soon as the facilitator and the group get to the user’s round the copy (based on having or not having projects) should stick to whatever makes sense at that point in time.

When the facilitator gets to a users round, the value of `updateUserHasProjects` could stick to whatever the state is when the facilitator reaches the user’s round. It would almost be like a boolean for `updateUserHadProjects` emphasis on “had.“

I think we could use the sticky boolean for having projects so that we can still use `isCheckedInFalse` which I think should reflect the current state (not sticky). Let’s chat if we need to.

**Comment by ackernaut** [comment]
@mattkrick This was an issue that I wanted to circle back on, basically what is a simple way to make the value of `updateUserHasProjects` a second, sticky constant once the Solo Updates phase reaches the user’s rounds. Ping me as it may be easier to discuss on chat/video.

**Comment by ackernaut** [comment]
@mattkrick I am still curious how to make the Solo Updates prompt sticky based on the state it is in when it loads. If a user manually archives their last card, it would not change to the state that a user would otherwise see if the team arrives to their solo updates round and they have no cards. For now, going to change the milestone to help close out 8.5.

**Comment by jordanh** [comment]
@mattkrick and/or @ackernaut this needs AC

**Comment by ackernaut** [comment]
Sticky updates prompts now has AC and EE

**Comment by mattkrick** [comment]
this is done
