### ISSUE TITLE
Lobby: add copy to illustrate the consequences of pressing "Start Meeting"

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#162]
## Issue - Enhancement

More feedback from @mikearauz:
- When a team member is in the meeting lobby, I want to know who should press the start meeting button (and if they're any special consequences), so I don't do anything I'm not supposed to.

It isn't clear that the first person to press the button will become the meeting facilitator or what that means. Our copy should be updated to reflect that.
- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
👍

**Comment by mattkrick** [comment]
5 issues left until we finish epic 1! I'm all sorts of excited to finish these up.

The logic is kinda difficult. It's not the person who clicks the button. It's the person who clicks the button _unless they aren't a facilitator & a facilitator is present_. 

We got options:
- Do away with `isFacilitator` since anyways can be a facilitator (this makes team settings easier, too)
- Make the copy reactive: "Clicking 'Start Meeting' will make *Terry* the facilitator". That name will be different for everyone. For example, if we're all facilitators, it will say our name. 
- Say something simple like "The facilitator should be the one to click the button"

**Comment by ackernaut** [comment]
I like the idea that anybody can facilitate (and less settings on users). I think the copy should be clear: whoever clicks “Start Meeting” will be the facilitator.

For now, I think the only guidance we build is re-joining the facilitator, otherwise anybody can navigate un-tethered between current and completed phases (check-in, updates, agenda).

I’m starting to re-think who can “End Meeting”. And I haven’t followed the effort closely as to how another person becomes facilitator when the current facilitator drops. So my thinking may be dated!

Just adding my two cents to the conversation. :)

**Comment by mattkrick** [comment]
Ah yeah, leader election!
Right now, if the facilitator disconnects, then a new facilitator is chosen automatically. First, we try to elect someone who has the `isFacilitator` flag set, which comes from team settings. If no one exists, then we pick the left-most avatar (ignoring the folks who aren't connected). This is good because it keeps facilitator duties random. A brand new team member will never be the left-most avatar since new team members are put at the back of the line. So, the next facilitator is guaranteed to have experience with at least one meeting (as long as this isn't the first meeting).

If we nuke the `isFacilitator` from the settings, we could keep left-most avatar logic, or we could go by whoever has been on the team the longest. That means it would first be the person that created the team, then the first person that accepted the invite, etc. @jordanh any strong opinions?

**Comment by jordanh** [comment]
I've been debating whether or not the term "facilitator" is meaningful enough to even really expose. This copy isn't perfect, but perhaps this is closer:

> Whoever presses "start meeting" will lead this meeting, the other participants will follow their screen.

**Comment by mattkrick** [comment]
@jordanh so kill the `isFacilitator` prop on the teamMember doc?
