### ISSUE TITLE
"Soft Assign" Implementation Exploration

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1642]
### Motivation
We want to implement the spec'd out workflow of assigning to and inviting a new user at the same time.

<img width="730" alt="screen shot 2018-01-12 at 2 28 39 pm" src="https://user-images.githubusercontent.com/2146312/34892116-033d132a-f7a6-11e7-927d-c1d46d747330.png">

### Acceptance Criteria
- A specific implementation story addressing the various components of the system which will need to change to support this use case
- No buggy experiences around accepting invitations (see #1356)

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
We've got 2 options here, we can stick the orgApprovals/invitees onto the TeamMember table, or we can create a SoftTeamMember table. I like the latter because fundamentally, they are very different things & the only time we'll ever union the 2 are for task assignment. Otherwise, we'll need to also create a User,
 migrate all users to having our own generated ID instead of an auth0 id, build in support for some things not existing for users/team members, etc.

BACKEND
- Create a SoftTeamMember table with an id, name (autogenerated from email), email, createdAt. isActive, Index on email
- update the project assignee. We'll need 2 data points: is it soft? what's the ID? we could keep the teamMemberId field & just prefix the string with "soft", we could put an `isSoft` attribute on the object, or we could have a "teamMemberId" and "softTeamMemberId" on the object. since we may want to query on these things, I think we should have it be a boolean `isSoftProject`. Then, we should rename `teamMemberId` to `assigneeId` 
- update isSoftProject whenever the project changes owners. 
- add assignee interface type to graphql that lives on the project.
- migrate `teamMemberId` to `assigneeId`
- when a SoftTeamMember gets their orgApproval cancelled or rejected, or the invitation gets cancelled, their `isActive` flag goes false. their projects get archived.
- when an org approval or invitation is created, a soft team member is created. any archived projects with `isSoftProject` and an ID that refers to a soft team member that has the same email address should be unarchived
- when an invitation is accepted, the softTeamMember gets set isActive to false and all projects with that assigneeId are reassigned to the new team member

FRONTEND
- Refactor project#teamMember to project#assignee
- add another line for the + button on the assignment menu
- that line, when clicked, should be an input that takes an email, triggering inviteTeamMembers

**Comment by mattkrick** [comment]
@dan-f Acceptance criteria fulfilled!

**Comment by mattkrick** [comment]
@dan-f does this meet the acceptance criteria? anything else to deliver for this?

**Comment by dan-f** [comment]
LGTM! Nice detail! Once you create a back-end implementation story, we can close this!

**Comment by ackernaut** [comment]
This looks great! There is only detail that may have a funky UX, but not unsafe:

>when an org approval or invitation is created, a soft team member is created. Then, find any archived projects with isSoftProject set to true and an assigneeId that refers to a soft team member that has the same email address. Unarchive those.

The funky story sounds like this: Team A thinks it’s ready for Player X. But team lead realizes that after revisiting the team purpose and roles it’s not ready to expand with that teammate because of role constraints etc. Player B was excited and had already assigned a few things to that player that make sense in the context of Q1 of 2018. Those were archived because the invite was rejected. Later (Q3 of 2018) the team feels the growing pains to really expand but their context (outcomes, current work) has changed. The new teammate Player X gets a bunch of old archived tasks that aren’t relevant anymore and some folks are confused. Player B thinks that she made those and says they are old. Wha wha.

Like I said not the worst thing. I could see the other direction where somebody rejected an invite by mistake or misunderstanding, and they immediately correct it, and if those archived cards come back they are still relevant. Just thinking out loud here, trying to figure out why that 1 bullet sounded odd.

**Comment by mattkrick** [comment]
@ackernaut that's good thinkin!
it sounds like the un-archiving might be a function of time? If cards were archived yesterday, they're probably still relevant today. if they were archived 90 days ago, not so much?

i'll build in a little unarchive-only-if-recent functionality.

**Comment by ackernaut** [comment]
@mattkrick I like that idea, checking if it is recent or not. How long? 1 week, 2 weeks? Whatever you think is fine as a baseline.

**Comment by dan-f** [comment]
Closing, as #1695 was delivered.
