### ISSUE TITLE
Investigate max 9 people in summary

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1648]
User feedback:

>Small thing - but in the meeting summary, it doesn't appear you can see everyone who was or was not at the meeting. The attendance section of the summary only includes the status for 9 people, and we had 11 potential attendees.

>Just looking more closely, the 6 people who actually attended the meeting were in the 9 that were shown, so maybe this limit is by design?

**Comment by dan-f** [comment]
Needs a bit more clarification

**Comment by ackernaut** [comment]
I’ll take the next step to verify what is happening and report back.

**Comment by jordanh** [comment]
Our user clarified that they were misreading the summary. The user thought that the "users with no projects" section at the bottom of the message had a different intent. They believed it was a section to primarily show attendance. That's why they were confused.

It may be because all of the users and their avatars are listed with their attendance status first, followed by: 

![image](https://user-images.githubusercontent.com/103000/35123942-19891752-fc59-11e7-9f8a-ae351cfc5b1b.png)

...which is the real intent of the section.

Perhaps we should give this section a header that says something along the lines of "folks without new tasks"

**Comment by ackernaut** [comment]
When we include Done tasks in the summary, this list may get shorter on average.

Does the label become “Folks without Done or New tasks this week”?

**Comment by mattkrick** [comment]
I think that's right. Maybe we could call it "activity"?

**Comment by jordanh** [comment]
Close when #644 and #1034 as complete

**Comment by ackernaut** [comment]
Fixed with #1731
