### ISSUE TITLE
Super cards (read-only with CTA)

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1670]
### JTBD

>As team leads on-board to Parabol and are considering adopting with their team, they want explicit affordances in the software (as task cards) so that they can take meaningful next steps in getting their team to use the software.

### Acceptance Criteria

Users can:
  - [ ] Be assigned a super card
  - [ ] Reassign the card to another teammate
  - [ ] Only read the content of the card
  - [ ] Change the status (Done, Active, Stuck, Future)
  - [ ] Archive the card (including automatically when in Done column after a meeting ends)
  - [ ] Tap the button on the card, triggering integration steps in the app (like a modal) or out of the app (like an authorization view for Slack or a new event details view for Google Calendar)
  - [ ] Have “Connect team via Slack” super cards (see #1671)
  - [ ] Have “Schedule your first team meeting” calendaring super cards (see #1672)

**Estimated effort**: 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
I suggest estimated effort to be at 12 or 13. To do this, we'll need to support buttons inside of draft-js.

**Comment by ackernaut** [comment]
Interesting, would it be worthwhile to explore a fixed content component that can be seeded on a card instead of an editable component? Upping this to 12 points for now.

**Comment by mattkrick** [comment]
i mean if i had until the end of the day to do it, that's how i'd do it.
however, to do that, i'd have use a sentinel value for project.content (eg `project.content == "__MAGIC_SLACK_CARD__"`) & then make sure every component can handle a sentinel value. i usually prefer to avoid things like that because it spurs a proliferation of conditionals to check for various sentinels, & aside from making code harder to read, i'll inevitably forget to write a sentinel handler somewhere & it'll break. I think buttons will come in handy down the road, BUT i'm all about getting this out the door, so if you want it to be 11 points, i can do that

**Comment by ackernaut** [comment]
I trust your thinking on this one…we can revisit when this gets prioritized (and how much time we can spend on “super cards” in general. Thanks for the feedback!
