### ISSUE TITLE
Design: retro experience

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1737]
## Issue - Enhancement

At S.P.A. VII we designed and received feedback on a [set of pen and ink wires](https://docs.google.com/presentation/d/1iAkjfHTG9UIHsHspaF0haHjCNDyJopbr6luSAdVPpog/edit) for a new retrospective meeting experience.

This story captures the work of raising it's fidelity to a state where it can built to an MVP.

### Acceptance Criteria (optional)
Users can:
   - Easily locate where to start the retrospective meeting from the Team Dashboard
   - Receive an explanation of what a retro is, copy the retro meeting lobby link, and start the meeting
   - Optionally, invite others to join the meeting from the meeting lobby
   - Check-in, input cards, group cards, rank groups/cards, hold a discussion, generate next actions, and complete the meeting
      - Input prompts to use: "What's working?", "Where did you get stuck?", "What might we do differently next time?"

Test criteria:
   - Design validated with at least 1 stakeholder from August Public
   - Design tested with at least 1 user from userbob.com or usertesting.com

- **Estimated effort:** 18 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Ok, the clickable prototype is done and up for review. It shows:

- A meeting button from the team space gives one the option to start a retro meeting.
- The retro meeting lobby (with the help text expanded, explaining the process)
- In the retro lobby, you can copy and share a link with others
- Shows a new concept for the check-in phase
- Shows multiple folks adding reflections (including you, “Terry”)
- Shows a timer that starts at 2:00 in any phase that can benefit from time constraint. Tapping the first time starts it, additional taps add 1 minute per tap. Navigation is not blocked by the timer.
- Shows folks dragging and grouping cards (including you, “Terry” and then also “Taya”). The grouping is multiplayer.
- Shows an optional affordance to add themes to any ungrouped cards, otherwise move along
- Shows you “Terry” adding votes. The Vote nav item expands to show user’s remaining votes and team’s remaining votes (total including yours as to not confuse). Folks can toggle votes on and off and vote up to 3 per card/group.
- Shows an discussion agenda added for the 5 upvoted topics.
- Per upvoted topic, you see any associated reflection cards, and the ability for anybody to add tasks that persist on the dash board and can be processed in action meetings.
- There is a final view where you end the retro. You have an optional space to quickly add any last tasks without needing an additional agenda item.
- Ending the meeting shows a meeting summary with new tasks by teammate and also a list of all the upvoted reflection cards/groups.
- General: the nav shows default, active, and completed states as you move through phases.
- General: the facilitator bar at the bottom has room for a timer control, flat control buttons to advance, and a help icon that can be toggled and gives tips depending on the phase. We can optionally put hint text in the facilitator bar (see “end retro meeting” view) before summary.

**Comment by ackernaut** [comment]
Done in Sprint No. 3
