### ISSUE TITLE
Handling `editing` in UserDash

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#188]
shared `editing` status in the team dashboard works great. BUT, that same task might be viewed from a UserDash. If that occurs, the person won't see that someone else is editing it. In order to enable this, we'd have to subscribe to presence for every teamMember from every team. Is this something we want to support?

**Comment by jordanh** [comment]
This issue was the last thing I read before I went to sleep last night. It was such a bummer!

It seems we have two alternatives here if we want to support this:

- Each project card is it's own room (ick)
- Join `/me` up to each team room (ick, but less ick)

It seems like something we should at least implement and test, if only to understand the bounds of the system... what do you think?

**Comment by mattkrick** [comment]
PUSH IT TO THE LIMIT

`/me` is already in each team room. (that's how the active meeting notification happens).
What we'd have to do is subscribe to every team member for every team.
