### ISSUE TITLE
"Me" Dashboard Part 2

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#190]
## Issue - Enhancement

We made significant progress in #171 (with PR #189), but there are a couple items to address before we close out our alpha epic:

**The “Me” Dashboard**:

- [x] Has buttons to add new outcomes (Actions and Projects).
- [x] Has a filter option to see Projects by a specific team.

**Not in scope for Alpha**:

- Cards have drag-n-drop functionality between columns.
- Can update email address from settings.
- Can add/update avatar from settings.

- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
You're correct, I had intended filter. Updating!

**Comment by ackernaut** [comment]
A checklist for the Action List component:

- [ ] Has empty state. Does **not** show when adding the first item or selecting a team.
- [ ] Has control to add new action. Always shows unless the team select menu is open.
- [ ] Has optional inline menu to select a team. This only shows if the user is on many teams and has to select a team for the action. The user can click the cancel icon or click anywhere else in the DOM to cancel.
- [ ] Items have `isEditing` state which disables checkbox.
- [ ] Items are added to the top of the list.
- [ ] New items are auto-focused upon creation.
- [ ] Items disappear if the user blurs and there is no text area content.
- [ ] The Add New control shows when interacting with the first item to be added so that the user can immediately click it to add another.

**Comment by ackernaut** [comment]
![screenshot 2016-09-27 16 26 41](https://cloud.githubusercontent.com/assets/307286/18895812/2ac927b8-84e2-11e6-938b-d23264a74e71.png)
![screenshot 2016-09-27 16 28 57](https://cloud.githubusercontent.com/assets/307286/18895814/2ac98dfc-84e2-11e6-85ed-d47687cd2156.png)
![screenshot 2016-09-27 16 30 10](https://cloud.githubusercontent.com/assets/307286/18895811/2ac678f6-84e2-11e6-9bc8-f10863420d5c.png)
![screenshot 2016-09-27 16 31 24](https://cloud.githubusercontent.com/assets/307286/18895815/2ac9ef72-84e2-11e6-80bb-959385729cd4.png)
![screenshot 2016-09-27 16 32 19](https://cloud.githubusercontent.com/assets/307286/18895813/2ac955b2-84e2-11e6-8af3-7114aec10f70.png)

**Comment by mattkrick** [comment]
@ackernaut do new actions go to the top or bottom? Looks like it'd make sense to put em on the top.

**Comment by ackernaut** [comment]
@mattkrick at the top :)
