### ISSUE TITLE
Team Archive pagination broken?

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1900]
## Issue - Bug

With our design updates, we may have lost the ability to pagniate our Team Archive:

![img](http://g.recordit.co/H0fdPPxpQu.gif)

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:**  11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Reproduction steps:
1. Navigate to any pro-tier team's archive
2. Scroll to the bottom

### Acceptance Criteria
We:
   - Reproduce and triage failure
   - Fix if less than 1 day of effort, else create a new issue for prioritization

**Comment by ackernaut** [comment]
Investigating…

**Comment by ackernaut** [comment]
I think the problem here is that we are using a scrollable `div` instead of scrolling the entire `window` and the `< WindowScroller />` component that `react-virtualized` provides is listening to the `window` by default. I think if we specify the `scrollElement` to the container div that gets scrolled that may get us what we need. [See the docs](https://github.com/bvaughn/react-virtualized/blob/master/docs/WindowScroller.md) @mattkrick I’m not 100% sure on how to specify the element, just pass in a `ref` to to `div`?

**Comment by mattkrick** [comment]
thanks for the investigation! i'll dig into this as soon as i finish up the auth0 stuff
