### ISSUE TITLE
Editing reflections after the reflect phase

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1913]
Currently, the spec is to make reflections immutable after the reflect phase.
I think this is bad for the following reasons:
- a reflection might be blank
- it might have a typo
- it might be unclear
- it might be 2 reflections that should be broken apart

Possible solutions (not mutually exclusive!):
- enable updating content in the grouping phase
- enable deletions in the grouping phase
- enable creation in the grouping phase (but maybe just for the facilitator? maybe instead of an obvious "add a card" button it's a "split card into 2" button?)

Acceptance Criteria
- [ ] pick a path forward

Effort: 11 points

**Comment by mattkrick** [comment]
@jordanh allow me to poke some holes:
- you allow me to edit a card, but i cannot delete it. what happens if i remove all the text from a card? if the cards behave like the task cards in our app, it should delete itself. if they don't, then we have a UX mismatch.
- i change a card during a voting phase, which changes how others perceive it & that changes the vote. a facilitator could even do this by saying something like "i think this is what he really meant...".

Here's my counter proposal:
- I agree with no creation. 
- I disagree about editing in the vote/discuss phase. Everyone should have read every card during the grouping phase, which means the chance of a typo is pretty slim
- I disagree with disabling deletions during the grouping phase:
- it breaks expected behavior. if i can edit a card, then i can remove all text. when a card is empty & blurred, they expect the card to self-delete (if it's a Task card)
- if the facilitator moved on to grouping before i got 2 words on my card, i may want to remove the partial thought

**Comment by ackernaut** [comment]
Oh, wow. I want to drop my thoughts here too:

- If a reflection card is blank in the creation phase, then it should disappear when moving to grouping.

- I think cards should be immutable after the creation phase. I think that we shouldn’t be too precious about these cards. They really just prompt discussion, clarifying questions, take-away tasks, etc. Otherwise, edits and deletions in other phases really detract from the purpose of those phases.

- BUT as a compromise I could see that **only the author of the card** could edit (I want to clarify in my own words when asked, I want to finish that thought that got cut off by switching phases) or delete during the group stage. After that, cards are immutable. Note that when folks say “who wrote this card? what did you mean?” that person loses anonymity if they choose to speak up, so if they update their words it’s not a big deal.

**Comment by jordanh** [comment]
Ok, after taking in the above, let's:

   * disable editing _and_ deletion after the creation phase
   * disable creation (even for the facilitator) in the grouping phase

We can add fancier bells and whistles (like only owner or owner and facilitator can edit/delete) after gathering user feedback

**Comment by mattkrick** [comment]
i like it! Terry & I were discussing how to add a title to single-card groups in the grouping phase. If the cards can't be edited, then we can use a click to display the title field.

really good discussion here to use when we revisit the flow. closing for now.

**Comment by tayamueller** [comment]
feedback from [this Free-tier user](https://app.hubspot.com/contacts/3888472/contact/5413301):

> You should be able to go back and edit groupings after you've moved on to vote–or at least give the facilitator an option to re-open things.
