### ISSUE TITLE
Implement Clone Card Functionality on Task Cards

### ISSUE THREAD

**Issue by bjanjanin** [ParabolInc/action#2010]
## Issue - Enhancement

This issue is for the implementation of [#1874](https://github.com/ParabolInc/action/issues/1874), which has a design in [Figma](https://www.figma.com/file/ZaF5UkRwPdZtNAeKHlffq4zj/Single-Kanban-and-Retros-UI?node-id=263%3A10589).

### Acceptance Criteria 
Users can:
   - Hover over the card to reveal the "more" (three dots) icon. 
   - Click the "more" icon to open the submenu.
   - Click the "Clone Card" link, which clones that card. 

### Estimated Effort
- 11 points

**Comment by ackernaut** [comment]
I had an idea for a further enhancement when cloning cards. In a lot of design software, when I grab an object I can drag using `alt/option` on a Mac and it makes a copy instead of dragging the original element. It’s a similar behavior in Finder where instead of moving a file, it adds a copy in the new location.

I want to explore realtime drag-and-drop in many places (agenda, discuss, kanban) and being able to grab a copy of card would be slick IMO.

Here’s the basic criteria in my mind:

- User can grab a task card anywhere they are presented (agenda, discuss, kanban)
- User holds the equivalent of `alt/option` for the respective OS
- User gets a copy of the card assigned to them (which they can later reassign to another owner)
- If the user already owned the original card, that is ok, the copy is still assigned to them, too

I envision any task card grid or column being more interactive depending on how the target design evolves with time. Perhaps grabbing and cloning appends to the end of the grid when dropping to not shuffle the other task cards around too much. Maybe it bumps cards down in a column. Just brainstorming.

**Comment by jordanh** [comment]
Scrubbed. Still a thing. But, iceboxing for now.
