### ISSUE TITLE
Checklists added to cards

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2055]
## Issue - Enhancement

Refreshment of #1026, checklists:

> When managing multiple projects, team leads want to add detail to projects breaking them into subtasks so that they can see what is needed to complete a project and how much progress has been made. 📎 🔒 [See user data (internal doc)](https://docs.google.com/a/parabol.co/document/d/1PlpKZXZEu3JeSzaFfJwasBDmUASL3Y7TAHp71tprY9I/edit?usp=sharing)

...but making this one a design issue rather than a design and implementation issue.

### Acceptance Criteria (optional)
Users can:

#### Card front checklists
   - Access a control (without having to know a shortcut) for adding a checklist
   - Create/Update/Rename/Delete checklist items similarly to how a bullet list is edited in a rich-text editor
   - Check or uncheck items to mark completion
   - Can see status of all checklists summarized on card front "✅4/10" 

#### Card back checklists
   - Intentionally omitted from this design story

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tayamueller** [comment]
validation: https://docs.google.com/document/d/1CSfl9u6VXaCG7gw3AviLCeEs9M-rUQ_lqXdYkKlZLaY/edit

**Comment by ackernaut** [comment]
Oh, I think concepts can be designed with less effort, maybe 12-13 points. I’d say more points if the concepts are made clickable and tested with folks. Also, part of the effort is to write the implementation issue once designs have reasonable validation.

**Comment by tayamueller** [comment]
validation from large Pro user:

**[user] "Looking forward to Pinnable Agendas / Team Checklist feature!"**

[Prbl] "We've de-prioritized these features [...]

**[user] "bummer - we've had it come up quite a bit - and i've been telling folks it's coming based on the models we saw a bit ago. [...modify the wording associated with Solo Updates] not so important for us - would much rather have [Pinnable Agendas / Team Checklist]**

[Prbl] "we're just about to enter into our planning process, I'll make sure your request gets some air time with the team and we'll see what we can do!"

**Comment by jordanh** [comment]
Been 6 months since we updated this. Feedback on this issue also related to pinned items, not checkboxes. If this comes up again, let's open a new issue so the history of feedback from users is clean.

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/2470051) writes 🔒 :

>The biggest issue I have with Parabol is that there is such a limited amount of detail I can add to each card. Is there a reason why you don't allow more details such as Favro and Trello tasks?
>
> Right now, your cards only have a title. Nothing else. I think Parabol can basically be a Trello on Steroids.
>
> subtasks
> descriptions
> comments
> attachments
> labels
> templates

**Comment by avivapinchas** [comment]
I've created a little work around for this - I add it into the task card like so: 
<img width="209" alt="Screen Shot 2020-06-29 at 7 04 39 PM" src="https://user-images.githubusercontent.com/11621016/86067846-6fd09980-ba3b-11ea-9b1b-45d23d85c589.png">

I use this when I have what's really 1 large task that I want to track, but I need to remember where I was in the process. This lets me easily see that I've finished it _mostly_. 

This also helps because we don't have tagging. Without adding this pseudo-check-list, I'd have a million small tasks, and the board would get cluttered. By clustering the little tasks that take a couple hours into one card to cover the week-long tasks I'm addressing, I can keep my board a bit cleaner and more easily remember the context around each individual checklist item.
