### ISSUE TITLE
Speed up CircleCI

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2141]
It takes 20 mins to deploy. That's crazy.

Longrunning tasks
- E2E Test Build: 2 mins
  - By speeding up the build step, this will speed up too
- Lint: 2 mins
  - remove formatting from the CI step, the 2x rewrites are expensive
- Test: 1 min
  - don't run things inline, i think jest fixed this by now
- Build: 2 mins
  - remove! we already do a prod build below. this serves no purpose
- Prod build (uglified): 3 mins
  - remove SSR. we don't need it for search engines since the landing page is not part of the app. the only benefit is page load speed, but in order for that to be useful, we need to use true SSR, not just return the login portal.
  - upgrade webpack, babel, and uglify, don't turn the code into pure ES5. that's expensive in terms of paylaod & build speed 
- Deploy: 5 mins
  - 3 mins is spent installing everything in the package.json. instead, we should use lerna to break out app into a server & a client monorepo so they can each have discrete deps. or just rewrite the package.json to include just server stuff. forget about all the big clientside stuff.
- CircleCI: pay $50/mo to run it on (presumably faster?) servers

Acceptance criteria
- [ ] decide how to fix & scope out individual issues

effort: 10.5 points

**Comment by jordanh** [comment]
I want to keep this one open. It's a daily thing. I will add to the product team agenda

**Comment by jordanh** [comment]
To get this one closed, we need to break out an issue or 2 we can prioritize. @mattkrick, I think we already did this, right?

> Prod build (uglified): 3 mins
remove SSR. we don't need it for search engines since the landing page is not part of the app. the only benefit is page load speed, but in order for that to be useful, we need to use true SSR, not just return the login portal.
upgrade webpack, babel, and uglify, don't turn the code into pure ES5. that's expensive in terms of paylaod & build speed

If that's true, I suggest we create issues around these 3 items:

### 1
> Deploy: 5 mins
> 3 mins is spent installing everything in the package.json. instead, we should use lerna to break out app into a server & a client monorepo so they can each have discrete deps. or just rewrite the package.json to include just server stuff. forget about all the big clientside stuff.

### 2

> Lint: 2 mins
remove formatting from the CI step, the 2x rewrites are expensive

### 3

> Build: 2 mins
> remove! we already do a prod build below. this serves no purpose

Doing these will save us 8 or so minutes...

**Comment by mattkrick** [comment]
yeah, SSR is gone.

it's been awhile since i focused on DX, there are a few easy wins out there (using sucrase or swc over babel, terser over uglify, etc). I think your no. 1 is correct though. see #2173.

**Comment by ackernaut** [comment]
Nothing to add here as it reads like a good list of improvements, and thanks for the informative comments, helpful for continuous effort to grok the “stack” (meanwhile looking up mentioned packages)
