### ISSUE TITLE
Reflection card group updates

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2166]
## Enhancement

~This is pending design review for #2106.~

See design: https://codepen.io/ackernaut/full/PaqWmO

### Acceptance Criteria
- Grid layout implemented for grouping Reflection cards
- Modal implemented for grouping Reflection cards 
  - When card dropped on single card, new group is created
  - When card is dropped is dropped on group, card is added to group
  - When card is clicked, modal is raised:
     - The top card in the group appears in the top leftmost position in the modal
     - The width of the modal is calculated from the width of the view port
     - The number of columns and reflow is calculated from the grid breakpoint(s)
- If the top leftmost card is dragged out of the group modal, the next card becomes the top of the group
- When the modal is open and a card is dragged out of the group
   - it may be dropped in between cards to remove it from a group entirely
   - it may be dropped onto a existing group
   - in the above cases, the modal stays open
   - for an observer, if their modal for the _same_ group is closed, they _may_ see the card emerge from the group and move toward the intended destination
   - for an observer, if the their modal for the _same_ group is open and the card is leaving the modal then they would see the card move toward the intended destination and both the initiator and observer would see the top card of the collapsed group beneath the modal change to the next top left-most card within the group
   - for an observer, if the their modal for the _same_ group is open and card is re-ordered within the group then the card drag state is shared
      - for observers who do not have their modal open, they only see the top card of the collapsed group beneath change to next top left-most card within the group as the order changes
- When the modal is open and a user clicks on a card outside of the modal, the modal closes
- When the modal is open and other users are dragging cards, I see this activity happening beneath the modal
- Cards that are currently being dragged do not exist in the modal
- Changing the order within the modal is optional implementation
- A user can drag the top card of a group to another drop zone, the next highest ordered card within the group becomes the new top card of that source group

 
- Topic label is aligned along left text edge instead of centered
- Card count badge added and contains the word "cards"
   - Card count badge is only shown during group
- Cards no longer stack. Groups are illustrated by adding 1 extra card underneath regardless of count.

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Will prioritize this issue now, but it'll need to be groomed before we begin to sprint

**Comment by mattkrick** [comment]
Masonry layout:
-  to make a masonry, you put cell n in the column with the shortest height. a tie goes to the leftmost column
- cells have variable, dynamic height, meaning that they can all start with different heights (due to content) and change height during the grouping phase (adding/removing cards from groups)
- the goal is to achieve a tightly packed grid with the fewest number of moves as possible
- to achieve this, whenever a card is removed from a column, the cards below it should move up
- for any card in the last row, if the start position is greater than the `end position + threshold` of any other column, move it laterally
   
spec
- use the css grid layout to establish a baseline. once created, create a cache for each card including:
```
id
column
row start
height
```
- keep the array of cells in component state. compare length of the array in state to the incoming props to determine if it an add (ungroup) or remove (group)

<hr>

- if it is an add, find the reflectionGroup added, get the reflectionId, then find the oldReflectionGroup. if the oldRefletionGroup had exactly 2 reflections in it, we know the height will decrease (title and stack will go away)
- calculate the height (number of rows) that the oldReflectionGroup decreased by, decrease the height for that card in the cache
- for each card in the same column, decrease the rowStart by the same amount
- put the new reflectionGroup at the bottom of the column
- resort the cards by rowStart, with tie going to the leftmost column

<hr>

- if it is a remove, find the reflectionGroup removed, get the reflectionId, then find the newReflectionGroup it moved to. if the newReflectionGroup had exactly 1 reflection in it, we know the height will increase (title and stack will be added)
-calculate the height (number of rows) that the newReflectionGroup increased by, increase the height for that card in the cache
- for each card in the same column, increase the rowStart by the same amount
- get the height of the oldReflectionGroup, for each card below it in the column, decrease the rowStart by that height
- measure the rowStart and rowEnd (rowStart + height) of each card at the bottom of each column. if any rowStart >  any rowEnd, move that card to the column with the shortest rowEnd
- resort the cards by rowStart, with tie going to the leftmost column

<hr>

there are 5 primary functions here:
- adjustGroupHeight(reflectionGroupId)
- appendGroupToColumn(reflectionGroupId, column)
- removeGroup(reflectionGroupId)
- flattenBottom(groups)
- resort(groups)

**Comment by mattkrick** [comment]
PLACEHOLDERS SPEC

1 thing i left out was placeholders. if i have a grid like this

```
1  2  3
   4  5
```

then the css grid will move 4 & 5 to the left

- placeholders only appear on the last row
- they only appear in the column where a card was removed
- they only appear where the `botom` of the last card in that column is <= the `bottom` of any column to the right

that means after we flatten the bottom, we need to call `addPlaceholders(shortenedColumn)` which will do the following:
- if the column is not the last column
- if the short column is shorter or the same length as any column to the right...
- TBD

**Comment by mattkrick** [comment]
It seems like what we wanna accomplish won't work with react-flip-move because it does basically the exactly same thing as we're doing & when we synchronously paint the dom, react-flip-move sets the before state to off the screen so cards just fly in from all over.

the next approach to try is to manage the grid entirely on our own:
- absolute position everything in the top left
- translate to the correct position according to the gridCache
- when a remove happens, the dom will just delete that node, that's OK since it won't affect the position of the other cards
- instead, we'll just update the position of the other cards with the same logic as we did before. the 2 cards below will simply get translated up

**Comment by jordanh** [comment]
The plot thickens...

**Comment by mattkrick** [comment]
## MODALS

A lot has changed since the original spec. We created the concept of minimal movement, we added animations, etc. Here is the updated spec & outstanding questions: @jordanh @ackernaut 

Here is the exhaustive list of events concerning a modal. When my modal is open...
1. i can begin a drag and fail to drop, which causes the reflection to animate back to its position in the modal
 - observers with the modal open will see something that looks very similar
 - observers with the modal closed will see a reflection appear at the transposed x,y coordinates of where it is in my modal. 
 - FUTURE: observers with the modal closed will see the reflection hovering on top of whatever group it is on top of. if it's in the modal, it'll be hovered over the group.

2. i can begin a drag and drop onto a group outside the modal 
- observers with the modal open will see something similar
- observers with the modal closed will see a card appear at the transposed x,y coordinates & when dropped, it will move to the new destination. 
- **QUESTION**: What happens if i drop the 2nd to last card outside of the modal so there is only 1 reflection left in the group? Does the modal close itself? Should the modal always close when your dragged card exits the bounds of the modal so you can drop on a group that is under the modal?
- **QUESTION**: how do the remaining cards in the modal react? do they reflow like a grid or do they use the minimal movement technique?

3. I _cannot_ open a modal and then drag a reflection into the group. This is because any click on a card outside the modal will trigger the modal to close.


Other considerations:
4. with the modal closed, i can drag a card onto a group.
- observers with the modal open will see that card animate into the modal
- **QUESTION**: how to animate? Option 1: the dropped card animates to the collapsed group's location. Then the new card fades into the modal. Option 2: The dropped card increases its z-index & flies into its new home in the open modal.
- **QUESTION**:  If the top card of a group goes to the top-left position in the modal & then another user drops a reflection on the group, that'll cause a complete reflow (everything gets pushed 1 to the right, cards in the rightmost column shift to the leftmost in the row below). An alternative would be to reverse order the cards so the top card is the last card (bottom right). Thoughts?

5. I'm not convinced that sort order within the group matters. if you have a strong preference to keep it, let me know! i'd like to remove this from scope but build it in such a way that we could add it later if we want.

**Comment by ackernaut** [comment]
1. Re: fail to drop, sounds safe to try!
2. Re: dropping onto a group outside of the modal
  - Perhaps we start with modals always closing when exiting the bounds?
  - I think reflow would be safe in the modal
3. Re: dragging into modal from the outside, do we have to close the modal on any click outside of the modal?
4. Re: dragging onto a group
  - Re: how to animation new cards, Option 2? Folks see the card fly into its new home
  - Re: new top card, when adding cards to the group, can’t each new card to the group just go to the bottom right?
5. No strong preference on sorting

**Comment by mattkrick** [comment]
2. OK, let's start with that. when i drag a reflection outside the modal bounds, the modal closes & i can then drop it on any group. a drop on an invalid target (like the sidebar) or on the originating group will result in a cancelled drop, meaning it'll animate back to its originating group, but then disappear (if it wasn't the top card)

3. There are 3 options i see: close when you click another card. close when you click within the grid. close when you click anywhere. Personally, I like the last option, because if you're gonna click something like your avatar in the upper right, you probably don't need that modal open.

4. Yes, new cards can go the bottom right, but that means the top card must go to the bottom right as well. While we don't let folks re-order within a group, a sort order does exist. The newest card added to the group is always on top. so, if we order from least to greatest, it might go `3,2,1`, with 3 being the top card. if someone drags a new card onto the group, it'd be `3,2,1,4`. 
Another option would be to reverse sort the drop order, so the newest card is added to the bottom. I'm not a fan of that approach for 2 reasons. 1) it'll cause a whole lot of "where did that card just go" since after you drop it it disappears. 2) it breaks our physicality design principle because a card goes _through_ the stack to the bottom.

**Comment by mattkrick** [comment]
> the first row gets pushed down 1

you mean the first column?

the difference between the grid & the modal is the required sort order. in the grid, any card can be on the top left & if you hit refresh, there is no guarantee which card will be up there. to handle overflow, cards are assigned right to left, top to bottom. if we run out of room, we just make it a vertical scroll.

in the modal, we want the top card to be in the upper left. if we relax that constraint, this problem gets easier, but the only way to keep the top card in the top left is to trigger a reflow. if i'm not understanding your suggestion lemme know

**Comment by ackernaut** [comment]
I think we can relax on the order in the modal, and the top card of the stack doesn’t have to be top left in the modal grid however we achieve it. The top card is more of a constraint on the stack presentation than anything, so that things look more consistent for all players. Safe to try! Thanks for reaching out on these details.

**Comment by jordanh** [comment]
Done. for now 🙌
