### ISSUE TITLE
Custom reflection prompts

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2216]
## Issue - Enhancement

Retrospect.team allows folks conducting a retrospective to add custom "sections" – what we would call a columns. 

![image](https://user-images.githubusercontent.com/103000/41555528-dc4f59c2-72ec-11e8-804d-9948a400fe2b.png)

This allows teams more freedom to control how'd they'd like to retrospect. See this email from a potential partner echoing the need:

![image](https://user-images.githubusercontent.com/103000/41556504-d8381ff6-72ef-11e8-825c-7bbf7ba9b21e.png)

This would open the door to adding a checkbox somewhere in the meeting flow "Save as New Retro Template"

### Acceptance Criteria (optional)
Users can:
  - See an affordance during Reflect phase to add a custom retro prompt
  - Click affordance to add a custom prompt
  - Click on prompt to edit it, including the defaults
  - Click on control to remove prompt, including the default
  - See prompt text in lower-lefthand corner of reflection cards in subsequent phases

Evaluate:
  - Removal of headings "Positive" and "Negative" of default prompts
   - (to explore) Layout columns in masonry format (eliminating horizontal scroll)

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

- **Design uncertainty:** 3

**Comment by ackernaut** [comment]
A working proposal:

### Problem
- Folks want to add/edit/delete custom prompts

### Solution Concepts (WIP)
- The view affords multiple columns each supporting an editable prompt, a reflection card input control, an expandable stack of my reflections (which I can edit/delete in the modal), multiplayer feedback on others working on anonymous reflections (see latest outcomes from #2039). The column can be removed or updated, but we need to consider what happens once the phase has started and/or the prompt column already has reflections added to it.

### Phase Criteria
- Something
- Something

### Target Criteria
- Something
- Something

**Comment by mattkrick** [comment]
I like the in-lobby and in-reflect-phase options the best.
the in-relfect-phase option isn't perfect because:
- it's clunky to change templates while in-meeting because folks may have already written things
- i may want to set my columns before the meeting starts

the in-lobby option isn't perfect because:
- I may want to change the prompts later
- anyone can edit, not just the facilitator (pro/con?)
 
a hybrid approach isn't great because:
- if i can set my template in the lobby, why can't i also add/remove columns from the lobby?
- folks can add/remove cards in-relfect-phase to end up with duplicate templates

Since we know templates will be part of the future & they will heavily influence which layout we choose, i think it's important to get a lo-fi of how templates work. see #2337
