### ISSUE TITLE
Pro-tier change queries added

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2244]
## Issue - Enhancement

When a pro-rated billing period elapses (a week), I want to know which organizations have:

- Converted from Personal to Pro
- Added Pro users (who and how many)
- Removed Pro users (who and how many)
- Had Pro users go inactive (who and how many)

### Acceptance Criteria (optional)

A GraphQL query is added that:

   - Can only be accessed by users with `rol == su`
   - Takes a time range (start date and end date) to report for
   - Reports on the following sections
      - OrgTierChanges: a list of orgs (and subfields) who converted from one tier to another including the old tier name and the new tier name
     -  OrgTierChangesSummary: an aggregation by tier summarizing the total number of users who were added, removed, and went inactive
      - OrgUserChanges: by org, report which users were added, removed, and went inactive

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
we currently don't track up/downgrades as events, so we'd need to store a little extra data to do this.
since the timeline is a thing, I'd say we should treat up/downgrades as events & then we can just query the events table since storing this stuff on the Org itself would be cumbersome if they upgrade or downgrade more than once.

**Comment by jordanh** [comment]
Iceboxing as per policy, I'm sure this one will come back around as we close more sales.
