### ISSUE TITLE
Offer support contact action when auth fails

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2276]
## Enhancement

Per current design, folks can run into a scary error message on the auth views. I think we should offer a minimal way to contact us so that they feel less stuck on what action to take, and can sense that we value our customers and are attentive to their needs, especially when blocked.

The UX design principle: blocking error? provide a next-step action to the user

Concept (the white alert with the support email is new):

![auth-error-action](https://user-images.githubusercontent.com/307286/42897472-bcd00668-8a85-11e8-9f8b-0a884081c284.png)

### Acceptance Criteria
- Users have an appropriate UI alert with a clear next step (emailing support) when auth is blocked with an error.
- Until there are Better Ideas™ I think this is a low level of uncertainty can be designed/implemented in code.

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
if i were a user, i wouldn't report this. it's the company's job to be on top of its game. it's not my job to tell them.

- instead, we should be firing off a report to sentry instead of relying on customer feedback. 
- We should sanitize all error messages
- We should make it a light-hearted experience. Point them to our twitter status page. Tell them to go waste 15 mins browsing twitter & we'll be ready by the time they get back
