### ISSUE TITLE
Lo-fi Discussion phase improvements

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2301]
Prior art: #2093

Ideas: : 
-reflections are in an expandable group, either in a modal or a div that expands locally

Acceptance criteria:
- [ ] discuss phase has no scroll container for reflections 
- [ ] at least 8 tasks are shown without being scrollable (in a desktop environment)

Effort: 13 points

**Comment by ackernaut** [comment]
We’re proposing a column-based UI for the Discuss phase.

Currently, we have a stacked layout: topic heading, a grid of reflection cards, a grid of task cards. This is less than ideal for folks on small viewports (eg. small laptops, smartphones) because the two grids share 50% of the vertical space allowed and scroll when overflown.

Addressing the criteria, at some point when there are many reflections in a topic, or many tasks created, there will be overflow, especially depending on the viewport/device. So the question is how to handle overflow in the best way for both the most common cases and the extreme cases. We also want to have a reasonable phase improvement and think about target implementation for not only this phase of a meeting, but as a reusable UI pattern in other contexts and how it eventually affects mobile/tablets.

### Criteria
- The header (topic heading and votes) is above 2 columns
- The first column is for the reflection cards with a label including the count eg. “12 Reflections”. Overflow is a simple vertical scroll. The responsive grid shows 1-3 cards depending on viewport width.
- The second column is for the takeaway tasks including a label “Takeaway Tasks” and an inline control to add task cards. The overflow and grid behaviors are just like the first column.

### Reasons for using a column-based approach:
- Some UI definition: a column can have 1 or many lanes, and/or a responsive grid. In the future this UI concept could support UX like a kanban column “Done” with multiple, customized lanes.
- A longer, more narrow column has a more natural, scrollable overflow than the current, short and wide stacked sections w/ grids of cards
- If 1 column has a high quantity of objects, that does not prevent you from seeing the content of the other column
- Depending on the UX, the order of columns can give the effect of forward progress. We currently support the LTR feel opposed to the RTL feel (b/c LTR culture and language? being able to flip the UI to accommodate RTL users is a nice problem to have in the far future). We are intentional about the order of task status columns in both the dashboard, and the action meeting. Having the reflections in the first column, followed by a second, initially empty column for tasks, supports what action should be taken next (add some takeaway tasks, folks!) to move forward. Also, 2 columns creates a sort of 50/50 tension and the space begs to be filled!

### Considerations for target Implementation (aka the FWEIB)
- For mobile, it is common for folks to navigate columns by pressing a tab-based nav and/or swiping. Perhaps a unique column is a tab (eg. reflections vs tasks), and subset lanes of similar content would be swiped (eg. reflection prompt no. 1 vs. prompt no. 3 of the Reflect phase). We can explore this as a UI enhancement as prioritized.
- Because of this design problem (and similar problems), we are exploring a control-based input for creating tasks instead of our current, simple inline editing. Comparing the advantages is a separate effort outside the scope of this, but both ways of editing have different constraints on how we handle adding/editing cards in columns, lanes, and grids for both larger devices and mobile devices.

### Artifacts
We’ve got a dump of [some concepts in Figma](https://www.figma.com/file/RtoOPCsEK55WkHaCX2Spy6Xz/Discuss-UX?node-id=18%3A0) (see UI Concepts page), and a [branch/PR](https://github.com/ParabolInc/action/pull/2320) showing the low-effort next step toward what a target implementation might look like. The Figma file includes:
- Some sketches and screenshots showing a column-based approach
- Some sketches showing a carousel, or LTR overflow, for viewing reflections, over a grid or task. (We were pondering a way to associate a task card with a single reflection from the grouped topic, if the facilitator had the affordance to highlight 1 reflection card at a time).
- Ideas about collapsing/expanding a group of reflection cards
- Some sketches showing a task card input control that could be a main floating action independent of layout (think mobile columns where the main task is always to add a task card)

**Comment by mattkrick** [comment]
Path forward has been taken, moving to implementation #2336
