### ISSUE TITLE
Task card component and layout specs

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2354]
i think Task cards should have a fixed width, but I could compromise & settle on a max width:
![screenshot from 2018-08-31 08-29-37](https://user-images.githubusercontent.com/5514175/44921692-20629a80-acf8-11e8-8625-a2b347c0ce16.png)

thoughts? @ackernaut 

### Acceptance Criteria

- [x] Map out a few example layouts where cards + grids are used (optional: may include mobile)
- [x] Illustrate options and tradeoffs of different card width & layout options
- [x] Elect a set of card layout principles to apply generally to the product

### Estimated Effort
- 11 points

**Comment by ackernaut** [comment]
I theory I like the `minmax` function that the CSS grid provides because it maximizes space, but the cards do get wide at smaller breakpoints before increasing in columns. Here’s the code:

`gridTemplateColumns: `repeat(auto-fill, minmax(${meetingGridMinWidth}, 1fr))`` and the min-width is currently 220px. So that means cards range from 220 to 439 when breaking from 1 column to 2 columns. But the wider you go the `1fr` gets smaller (2 columns to 3 columns the widest the card is 330px) and so on.

We could try both a fixed min and a fixed max. Maybe something like `240` and `320`. However we will eventually have a gap on 1 or both sides depending on how we center the layout. I think card size is essentially a result of layout choices (grid vs columns, etc.) but the layout should be designed to accommodate the expected presentation of cards.

I’ll play with these locally.

**Comment by ackernaut** [comment]
Also, on a phone (say 400 visual pixels wide) 2 x 200 may feel odd and 1 x 400 would break a max-width of 320 (hypothetically). Do we just center the max-width card in a single column? What about an even wider phone? So do we set a max-width after a breakpoint, or per type of device? That’s why I feel that `minmax` is a decent compromise when we are taking more details into consideration like viewport, grids/columns, etc.

**Comment by mattkrick** [comment]
for grids, i imagine we'd do something like:
`justify-items: center`

and then on the reflection card (or its wrapper):
`max-width: 320`

that way the grid grows, but the card still looks like a card

**Comment by ackernaut** [comment]
Here’s [a messy set of concepts](https://www.figma.com/file/I0JFWKUu2YpGIisDqDH1Uafy/Task-Card-Design-Guidelines?node-id=0%3A1) where we’ve boiled it down:
- 1 fixed card width at 296px
- An individual column overflows vertically
- A group of columns overflows horizontally with either a snap-to pagination pattern or drawers open over the group of columns when there isn’t enough space
- Grids have a 16px gutter both horizontally and vertically
- Grid layout updates when there’s enough room to add another column, otherwise centered unless special layout affordance
- Columns have a 24px gutter between columns and a 12px gutter between cards in a column

**Comment by ackernaut** [comment]
Next steps:

1) Update the retro card grids
2) Update the agenda to open over the task card columns as a drawer, otherwise sidebar when there’s enough room for all
3) Consider collapsing the left navigation of the dashboard, unless we prioritize designing the top bar, or maybe both

None of the steps are urgent IMO.

**Comment by jordanh** [comment]
Do you want to open 3 issues for these @ackernaut? Please reference this issue when you do and then close this one when done.

**Comment by jordanh** [comment]
Also open a Guru card with the conclusions from this post. Thank you sir!

**Comment by ackernaut** [comment]
Card added! https://app.getguru.com/card/cBb5rG9i/Task-card-layout

**Comment by ackernaut** [comment]
Reflection card width updated #2784
