### ISSUE TITLE
Add New Team

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#237]
When clicking "ADD NEW TEAM" we should pop a modal with a Team Name & a list of team members to add. this list should be an auto-complete from all team members from all teams this person is a part of (same subscription as User Dash).

**Comment by jordanh** [comment]
Here's another possible flow:

1. Click on `+ Add new team`, we pop modal for new team name
2. We take them to team settings page and pop toast, "Team created, let's invite some folks"
3. They use regular controls for adding / removing team members

**Comment by ackernaut** [comment]
One initial concept that we have in the big ol’ bucket of artifacts is to use a zero-state of the team settings view (which also has not been implemented to my knowledge). I’m justing posting here to continue the conversation. I feel we now have a better understanding of the product (UI, UX) and these ideas can be improved:

![team-new 2x](https://cloud.githubusercontent.com/assets/307286/18064931/42389264-6df7-11e6-9f4c-55f934437be2.png)
![team-settings 2x](https://cloud.githubusercontent.com/assets/307286/18064932/4238bf5a-6df7-11e6-98f9-ff3ce17e4153.png)

**Comment by mattkrick** [comment]
Are we sticking this behind a paywall?

**Comment by jordanh** [comment]
I'd rather we not.

We haven't talked about design for monetization yet but I _really_ like Slack's model. Instead of _ever_ hitting folks with a paywall, the idea I'm gravitating toward is pre-loading a TL's account with some credit. Performing certain habit-building techniques yield more credit (i.e. adding more teams). We draw down the credit according to the pricing model (e.g. number of active teammates).

When we gear up for beta sprint, let's take some time to talk about monetization as team.

**Comment by jordanh** [comment]
@ackernaut can you drop latest designs and a checklist here? Let's start working on this puppy...

**Comment by ackernaut** [comment]
Yes, updating now!

**Comment by ackernaut** [comment]
@jordanh @mattkrick closing this in favor of using original #118
