### ISSUE TITLE
Creating GH issues using 3rd-party token

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2513]
## Issue - Bug

This is a refresh of #1885. Users are unable to integrate a task card with GH if the owner of the card is not integrated with GitHub.

As more and more of our users are dev teams and folks are requesting working integrations, it's getting more important to get this one fixed.

### Repro steps:

With `User A` and `User B`

1. As `User A`, add GH integration to a team
2. As `User B` (who is not integrated to GH), create a card and tap the Octocat to add to GH
3. The GH styling flashes (optimistically?) but then the card returns to a normal task card type

- **Browser:** Chrome
- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users who haven't been added to the GH integration can:
   - create GH issue cards

**Comment by mattkrick** [comment]
this is working as intended, doesn't mean we can't change it!

What you're asking for is: allow User B to create an issue __by using User A's token__. That means when User A hops on GitHub it's gonna look like they created things that they did not create. It also means that the creator on Parabol != creator on GH, so we'll see a task created by B on Parabol, but created by A on GH.

**Comment by mattkrick** [comment]
so running with an alternative solution...

3 options, ranging from fast to slow. I'd opt for the slowest because i don't like error messages.

- click, optimistically succeed, come back as a fail telling them to integrate by going to the GH int page
- click, optimistically succeed, come back as a fail & a link to integrate (so they don't have to leave the page). this means maybe OAuth window.
- adjust the dropdown item eg `ParabolInc/Action (requires integration)`. This avoids the error message, but requires an extra lookup when the menu opens (nbd really since that menu is rarely opened)

**Comment by jordanh** [comment]
If they click on `ParabolInc/Action (requires integration)` what happens? They get an OAuth window?

**Comment by mattkrick** [comment]
yeah, it'd probably follow this flow:
- get GH OAuth token (pop window) if we don't have a token for them
- link to the repo they requested
- turn the task into a GH issue

same as the 2nd option, just without the error

**Comment by mattkrick** [comment]
thinking back to when we first implemented this, i think the original idea was to let another team member user another user's token in case they don't have an account. for example, taya could create a GH issue under my name even though she doesn't have a GH account. i do see some merit to this, but it's somethign that we'll have to explore, not sure what the expected behavior is for both parties

**Comment by jordanh** [comment]
I could have sworn we had a discussion issue where we came up with some reasonable choices for this. The closest I got was #1174...maybe if I dig deeper I can find it.

One option I remember: if a 3rd-party creates an issue using another user's token material, we format it like this:

```
**An issue created by a 3rd-party user** #42

@tokenuser commented just now:

_Issue created by Parabol user @soandso_
```

Thinking about this further, might be a good way to get some SEO advantage if we dropped a link to the team's board, etc. from these comments.

**Comment by mattkrick** [comment]
Yeah that works. I think we still need a strong incentive to get folks who have github accounts to link their account on parabol to not annoy the guy who has the original token.

This could definitely work for SEO, but only if they're working on OSS. 

*** Issue autogenerated by Parabol. Get your FREE Parabol account today at parabol.co ***

**Comment by jordanh** [comment]
Scrubbed. Iceboxing.
