### ISSUE TITLE
Authentication not completely cleaned-up on logout?

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#260]
## Issue - Bug

Steps to reproduce:

1. Login as test user (e.g. `jordan@parabol.co`)
2. Logout using gear menu on dashboard
3. **Sign-up** as new user
4. Proceed through welcome wizard
5. Observe auth failures on server console

- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
This is a symptom of a much larger issue.
Steps required:
- [X] clear cashay cache on logout
- [X] remove socket transport on logout
- [X] use cashay's new `@cached` for retrieving the user data
- [X] unsubscribe from changefeeds on logout

To unsubscribe, we have a few options:
- unsubscribe from each subscription 1 by 1
- disconnect the socket

The 2nd one sounds best. However, the logout route right now doesn't know about a socket, and I'd like to keep it that way, since being logged in doesn't necessitate a socket (eg welcome wizard, invitation portal).

This is what `redux-socket-cluster` was kinda built for, but we worked around it by setting the `keepAlive` to infinity. I've improved it to handle multiple instances of the HOC, so I turned the keepAlive back on.
