### ISSUE TITLE
Bring back assign by email

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2627]
## Issue - Bug

A funny thing happened on the way to trying to reproduce #2404: I couldn't find a way to assign a task by email any longer!

![gif](http://g.recordit.co/edOMYOtStc.gif)

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Assign tasks by email, triggering an user invitation

**Comment by mattkrick** [comment]
this went away when we simplified the invitation flow. I think about half the logic is still intact to support soft team members, the only part that i know is missing is handling these tasks when a user accepts an invite. We'd also need to come up with some new logic for when to show those invitees since the concept of invitees is gone. for example, after you assign to an email, does that email stay in the list? if so, we'll need to re-implement the concept of invitees & come up with a way to remove them from the list if they never join. if not, then it'll be a pain to assign more than 1 card to an non-existent user.

**Comment by jordanh** [comment]
Closing as "working as designed"
