### ISSUE TITLE
Archived Team Projects Sprint

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#264]
- [x] On team dash, next to the filter, there is a link to goto archived projects
- [x] Clicking "Move to archive" on a card sets the status to archived
- [x] archived projects are all greyed out and the only thing that you can do is unarchive them
- [x] use changefeeds for now. we can switch over to pagination later. 

![team-view-archived-projects 2x](https://cloud.githubusercontent.com/assets/307286/18526337/d142d4e8-7a85-11e6-8738-2a4e0d57554e.png)

https://docs.google.com/spreadsheets/d/1_qrcKcVBvHZLPj7q_zJ82S1yAkpocaWLJHhflHksDVw/edit#gid=0

We'll put off toast popping for now.

Effort: 3 points

**Comment by mattkrick** [comment]
@ackernaut to do--- gimme a ProjectCard that supports `isArchived`

**Comment by ackernaut** [comment]
The `ProjectCard` partially supports this, would just need to be pushed further. I was thinking it might make more sense to write an `ArchiveCard` since we don’t need to handle textarea content or menus. There is a simple button to send it back to Team Projects. We could it compose it with basic `OutcomeCard` presentational components. What say ye?

**Comment by ackernaut** [comment]
Note! I found an icon that I think I like. It is pretty recognizable as a reply icon, but I checked the Noun Project and it comes up a few times for “undo.” What do you think? (See updated graphic above)

**Comment by ackernaut** [comment]
This is yet another UI component that needs a reusable tooltip.
