### ISSUE TITLE
Prevent OAuth and email/pass accounts for the same email

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2696]
if someone creates their account with an email/pass, we should not allow them to login with their OAuth.
Similarly, before creating a new account, we should check if an OAuth exists & if it does, don't create the account.

AC
- [ ] above logic implemented

effort: 12 points

**Comment by ackernaut** [comment]
I think this makes a lot of sense for prod UX. For testing purposes we can always nuke users on dev/staging to test both un/pw and oauth. 👍

**Comment by jordanh** [comment]
Here's a report from [a user](https://app.hubspot.com/contacts/3888472/contact/2732251):

>>> Jordan,

I can login using the Google auth, but the problem is that it's a different account than the one when I login using the form auth. We couldn't see how to link the accounts, and if any of us login using Google, we don't show up as part of the team nor could we add them as members since the Google email address was already a member of the team. I was able to work around the problem by leaving the team with my account from the form login, and then while logged in with the Google auth account, having a team member invite me and accepting it while logged in.

I'm sure it's just the way the accounts are stored, but I would think for most, maybe all teams, you'd want the same account entity to be used whether using email or OAuth or other external auth schemes. The user principal should just be the email address. If not, then we just need to know how we can send invites to users with their email addresses and be able to use Google auth.

**Comment by mattkrick** [comment]
OK, so 2 flows:

- The user already has an oauth account & they try logging in with email/pass
  - Pop an error telling them to log in with oauth
- The user already has an email/pass & they try logging in with oauth
 - Link the 2 accounts so they can log in with either (ideal)
 - Pop an error telling them to login with email/pass (fallback)

since linking the accounts is very auth0 specific & i'm not a fan of auth0, i'm gonna do the fallback & just pop an error
