### ISSUE TITLE
TypeError: Not enough arguments

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2717]
https://sentry.io/organizations/parabol/issues/917227986/?project=107196&referrer=github_plugin

```
TypeError: Not enough arguments
  at postMessage ([native code])
  at None (./src/universal/components/OAuthRedirect.tsx:31:21)
  at asyncFunctionResume ([native code])
  at None ([native code])
  at promiseReactionJob ([native code])
```

Attempt login via OAuth with safari (on desktop or mobile)

**Comment by jordanh** [comment]
Also affected: Chrome on iOS. This is preventing a few users from logging in. Let's schedule this sucker for hotfix mañana.

**Comment by jordanh** [comment]
The `TypeError: Not enough arguments` is being thrown from our code here: https://github.com/ParabolInc/action/blob/8f737e7214c366eb78fd777ba4b84049c4e651a5/src/universal/components/OAuthRedirect.tsx#L31

My guess is this bug is actually pretty simple, in that Safari is being strict in requiring the second argument `targetOrigin`. See: https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
