### ISSUE TITLE
Invite email has improved messaging

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2837]
## Issue - Enhancement

Meeting invite email copy is improved. Iterating on existing presentation.

### Acceptance Criteria (optional)

Users can see:
   - How quick and easy it is to join
   - If a meeting is active, tell the user the meeting is going on

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Stuck on business logic for multiple active meetings:

**Problem**: we want to put active meeting information in an email invite. If the user is being invited to a team, from what context? The team dash? A meeting lobby (if they still exist in the same way because maybe we have a new omni-lobby for all meetings that exist)? An active meeting?

Maybe the invite module needs to be context aware.

**Comment by ackernaut** [comment]
Actually this is duped in 2 places so create an issue.

This is stuck on multiple meeting logic and then #2873 (invite control is context-aware)

**Comment by ackernaut** [comment]
Sending to to-do column:
- Today, we can conditionally say “Join Meeting” if there is an active meeting
- When there are multi-meetings, we have a heuristic #2914 to keep the same conditional message in the email

**Comment by jordanh** [comment]
> @ackernaut sez, "[the heuristic] is: if a meeting has been started in the last hour, 'hey check out this meeting,' otherwise, 'hey check out this team.'"

See #2914

**Comment by ackernaut** [comment]
Ready for review via PR #2943
