### ISSUE TITLE
Invite dialog updates for meeting context

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2838]
## Issue - Enhancement

When a user is joining Parabol in order to join a meeting, let’s show them the context they are about to join.

### Acceptance Criteria

When a user is joining, users can:
  - Float dialog over meeting UI
  - Emphasize one step from joining meeting 
  - Have conditional meeting in progress vs. join a team

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Stuck on business logic for multiple active meetings:

**Problem**: we want to put the invite auth dialog over the active meeting. The user was invited to the team, from what context? The team dash? A meeting lobby (if they still exist in the same way because maybe we have a new omni-lobby for all meetings that exist)? An active meeting?

Maybe the invite module needs to be context aware.

**Comment by jordanh** [comment]
I think the correct thing to do here is to enhance the invite controls to pass along the context of the invite (e.g. invited from a retro meeting, invited from an action meeting, invited from a team dash). @ackernaut do you agree? If so, could you update the AC of this issue?

**Comment by ackernaut** [comment]
AC updated!

**Comment by ackernaut** [comment]
The context-aware invite would be duped in 2 places so created a separate issue:

This is stuck on multiple meeting logic and then #2873 (invite control is context-aware)

**Comment by ackernaut** [comment]
Moving this to the backlog
