### ISSUE TITLE
Lo-fi design prototypes for Group phase including prompt categories

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2842]
See #2557 

### Acceptance Criteria (optional)
A lo-fi prototype we can send to users for feedback that:
   - Shows current group layout, but with headers for each prompt and generated cards under each prompt
   - Shows cards in grid, but automatically color-coded by prompt. Sort cards by prompt
   - Figma prototype link generated for each

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
[WIP in Figma](https://www.figma.com/file/Rz8nce3zxvJYR2xNcO3g38Nh/Retro-Group-Phase?node-id=0%3A1)

**Comment by ackernaut** [comment]
[One](https://www.figma.com/file/Rz8nce3zxvJYR2xNcO3g38Nh?node-id=6%3A323&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#6557604), [two](https://www.figma.com/file/Rz8nce3zxvJYR2xNcO3g38Nh?node-id=6%3A311&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#6557635) more iterations in Figma

**Comment by ackernaut** [comment]
For initial review…
### Colorized clusters by prompt (prototype)
[Figma prototype](https://www.figma.com/proto/Rz8nce3zxvJYR2xNcO3g38Nh/Retro-Group-Phase?node-id=16%3A178&viewport=65%2C527%2C0.5&scaling=scale-down)
- Reflections are clustered and colorized by prompt; order for each cluster is random
- Experimented with a flat (MD specifies 1px border as substitute for elevation level 1) style because the colors and box-shadow get fuzzy
- Experimented with colors that were richer than pastel (found inspiration [here](http://clrs.cc/a11y/) and [here](http://tachyons.io/docs/themes/skins/)), could probably come up with at least about 12-15 colors for prompts; I would code color choices into the template config for our defaults prompts, and then assign random for custom template prompts. Later we could expose controls and let users choose.
- Stretch experiment for mobile: mobile uses snap-to columns that could be swiped left and right. The initial columns would be 1 per prompt. These columns would only hold ungrouped cards by prompt and be read only. We’d have to explore controls to group/ungroup (see sketches). Additional columns would be added per group created, which can include cards of any prompt.
### Grids by prompt (prototype)
[Figma prototype](https://www.figma.com/proto/Rz8nce3zxvJYR2xNcO3g38Nh/Retro-Group-Phase?node-id=16%3A1193&viewport=65%2C527%2C0.5&scaling=scale-down)
- This iteration wasn’t as hot. Initially we show grids grouped by their prompts.
- Groups can be from mixed prompts, but it doesn’t make sense to keep them under a prompt heading.
### Comment
[Figma file](https://www.figma.com/file/Rz8nce3zxvJYR2xNcO3g38Nh/Retro-Group-Phase?node-id=0%3A1)
- If we want to back up from these prototypes, let’s look at sketches and discuss some other solution ideas.

**Comment by mattkrick** [comment]
i think colors are the way forward! 

headings could work (just title, no question) iff we remove the redundant footers to make up for the lost real estate

i'd like to avoid the colored columns on mobile, that will be an engineering nightmare. we should just focus on tinderizing the phase to appeal to mobile

**Comment by ackernaut** [comment]
@mattkrick what do you expect to be tricky about using colors in the mobile views?

**Comment by mattkrick** [comment]
in desktop everything is sorter left to right, top to bottom.
the mobile designs show columns, so top to bottom, left to right.
the masonry grid won't support that. i mean it could, but for the amount of effort to change it probably isn't worth it

**Comment by ackernaut** [comment]
Yeah, it seems that either way how we present on larger viewports (laptops up?) and smaller viewports (tablets down?) will be different and need different components, so validating designs with folks is key.

**Comment by ackernaut** [comment]
Tested this concept with [Sam Spurlin](https://docs.google.com/document/d/1dUjcH_jo1geZYuiobhtfsAZdL4pIIRtDBJBakYbRnzk/edit#heading=h.golwk6sm5g56).
- He preferred the subtle styling of prompts with the colorized dot. Initially these cards are clustered by prompt type ([see Figma](https://www.figma.com/file/Rz8nce3zxvJYR2xNcO3g38Nh/Retro-Group-Phase?node-id=129%3A359))
- He validated some way to view by prompt to take in the cards 1 chunk at a time, but also validated the value of being able to group across prompts for emerging themes ([see prompts filter in Figma](https://www.figma.com/file/Rz8nce3zxvJYR2xNcO3g38Nh?utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#8443505))

Closing as we have some validation on our design direction.
