### ISSUE TITLE
Guard retro phases or allow free navigation

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2948]
## Issue - Enhancement

[This user](https://app.hubspot.com/contacts/3888472/contact/3192751) thought Parabol was broken when he advanced to Group and then navigated back to Reflect.

[This user](https://app.hubspot.com/contacts/3888472/contact/4804901) had a similarly bad experience:

>Mid grouping, I lost the ability to move the cards. I could still scroll up and down but I could no longer group. I may have gone ahead a step and then it locked but I'm not sure
I found the grouping part to be awkward. It left time where I as the facilitator was just doing things and everyone was just staring at me. In the future we would do that part before everyone walked in the room OR if we could all work on it together where the facilitator wasn't the only one that could move cards
We frankly did not vote. Once we hit this stage we went back to our discussion forum which was fine and the voting felt awkward but it's possible I was flustered at this point due to the grouping issue

We need to make a decision here: either we need to confirm with our users before advance or we need to relax constraints and allow people to go back and forth.

If we confirm advancement, this could be a modal, "once you advance to Group, you'll no longer be able to add new Reflections from the Reflect phase..."

If we allow for free navigation, we might need to invalidate the latter meeting state if they make a change back in history, "by adding a new reflection, you'll have to start from the group phase."

Tension is serious enough that this warrants discussion...

### Acceptance Criteria (optional)
- This discussion is resolved when a new design issue is opened with acceptance criteria to resolve this user tension

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
What we might decide to do here is come up with some Pen and Inks and ask for feedback from users.

**Comment by ackernaut** [comment]
I think that a guard dialog may be low enough effort to help in the short term in order to learn.

>Ready to advance to [Next Phase]?
The [Current Phase] phase will be read-only and you won’t be able to [activity].
primary: Advance to [Next Phase] | secondary: Nevermind
[ ] Don’t show me this dialog again

Yes, it’s clunky but it may do the trick. Maybe a flag lives on the user `hidePhaseAdvanceDialog` or something once they’ve gotten tired of this dialog.

I realize this may be throwaway work if we ever take on the task to design the logic for a more fluid phase navigation experience, but this may be a case of doing something that doesn’t scale (not working toward target) so that we increase attachment, and not lose any folks to upsetting experiences (the horror! 😱).

If we want, I’d be glad to make a quick, clickable prototype to test.

Otherwise, I can envision some of the potential solutions I’ve heard mentioned by the team, but they need more thought and testing:
- Maybe we allow additional reflections to be added during group
- Maybe we allow comments on a reflection card during group
- Maybe we allow folks to restart a stage (e.g. you can restart the group phase, but you’ll have to group again)
- Maybe we show all groups in the discuss phase including those with 0 votes so the priority can be vetoed
- Maybe some of these are exposed as team meeting settings
- Maybe we have a smart chat, an ongoing discussion thread that is delineated by phases/stages, so folks can clarify and talk during async meetings as to what cards mean, what they want to talk about, create tasks outside the scope of the Discuss view proper, etc.

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/3861651) said:

> It’d be great to be able to go backwards. If you reset subsequent phases (e.g. voting) it’d be great to preserve the votes [that are unaffected] and people can adjust them if they need to. Robert volunteered for us to be able to get more feedback on specific corner cases.

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/4446051) said:

> While playing, I could not go back to the voting and make adjustments. That might be a good improvement, to be able to go back and if process new insights that come up in the discussion.

**Comment by jordanh** [comment]
Watermark: 4 users gave feedback pointing at this within 21 days

**Comment by jordanh** [comment]
A user reached out via chat and said:
> Hi, We are trying our first retrospective meeting and a colleague has accidental clicked on next. Is there a chance to go back, so that the other colleagues can add their comments also?

**Comment by awenger03** [comment]
It's really frustrating to not be able to go back, and it regularly causes problems for my team. I'm considering alternative products as a result.

**Comment by ackernaut** [comment]
Thanks for the feedback @awenger03, duly noted! What do you think of this idea (of many that we have):

We consider progressive enhancement:
- Reflect: can reflect
- Group: can group and reflect
- Vote: can vote, group, and reflect
- Discuss: we enable the ability to thread on a reflection card or the entire group of cards by adding comments or task cards. I think that the overall UX goal has shifted at this point, so no need to continue the progressive enhancement

**Comment by awenger03** [comment]
Those would all be helpful improvements. The process of grouping does often lead us to new reflections, and during voting we do sometimes want to change our groups.

It would also help us avoid user error if some of the previous comments would be implemented like when a user clicks to go to Discuss show a warning that it would close voting or the ability to go back and reopen voting.

**Comment by jordanh** [comment]
Feedback from [another user](https://app.hubspot.com/contacts/3888472/contact/7651451):

> Hi there,
>
> I am currently on the free plan but we are finding it very annoying when someone mistakenly clicks ahead of the current step such as when adding cards and then they are unable to go back and add the cards. I would think that the option for the team to jump ahead should not be there, but as a facilitator I can go ahead and then make the choice and allow the team to move back if we feel it is needed.
>
> I was wondering if this experience is any different on the paid plan. Before signing up , is there anyway for me to do a trail version of the paid plan?

**Comment by jordanh** [comment]
Closing in favor of #3312

**Comment by ackernaut** [comment]
💡  Here’s one hybrid trade-off we could make re: getting ahead and going back in a Retro.

We allow for progressive enhancement from Reflect to Vote. What I mean is that each phase works until you advance to the Discuss phase where reflections/groups/votes becomes read-only.

The Reflect phase keeps its enabled inputs until Discuss is reached.

Grouping can still happen once Vote is reached. If the penultimate card is removed from a group we can consider returning those votes or leaving them on the last card.

Once the facilitator tries to advance to Discuss we look for confirmation. How do we do this in a way that is not Win 95? Maybe there’s a safe heuristic to try:

- 50% of votes haven’t been used
- 50% of team hasn’t connected to the Vote phase
- something else

If any given conditions are met, when the facilitator taps to move to discuss we replace all controls in the bottom bar with: “Locking in groups and votes in 5… [4… 3… 2… 1…] CANCEL / CONFIRM” where Cancel kills the advance and Confirm skips the countdown and advances.
