### ISSUE TITLE
Mass invitation to action meeting bug

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3024]
### Repro steps:

User A = member of Parabol
User B = completely new user, no previous Parabol User account

User A started action meeting, and entered check-in round
User A Clicked + to add to team (https://action.parabol.co/team/ryq6Vl0CW), copied mass invite link and sent to User B out of band
User B Clicked mass invite link (x)
User B Created new account

Redirect went here, and then hung

![image](https://user-images.githubusercontent.com/103000/61330115-e81f5a00-a7ec-11e9-827f-649d7e3100e7.png)

Then, tried sending personal invite. Also resulted in same state.

(had to delete users both in auth0 and in DB)​

### Acceptance criteria
A user can:
   * Invite a completely new user from an action meeting, have them sign up and join the meeting

#### Estimated effort: 10.5 points

Edit 1: correct typos, clarifications

**Comment by jordanh** [comment]
Promoting this to hotfix: reason is, that if User B hits this state then they are unable to login at all. They will have no personal team, nor will they be able to accept an email invitation

**Comment by mattkrick** [comment]
can't reproduce.

need more info:
- [ ] it says User B click + to add to team. do you mean User A?
- [ ] what stage of the action meeting?
- [ ] what do you mean it hung?
- [ ] do you have an approx time so we can look at it in sentry?

also, probably shouldn't post mass invite links in public repos. bad people could become our team members :wink:

**Comment by jordanh** [comment]
@mattkrick updated the above comment. Apologies for the ambiguity.

I think this happened July 16, 2019 at 11:20 AM ET (3:20 PM UTC)

**Comment by jordanh** [comment]
And, fair point about pasting a mass invite link! Ha! 😊

**Comment by jordanh** [comment]
User id that was affected (now deleted from auth0 and DB): `google-oauth2|100603953514293603285`

**Comment by mattkrick** [comment]
That user hit a number of errors:
https://sentry.io/organizations/parabol/issues/?project=107196&query=user%3A%22ip%3A184.153.65.202%22

The first error is one caused by auth0 when there is a state mismatch. 
https://sentry.io/organizations/parabol/issues/897870100/?project=107196&query=user%3A%22ip%3A184.153.65.202%22&statsPeriod=14d

state is used to prevent CSRF attacks, but a number of auth0 users report the same problem: https://community.auth0.com/t/invalid-token-state-does-not-match/22054

To fix it, I passed in my own state.
I also replaced auth0's WebAuth with my own client. fool me once...
we'll still wanna smoke test this on prod to make sure everything is hunky dory with the combo of auth0 + safari mobile (blocked 3rd party cookies) + new code.
