### ISSUE TITLE
User data migration mutation implemented

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3140]
​
Legacy: when I signed up for Parabol using email _and Google authentication by mistake, I want my data to appear only under a single account, so that I can have everything in one place

When my organization signs up for an enterprise account, I want my old user's data migrated to my new enterprise user, so that I can keep working as before

Start thoughts:
   - Mutation should take arguments of `srcOrgId`, `srcUserId`, `destOrg` and `destUserId`
   - If user is a Team Leader, then team (and its users) should move to `destOrg` too
   - If `srcOrgId` and `destOrgId` are the same, all of `srcUserId`'s data (Tasks, Teams, etc) are reassigned to `destUserId`
   - Should return:
      - error, message
      - destination org changes:
         - list of new users on org
         - list of new teams on org

03-Sep-2019 EDIT: Added case if `srcOrgId` and `destOrgId` are the same

**Comment by jordanh** [comment]
@mattkrick starting this as a `discussion` until the AC becomes a little clearer. How'd you make my thoughts better?

**Comment by jordanh** [comment]
Let's say I want to move a _whole_ bunch of users from one org to another, I'd probably write a quick script that would just write a bunch of mutations to paste into the graphiql...

**Comment by jordanh** [comment]
Edited

**Comment by mattkrick** [comment]
- orgs & teams don't have anything to do with users that share an email address.
- Today, it is impossible to create multiple users using different authorities. If they try, they'll get an error telling them to login using the opposing authority
- That wasn't always the case, and there are about 25 users who have 1 gmail & 1 username/pass login for the same email.

- if we want to merge those ~25 accounts, it'd be a lot of work.
- delete the user that uses the password (since oauth guarantees validated email)
- clone each org user
- clone each team member
- clone each meeting member
- reassign every task
- reassign every agenda item
- reassign every reflection
- reassign every vote in every retro meeting
- reassign the team member in every team
- 
- yada yada, it's pretty laborious & if we miss 1, it's a broken app, since the server guarantees those lookups to exist

**Comment by jordanh** [comment]
This has been implemented well enough. Closing for now!
