### ISSUE TITLE
Connected meeting avatar enhancements

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3274]
Now we show connected teamMembers in the top right, with overflow into a count (+N) avatar based on a breakpoint. The farthest right component is the invite button with the `person_add` icon, always visible. Here are some suggested improvements to presentation:
### Comments
Animating in avatars and connected overflow count [from MK](https://github.com/ParabolInc/action/pull/3269#issue-328026776)
>I think a nice addition would be to add animations when people connect/disconnect. we can copy the code from the atlassian domain icons. the overflow number could roll up when incremented & down when decremented.

Regarding viewer’s connected state [from MK](https://github.com/ParabolInc/action/pull/3269#discussion_r335147705)
>yep! the tricky part is that the viewer may not be connected & we don't want to show them as connected if they aren't.
>i guess we should design out what it should look like when the viewer isn't connected? maybe...
>- don't show their avatar
>- show others' avatars as faded
>- show the overflow count avatar as gray

### Acceptance Criteria
- Design uncertainty is low, we can implement improvements based on written criteria
- Animates avatars in/out based on connection
- Animates the overflow count avatar in/out
- Animates the overflow count number value when it changes
- Has a disconnected state for the local viewer

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@mattkrick at some point, do we want the avatars to represent that a user is in the same place e.g. team dash, meeting, etc? The change is we would only show an upper-right avatar in the meeting if they’re actually at some phase/stage of that meeting. If they’re at the team dash, we wouldn’t show them.

**Comment by mattkrick** [comment]
i think the razor for show/no show is connected.
i say this because it'd be weird seeing someone disappear from the team dash when they navigated to my dash or settings or something.
i think _where_ they are in the product is a property.
but, i don't wanna be overly creepy (Matt is in Team Dash, now he's in User Dash)
so, i'd say for the Team Dash Avatars, we simply say "Matt is in the Product Meeting". see #3300. or Maybe "Join Matt in Product Meeting" so you can join, too.
in the meeting, i'd say we show the avatar, but if they're not in the meeting itself, then we just have some UI affordance (either no affordance, faded avatar, avatar moving left/right or spinning slowly to show they're wandering, etc).

**Comment by ackernaut** [comment]
I think we’re thinking along similar lines. For the dash views I think we simply show if they’re connected or not. But it can be of interest to know if somebody’s in a meeting space kind of like a Google doc. Also, to afford the “Matt is in the Product Meeting” we do need that property. At any rate, I don’t think it blocks the UI enhancements outlined in this issue.

**Comment by mattkrick** [comment]
yeah, i think `Meeting/NonMeeting` is about as granular as we should go from Team Dash.
From the Meeting, maybe not even show the difference. Just let them assume everyone is present & focused.
It's tricky because we have to account for multiple tabs/devices, so we'll have to make a hierarchy: e.g. `Matt is in Meeting 1/Meeting 2/Dash` should resolve to `Matt is in Meeting 1`.

**Comment by ackernaut** [comment]
- Maybe `Matt is viewing 2 meeting spaces`
- And being present in any view of a single meeting means their avatar shows up in that meeting
Just more ideas! Fun UX to solve for…

**Comment by ackernaut** [comment]
Marking this as stuck…this is taking me longer than I think the task should (need to focus on other things). I’ll need some pointers.
