### ISSUE TITLE
Reflect phase remains open until vote phase is reached

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3312]
Helps address certain aspects of #2948, see [Product team discussion](https://parabol.slack.com/archives/C836NA350/p1572559640017800) 🔒 

### AC
- The reflect phase remains open until the vote phase is reached. Then the reflect and group phases are read-only.
- Users can CRUD reflections from the reflect phase when the group phase has been reached.
- Must resolve bug: #3254

### EE
- 10.5 pts

EDITS:
   - JRH: added #3254 to AC

**Comment by jordanh** [comment]
Ah, came here to open this one myself. Thank you for writing it up.

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/7651451) wrote: 

> Yes, we are attending the meeting at the same time, but we do the initial data gathering, so adding of cards asynchronously, then I will usually try to group the cards just before the session, so that we can arrive in the session, do our check-in's run through the groups, vote and then discuss. The reason for this is that my team is large (up to 12 people in a retro), so this just helps us to have more time to chat. 

The tricky thing here is as a facilitator I want to group the cards, but we might also have team members wanting last minute ideas to get added. You do still allow us to add cards in the group phase which I have been very grateful for because of the 'peeking ahead' as you called it.

We are still very much still experimenting and working out the best approach, but this is what we are doing at the moment.

**Comment by jordanh** [comment]
Related to:

- #2948 (lots of user feedback on this one)
- #3254
