### ISSUE TITLE
New user not added to team dash upon mass invite accept

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3390]
## Issue - Bug

1. Login to Parabol as User A and User B
2. As User A, create a new team called "Test Team"
3. As User A, Invite User B to "Test Team" using mass invite link
4. As User B, using invite Link. Note: 2 users will appear on team dash for "Test Team"
5. As User A, note only 1 user appears for "Test Team"

### Acceptance Criteria (optional)
Inviting users can:
   - See new users appear on dash as invitations are accepted

**Comment by mattkrick** [comment]
OHHH boy, this is a fun one.
- This is caused only when someone initially logs in (no persisted authToken), they send the subscribe message to the server before the server has time to set up the listener.
- when someone has a persisted authToken, the server has time to set up the listener.
- the call that is preventing the setup from happening fast enough is the `connectSocket` mutation.
- that call is necessary to activate the user, tell team members they're online, send a segment event, and set a fresh auth token, if needed.

if we don't wait for those things, then the subscription request that comes use an invalid token, so we need to verify that token before setting up the subscription.

so, we could either tell the client the socket isn't ready until we send an ack that it's complete.
or, we could queue the messages on the server.

the first is simpler, but introduces a latency of 1 round trip. while that's bad for queries, it's especially bad for subscriptions because that means the client may not receive the update & have stale data without knowing it.

so, we got for the 2nd. it means we store a few thunks on the socket's connectionContext for < 1 second. i think that's a fine price to pay.
