### ISSUE TITLE
Comment threading architecture designed

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3552]
## Issue - Enhancement

See: #3334 and #3545 

### Acceptance Criteria (optional)

   - Design issue parsed and impacts to:
      - Schema defined
      - Business logic defined
   - And, opened as a series of implementation issues

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
there are 2 ways to treat threadables:
- a threadable could be an interface of Comment and Task, which would require that we add `threadSortOrder` on each object
- a threadable could be an entity with `id, type, sortOrder`

the first option is better if we add more & more fields to the thread item itself (e.g. upvotes, multiple items, ???). the first item is worse because it requires an extra hit to the DB. first we have to get all threadables for a threadId, then for each threadable we have to get the type, and hit each DB table for each type present.

i'm leading towards the 2nd option because there is no penalty to the user, it's only a DX penalty (more fields on an object). NoSQL makes this nicer since it's OK to have a bunch of empty columns. If we want, we could create a `ThreadableTask` that has those fields guaranteed. Then, any thread would return an array of Threadables, which is an interface of `ThreadTask` `ThreadComment` etc.

- 1 reflection group has 1 thread
- 1 thread has many  threadables
- 1 threadable is an interface of a `ThreadableComment` and `ThreadableTask`
- a ThreadableTask is a superset of a Task with `threadSortOrder` and `threadId`
- a ThreadableComment has `threadId, threadSortOrder, createdAt, createdBy, content, updatedAt, isActive, reactjis, parentCommentId`
- a Reply is a Threadable with a parentThreadableId. a parentThreadableId is a compound key with the type & the id. clicking reply automatically at-mentions the author of the parent. removing it removes mention notification, but it stays a child.

MUTATIONS
- postReflectionComment(reflectionGroupId, parentThreadableId)
- 
 
FUTURE (out of scope)
- Comment and Task both have an optional `reflectionId` entity in the content.
- if the reflectionId is present, then we look up the reflectionGroup & pull the title & add the discussion number to the end to create the label eg `Time Off (#3)`
- clicking on a reflection will filter to only those threadables or threadables with parents that reference that reflectionId
