### ISSUE TITLE
Billing

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#366]
## Issue - Enhancement

Enclosed are some ideas. Treat them as proposals, not sooth.
### Overview

Billing is accounted for by summing an organization's and **credits** and **debits** into a figure known as a **balance**. At the end of each billing cycle, we will attempt to charge the balance to the organization's **billing information** and receive an equal credit for the balance.

An organization may have its own billing information, or, may receive a credit for its balance by passing its parent organization if invited.
### Credits types

There are a two kinds of credits:
- **recurring billing**:  special credits applied only to organizations will valid billing information; these do not apply to organizations that pass their costs to a parent organization
- **one-time**: special credits/coupons, and rewards for certain events
### Credit incentives

We want to incentivize certain behaviors in order for users to get the most out of our system, and convert to paying customers.
- **recurring billing**:
  - **free active users**: we apply a credit to top-level organization for up to 4 free users
- **one-time**:
  - **new active user**: when a user becomes active for the first time, we apply a credit for one user-month of service
  - **streak**: when a team meets two weeks consecutively, three weeks, or four weeks consecutively we credit them with one user-month of service. We badge this heavily on the team and organization page.
  - **fast billing info added**: we give a one-time credit when billing info is added, offered only during the first 30 days
  - **reimbursement**: reimbursement for a support ticket, one-time discount, etc.

(more TODO)
- **Estimated effort:** 10 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Assuming that one can sign up, start a team, and try the software—is there a time limit until that team has to create or join an organization for billing purposes? How long are we thinking?

**Comment by jordanh** [comment]
I'm thinking there is no time limit: you can use us for free for up to 4 people forever. If you have more than 4 users, we'll turn the folks who joined last off first until you give us billing info.

**Comment by ackernaut** [comment]
I have a question about invoices that get paid for by parent organizations:

I am an organization. I have 4 user credits by default, and 5 active users. I don’t pay the bill, but rather submit it to my parent organization. Do my 4 user credits go unused, and the parent organization has to pay for 5 users? To make it more complex, my parent organization has the same stats: 4 user credits and 5 active users.

Does the parent organization pay for 2 users inheriting my user credits (making 8 discounts)? Or does the parent organization pay for 6 active users (my five, and their 1 because they only have 4 user credits)?

**Comment by ackernaut** [comment]
How many parent-to-child org. levels can there be?

**Comment by jordanh** [comment]
@ackernaut such good questions! I thought about this a lot more last night after we spoke.

**On credit:** I think what we actually want to do is message _up to 4 free users_ and apply it as a one-time coupon at the end of the billing cycle. If for example, they only have 3 of 4 free users active, we only show an end-of-month coupon credit for 3 users.

Also: this credit is only applied to the top-level organization. So, there can only ever be up to 4 free users organization-wide.

**On parent-to-child org levels:** my thinking on this changed somewhat since yesterday. Looking at your initial designs and thinking about some of the use-cases around this it could be a lot of work. And we don't want a lot of work right now. We want the shortest road to turning on the cash register.

What I think we might want to do is more Slack-like: instead of allowing orgs to have orgs, I think perhaps we only allow for teams to belong to *one* org and one billing entity. Then, the job story is:

When I find out other teams in my company are using Action and I want to join them, I want to merge our organizations together, so that we only pay one bill.

So, what we do instead is allow organizations to merge by allowing users to request merging with another org either by email invitation or discovery by email domain. That should _vastly_ simplify things. Right?

In the future, we can do orgs of orgs.

What do you think?

**Comment by ackernaut** [comment]
Ooh, two things:

1) I like merging orgs, definitely!
2) I didn’t pay enough attention to your original comments on only top-level orgs having 4 credits. However I would still see a problem which we would perhaps solve like this: Your org keeps 4 credits until you defer payment to a parent org. Then all of a sudden you are a cost of +4 users plus whatever additional count you had. It might feel bad losing those credits just because a parent org is paying but its the only way.

Some more thoughts:

- I think we use recurring credits first (the big 4) then we use one time credits. Recurring credits do not transfer month-to-month.
- When orgs merge, perhaps they get a credit per total team count just to incentivize merging. In other words, I could create an org for each team of avg. 7 and get 4 credits and only have to pay for 3. Why would I merge to one org and lose all of those discounts? But if we give a shot in the arm when orgs merge, then maybe the added value makes it worth it?

A scenario:

- Engineering adopts action and creates an org to pay the bill. Team size: 7, paying for 3 monthly
- Talent adopts action and creates an org to pay the bill. Team size: 7, paying for 3 monthly
- Product adopts action and creates an org to pay the bill. Team size: 7, paying for 3 monthly

Hey, let’s merge! Now I am down to 4 credits for 21 users so I am on the hook for 17 users instead of 9 (difference of 8). Sure it’s easier to manage one account, but the value difference is $40 a month which might mean something to a scrappy, small company.

What incentive do we give to merge? The three orgs merge and each get a one time additional coupon of 4 users? That is 12 discounts? That means for a month and a half they don’t feel a difference in the prices (8 + 4 = 12 where 17 - 9 = 8).

All that said, it would be a good problem for us to have!! Maybe small companies can stay scrappy and just manage multiple accounts (a win for them) and large companies win from stream-lining their accounting (but pay more).

**Comment by jordanh** [comment]
Yeah, I thought of that "two teams merge, we loose free users" negative incentive. On the other hand, you gain team communications across teams and team transparency right?

I think the shot-in-the-arm incentive for merging teams is interesting. Let's keep that one in our back pocket.

**Comment by mattkrick** [comment]
We could make it 4 free users for 3 months. That puts on upper bound on the gasification, then the switching cost to stay free includes a fragmented history and copying over actions.

**Comment by ackernaut** [comment]
@mattkrick I like that! @jordanh and I were just discussing some ways to throttle this—but overall I think our expectations/assumptions are correct in that we want to ease on-boarding and deliver value over time.

**Comment by jordanh** [comment]
@mattkrick it's a good point. Probably the safest thing to try if we make the offer expire. If we see a lot of churn, we can reevaluate.

**Comment by jordanh** [comment]
Meta. For reference only.
