### ISSUE TITLE
TypeError: Cannot read property 'openArea' of undefined

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#437]
Hey cool. Our very first production issue reported from sentry:

https://sentry.io/parabol/action-production/issues/173793828/

```
TypeError: Cannot read property 'openArea' of undefined
  at Connect.mapStateToProps [as finalMapStateToProps] (/static/2_14bd9e3a3737243aaa1a.js:7112:39)
  at Connect.computeStateProps (/static/vendor_df1255373436dc61f63e.js:22488:67)
  at Connect.updateStatePropsIfNeeded (/static/vendor_df1255373436dc61f63e.js:22546:35)
  at Connect.render (/static/vendor_df1255373436dc61f63e.js:22681:40)
  at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/static/vendor_df1255373436dc61f63e.js:33286:34)
...
(17 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
Looks like the the exception is occuring here: https://github.com/ParabolInc/action/blob/v0.9.4/src/universal/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.js#L25

**Comment by jordanh** [comment]
This is just dope:
![image](https://cloud.githubusercontent.com/assets/103000/19687436/5aaab9e4-9a93-11e6-9174-863a5cf39988.png)

**Comment by mattkrick** [comment]
i could write this more defensively, but i'd really like to figure out why that form field doesn't exist, because it should always exist. if you find any repro steps, lemme know!

**Comment by jordanh** [comment]
Yeah, this one is a fun one. Have you looked at the variety of stack traces on sentry.io itself? Some interesting clues in there.

One of the more interesting bits to notice is that it appears as though this exception can occur either 1) from an upsert or remove event coming from the socket or 2) from some local click event.

**Comment by mattkrick** [comment]
From slack: 
```
I moved a card to Done

[11:47]  
then I tried creating a new Card in the Active column

[11:48]  
and on each keystroke I get the `openArea` error

[11:48]  
well it looks like it happens on hover and focus too
```

**Comment by mattkrick** [comment]
Things we know:
- this happens more frequently (always?) on a remote connection. So, it could have something to do with server latency
- It is triggered by moving a card to Done. Changing a card status doesn't remove/add, so it probably isn't triggered by the client cache.
- it occurs when state.outcomeCard[form] doesn't exist. That means it was never created in the first place, or it was recently removed.

until we can reproduce this reliably (with the debugger open) everything i do is just gonna be a guess.

**Comment by jordanh** [comment]
Is there more instrumentation we could add?

**Comment by mattkrick** [comment]
The redux history would be the gold standard, but we can't get that in production.
I think the next step is to narrow it down to whether it was never created, or if it was recently removed. We can figure that out by logging every single `form` name to an array & then sending that array with the error report. memory leak city for production, but that might be what we have to do.

**Comment by jordanh** [comment]
Perhaps this would be a good start: https://blog.sentry.io/2016/08/24/redux-middleware-error-logging.html

I'll start a branch...

**Comment by jordanh** [comment]
Ok. Just about to push a branch and make a PR with this debugging enhancement.

While testing, I also unintentionally reproduced this #437. See: https://sentry.io/parabol/action-staging/issues/175651407/

**Comment by mattkrick** [comment]
I _think_ i found it:
![screen shot 2016-10-31 at 8 57 48 am](https://cloud.githubusercontent.com/assets/5514175/19861009/2701f012-9f48-11e6-98d1-71598256660f.png)

redux-form is unregistering and then it isn't registering again until _after_ we look for the `form` field. 

To fix, we shouldn't unregister that field unless we delete the item.

let's still do the PR to make sure we catch it, but I think this could be it.

**Comment by mattkrick** [comment]
Dnd made this _real_ easy to find.
Basically, an outcome card gets mounted, then when you drag it to another column, it gets mounted again, and then unmounted. that ain't good. we wanna unmount, and then mount. 

we solved this in cashay by sending in certain fields that determined if we were unmounting the right thing. we could do that, but that is a little hacky since we shouldn't have to store document data on the card itself.
the package i wrote awhile back (redux-operations) solved this by prioritizing synchronous events. That guarantees that unmount always gets called before mount.
We could store a datestamp when it was mounted and when unmount was called. then, we async dispatch unmount if mount time < unmount time. 
we could move the state back into the component.
i think the last option would be the easiest. if we do make a legit component library, using redux-operations is probably the way to go.

**Comment by jordanh** [comment]
The arbitrary execution order of reducers is such a shame. Glad you could find a case that made this easy to reproduce! This will be such a good one to get patched up.

I like the last two options best. Let me know if you want to talk it out at all! I'll be around all day.

**Comment by mattkrick** [comment]
1 more option-- we include the status in the form name, which I believe is the solution you came up with for moving cards across columns. I think i'll do that for now since it's the fastest.

**Comment by jordanh** [comment]
This would fix it between columns for drag-and-drop, but not for the bug we're already seeing on production – right?

Could we also consider adding some defensive code and a comment to avoid that case?

**Comment by mattkrick** [comment]
dug into it, actually how we were doing it (different form for each column) doesn't work for anything because we don't update the target component props. So:
- [x] put state back into components (faster, less noise in the redux-devtools)
- [x] remove status from form name
- [x] set redux-form destroyOnUnmount: false
- [ ] figure out where to destroy the redux-form (when they delete a card, archive a card, or navigate away from the entire page). Tiny memory leak right here.

**Comment by jordanh** [comment]
Oh yeah. This is a good way to go!
