### ISSUE TITLE
Action disappears when creator reassigns to different owner

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#442]
## Issue - Bug

Steps to reproduce:
1. Start action meeting
2. Proceed through phases, adding agenda item
3. When item is being processed create a new action and hit enter to submit
4. Click on action's avatar to reassign and choose a different owner
5. Note that action disappears
- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
i reproduced this _once_ but can't get it to do it again. any other tips?

**Comment by jordanh** [comment]
I just tried to reproduce this on the `elect-new-facilitator` branch and cannot. Let's leave this open and see if we run into it again...

**Comment by jordanh** [comment]
Ran into it again during this week's action meeting. Some new data: the Action will disappear for the original Action creator but it will remain for the other meeting participants. Spooky 👻 !

I suspect it's probably in the logic that destroys empty cards...

**Comment by mattkrick** [comment]
ohhh boy, found it.

so, recently i fixed cashay to not remove entities when they were deleted.
for example, Sub Foo returns [A,B].
Query Bar returns B.
now B gets removed from Sub Foo.
Sub Foo is now [A]
but i leave B in the cache because Query Bar still needs it

(in the real word, B is your name & email, because we initially query for those things, and then subscribe to users in organizations/members. when you delete yourself from an org, we don't want to remove your name/email!)

So, in `meetingAgendaCardsContainer`, we are pulling out the cached things. the action no long exists in the `actionsByAgenda` but it does exist in the entities.

so the question that remains is how do we filter out the deleted ones?
the easiest thing that comes to mind is ditch the graphql union and union it on the front end...

**Comment by mattkrick** [comment]
er, to be clear, this will solve the "hey i created an action and now it won't go away" problem. i'm betting the 2 have the same root cause, but i couldn't reproduce the one listed here.

**Comment by jordanh** [comment]
Wowee! Nice find and I can't wait to see if this covers both cases.
