### ISSUE TITLE
Push toast and logout on new version

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#480]
## Issue - Enhancement

When we push a new version, a user isn't forced to log out until they navigate to a new route. We should enhance their experience by detecting the version change, popping a toast explaining that a new version is available, and logging them out.

Implementation notes/requirements sketch:
- On a server update, the socket connection will bounce.
- When the socket connection is re-established we could include the version number.
- If the version number has changed, we could pop the toast & logout

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ndey96** [comment]
I was only able to replicate this logout scenario by:
- booting the server
- connecting to localhost:3000
- updating the version number in package.json and allowing the server to re
- refreshing the localhost:3000 page in the browser

This caused the client to logout and receive the unauthorized toast reading 'Hey! You\'re not supposed to be there. Bringing you someplace safe.'

in makeStore.js the client already checks to see if it’s version matches the server’s (line 59)

If the version is out of date we can pop a toast from here saying something like “You were logged out because there is a new version of action available.”

@jordanh what do you think about this solution? I wasn't sure what mechanism to use to detect if a new version is available before a logout is forced. I was thinking of adding an endpoint to query the version number but that seemed like overkill for this.

**Comment by mattkrick** [comment]
@ndey96 here's what's happening:
- there is a higher-order component (`requireAuth`) that makes sure you have a token in your redux store for pages that require auth
- when you change versions & restart, the code in `createStore` sees that the redux-store that is persisted in local storage doesn't match the version coming down the wire, so it doesn't rehydrate the state
- since the auth credentials are stored in the state, and the state isn't rehydrated, then you're essentially trying to access a member's only page w/o any credentials, so you get bounced (hence the toast you see)

You won't be able to pop a toast from `makeStore` because that is run pre-render cycle (ie it isn't part of a component). 


**The scope of this issue** 
- The hook you'll want to work off of is a new websocket connection, so you could emit a message from the server saying something about the version whenever a new connection request comes in.
- That websocket message could then be listened to by a component (probably ActionContainer) that turns it into a toast.

**The next issue (out of scope, call it extra credit)**
- we don't necessarily need to log them out, their auth credentials are still good. it's just the rest of the state (both local and domain) that could be stale.
- so, do everything logging out does while keeping the auth part of the state intact. That way, the only thing they might lose is their current working state. (which is fine for now, when the time comes, we can write local-state migrations for each new version if need be).

**Comment by jordanh** [comment]
@ndey96:

Greetings from Whidbey Island, Washington! 🎅 

You've correctly identified how we detect a new version of the Action application today and de-authenticate users. The solution you provided doesn't quite cover the implementation requirements. @mattkrick gave the background why and how possibly to implement it.

To give you some pointers:

1.  When a user initiates a websocket connection to the server, the server should respond with a message that includes the application version number (see: [scConnectionHandler.js](https://github.com/ParabolInc/action/blob/998a207f70be2e433de94c70259a6630a7a2ef9a/src/server/socketHandlers/scConnectionHandler.js))

2. When the client application receives the version number message, it should be caught by a React component that can pop a notification, as @mattkrick consider adding this location to [ActionContainer](https://github.com/ParabolInc/action/blob/47e3310bd14b9896ab163e19dc0731d23cd61aaf/src/universal/containers/Action/ActionContainer.js)

3. The server and client will then need to communicate using a socketcluster event, you might want to review this API: http://socketcluster.io/#!/docs/api-scsocket-client

Let us know if you have any questions. You may ask them here or [join us on our developer Slack](http://slackin.parabol.co/).Try to have something put together by the 4-Jan. It doesn't have to work completely. We strongly recommend putting together a non-working pull request early, and asking questions as you go along!

🎄 Happy holidays! 🎄

**Comment by ndey96** [comment]
Hey guys,

Opened this PR: https://github.com/ParabolInc/action/pull/600 to address this issue :)

Have a great new years eve!

**Comment by jordanh** [comment]
Closed by #600. Great work @ndey96! 🎆 

[Crediting you for 12 points](https://docs.google.com/spreadsheets/d/1V1KZJn6oKFsqrYwqr430rO3hkIkekSY7oYFzX3cVty4/edit#gid=679741853). Your current total is: 12 points!
