### ISSUE TITLE
Facilitator goes to next agenda item, interrupts active card interaction

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#490]
## UX Bug

**AKA Interrupting Chicken**

When a team member is editing a card, and currently at the agenda item where the facilitator is, the card interaction gets interrupted if the facilitator goes to the next item.

First ideas:

My current suggestion is to detach navigation from the facilitator when a user is at the same agenda item route or update route, but actively editing/updating a card.

In the future, if we implement the re-center button, this would show when the facilitator moves forward. Until that shiny future, the user would have to navigate back to where the facilitator is in order to ride that automagical nav wave again.

**Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
this is a tough one. if the person is adding a card during a meeting, that means there's value in the rest of the team seeing it. if that assumption holds true, then allowing the rest to move on without him means that a) it isn't valuable or b) the facilitator will have to go backwards. Neither is great.

My proposal is to wait until we send data per-keystroke. The facilitator will have a `lastOutcomeKeystroke` timestamp that represents the last time a team member entered a key on an outcome card while in the same phase & phase item as the facilitator. If that is < 1000ms, then instead of navigating, we pop a toast for the facilitator saying that someone is still typing.

**Comment by mattkrick** [comment]
the fix for this is to flag the person as `!inSync` if they are currently editing a project.
