### ISSUE TITLE
S3/CDN Configuration Enhancement

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#493]
## Issue - Enhancement

At present I've configured us with two S3 buckets:

- action-files.parabol.co (Production)
- action-files-staging.parabol.co (Staging)

When we build, we're uploading to `/static` within the each bucket.

I propose we make the following changes when we go to beta.

1. We consolidate down to a single bucket, action-files.parabol.co
1. There are two top-level directories on the bucket:
   - `/staging/`
   - `/production/`
1. Within these directories there are two more paths:
   - `/(production|staging)/build/vX.Y.Z` - the current build
   - `/(production|staging)/store` - user objects, like avatars, etc.
1. We set `basePath` on the`webpack-s3-plugin` according to the current version from `package.json`
1. We automatically append `CDN_URL` with `build/vX.Y.Z` by modifying `getWebpackPublicPath.js` to import files from this new URL

- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
will this bork our staging when we try to replicate a problem found on production?

Scenario:
- My avatar is upside down in production
- I write a fix for it
- I push that fix to staging
- i don't even have an avatar on staging because it only exists in production

should we treat this like the DB where we eventually replicate the entire production to staging?

**Comment by jordanh** [comment]
We should treat `/store` like another database. We'll need to replicate it back to production from staging, just like we do now.
