### ISSUE TITLE
condense 2nd column

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#497]
## Issue - Enhancement

In Dashboard view:
1) Move "My Actions" underneath "My Dashboard" on the left column = gain a whole column of empty space.
2) Likewise, move "Agenda Queue" under "Add New team"

**Comment by jordanh** [comment]
Could you draw a sketch of how this would look? I can't quite visualize #1. For #2, I'm afraid the agenda queue's association with an individual team might get lost or become ambiguous.

If the core of the issue is around spacing, would #463 (making the columns collapsable) address what you're sensing?

**Comment by tayamueller** [comment]
ah, yep #463 gets to the heart of it (lots of wasted white space), thanks. 

I suspect once the leftnav starts filling up we may also want some collapsible sub-features there similar to GDrive leftnav arrows
