### ISSUE TITLE
audit all queries/mutations for requireWebsocket

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#503]
lock it down for ex-teammembers

**Comment by jordanh** [comment]
I was mentally exhausted yesterday, apologies if I didn't bring a lot of fresh ideas to token management. I woke up thinking about it this morning and wanted to jot down some thoughts while they are fresh.

Take these as just thoughts. Even if we like any of them, we need not implement any of them now.

Job story
----------
First, let's write out the **job story**: when a user is removed from a team (or marked inactive), the system wants to de-authenticate them from the team, so that they no longer have access to the team or its data.


Constraints
------------
1. A token contains team membership; if the team appears on the token _and_ the token is valid, the system will grant them access to the team
1. We use tokens for team membership system-wide to avoid hitting the DB on requests (which are frequent and real-time)
1. A token is valid until it expires


Key design tension
-------------------
A previously issued token is valid long after access is revoked for a particular team.


Design
-------
**When a user logs in**
1. Issue an identity token with the `exp` field set for 1 hour
1. Obtain a [refresh token](https://auth0.com/docs/tokens/refresh-token) that never expires

**When the identity token is about to expire**
1. If the client remains open, the client establishes a task to request an updated identity token using its refresh token before it expires. This is done quietly and asynchronously in the background
1. When the new identity token is received, it may contain changes to team membership (n.b. this has the following implication: an attacker may only use an old token to access team data for up to one hour)

**When a team leader ("TL) revokes access to a team from a team member ("TM")**
1. The TL's session updates the app metadata removing the TM's access to the target team on auth0 using the management API
1. If the TM is online, the system sends them a `REFRESH_TOKEN` message
   1. Upon receipt of the `REFRESH_TOKEN` message, the client immediately and asynchronously uses its refresh token to request a new identity token from auth0
  1. The new identity token contains the updated `tms` list
1. If the TM is offline, we wait until the websocket connects before executing the above

**When a session is restored from localStorage**
1. If the token has expired, the client uses the refresh token to try to reauthenticate
1. If the token has not expired, it is used to continue to access the system

**When a user is removed or banned from Action**
1. An action administrator uses the auth0 control panel to disable the user account, this will revoke their refresh token
1. The next time the user's identity token expires, they will be unable to use their refresh token to re-authenticate to the system

**Comment by mattkrick** [comment]
@jordanh reference token! that's what we're thinking of: https://leastprivilege.com/2015/11/25/reference-tokens-and-introspection/

**Comment by jordanh** [comment]
I think we can close this now, ja?

**Comment by mattkrick** [comment]
nah, i still need to do this... basically go through every single query/mutation & ask myself if it's cool if an ex-team member calls it. If it's not cool, then I need to close it up.
