### ISSUE TITLE
Cashay warning while proceeding through check-in round

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#536]
## Issue - Bug

This one is also frustratingly intermittent. I was only able to see it once:

Steps to reproduce this one:

1. Start a meeting
2. Proceed through check-in round

![image](https://cloud.githubusercontent.com/assets/103000/20547858/f349fbd2-b0ec-11e6-9d6b-2ac086ceb6ab.png)

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
now _this_ one is gonna require rewriting a bit of the cashay mutations API.

**Comment by mattkrick** [comment]
just hit this one a few times. this is a showstopper, so i'll do a hotfix.

**Comment by mattkrick** [comment]
so i dont forget:
this is caused because cashay currently caches something called `activeQueries` which are all the queries that have mutationHandlers for the given mutation (in this case, something called `updateProject`). If these queries are no longer required, then they no longer have responses (eg i navigate away from the user dashboard, i no longer need the userColumns query, so it is undefined).  However, the activeQueries would still have that listed, which is no good.
Even if we compute activeQueries for each mutation, we still might hit an error because if `ops` is left blank, then cashay assume that means the mutation could possibly invalidate every query with the corresponding mutationHandler. To prevent bad habits and slow performance, cashay throws an error if such a query has multiple keys (eg teamContainer for team123 and team456).

Since we get our data from a subscription, we don't have to worry about mutation handlers for most of these things, so we can solve this by telling it that this mutation doesn't affect any queries (eg `ops: {}`).
