### ISSUE TITLE
User settings validation

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#602]
Just wanted to see if this was a bug. When I click into settings I get a validation error just by blurring the name field.

[Vid](http://recordit.co/vb4wX3eqdm)
[Gif](http://g.recordit.co/vb4wX3eqdm.gif)

- Seeing this on latest master!
- Not seeing this in production!

**Estimated effort:** 1 point ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
definitely a bug!

**Comment by jordanh** [comment]
I just got this one. Fun little bug! redux-form's default shouldValidation function _always_ returns true on initial render. This is a no-no on some of our forms. The killer combination is 1) cashay returns `null` on initial query (as per usual) 2) the form is autofocused causing `touched` to be `true` this causes the validation function to be called with empty data and the error to then be rendered next to the component.

The fix is to define a new shouldValidate function that never validates on initialRender. Works like a champ!

**Comment by jordanh** [comment]
(fix coming shortly on s3 branch PR)

**Comment by mattkrick** [comment]
ahhh i get it... the form initialization occurs _after_ the validation function runs. Booo.
Nice helper function! I've been meaning to write that for some time now...

**Comment by ackernaut** [comment]
Ooh, I like what you guys have cooking here! 🔥
