### ISSUE TITLE
Team name duplication, possibly on socket disconnection

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#603]
## Issue - Bug

I was on some janky hotel WiFi yesterday and saw this:

![image](https://cloud.githubusercontent.com/assets/103000/21662659/eb5f2e5a-d28f-11e6-9ece-638e718a2960.png)

Note the duplication of the **Wedding** team. When I hover on the second **Wedding** link, here's its URL: `https://action.parabol.co/team/null`

What I'm thinking is some kinda Cashay call is timing out and creating a new entity with a `null` id. Since this occurred on the production instance, it's difficult to confirm.

Thinking out loud: should entities be subject to validation criteria too?

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** 3 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
that sidebar is populated by our `@cached` logic, which means it looks through the whole cache & grabs all the teams you have in it. 
So, the question is: how did a team without an id get into the cache?
that directive will defensively create an object because sometimes we might request a cached item before it gets delivered. it quickly gets replaced when the actual item comes down the pipe though, so how you got 2 really baffles me...

the quick n dirty fix is:
```
resolveCached: {
  teams: () => (doc) => doc.id
}
```

but something tells me that this is linked to the weird error that everyone but me experiences when reassigning items during a meeting.
