### ISSUE TITLE
Summary email Subject line

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#643]
## Issue - Enhancement

The current Subject line of the meeting summary email reads:
 "Action Meeting Summary from Parabol"

Would it be a simple fix to change it to read:
 "[Team Name] [MM.DD.YY] Action Meeting Summary"
 e.g. "ExCo 01.16.17 Action Meeting Summary"

Seems preferable for archiving purposes & finding/reviewing old Summaries

**Comment by ackernaut** [comment]
I like this thinking!

**Comment by mattkrick** [comment]
I love the team name!
I think we could improve on the datestamp. If they're gonna look through old emails, it'll probably already be sorted by date, but if for whatever reason they decide to sort emails by title, having the month first will still yield the sads because 12.01.2016 and 12.01.2017 will be right next to each other. i'd rather do YYYY.MM.DD or a pretty March 20, 2017 or even a "Meeting #10". I'll start with the pretty one for now & we can change later
