### ISSUE TITLE
Add pan to scroll functionality across action

### ISSUE THREAD

**Issue by ndey96** [ParabolInc/action#662]
It would be really useful if I could pan (aka click and drag) to scroll sideways throughout the action app.

This would be awesome because:
- My mouse only has vertical scroll which makes side-scrolling a pain for me :( 
- My browser windows are usually never wide enough for me to view the entire action app and it would be awesome if I could do that only using my mouse

Trello has an implementation of this which is one of the first things that struck me about their product actually.

**Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Can you screenshot or record a gif of what you're seeing?

**Comment by ndey96** [comment]
@jordanh 

Here is a screenshot of what my action looks like:
![screen shot 2017-01-29 at 8 21 23 pm](https://cloud.githubusercontent.com/assets/10405248/22410053/123f038a-e661-11e6-8aec-c5920f4a20d0.png)

Here is a gif which illustrates how trello has implemented this behaviour: 
![yx6evgrslx](https://cloud.githubusercontent.com/assets/10405248/22410065/30d56c1c-e661-11e6-963e-047dc98ba438.gif)

**Comment by jordanh** [comment]
Ah, so it's more about the minimum horizontal card size. @ackernaut how do you feel about this?

**Comment by ackernaut** [comment]
yeah, I think it’s time to make the cards start at 1 line in height; as for scrolling—currently, divs with overflow are going to show scrollbars in certain operating systems...we plan to roll out future improvements for responsive layouts, scrollable panels, etc.

**Comment by ackernaut** [comment]
Just searching around for examples in the wild:

It would be interesting to see something like this: http://smikhalevski.github.io/react-scroll-box/

With the added functionality of being able to grab in the window and drag. Perhaps something like:

https://gist.github.com/gaearon/150fa1bed09c92abdb46

??

Basically, the design spec is twofold: 1) we control scrollable panels (instead of default browser behaviors 2) we add the ability to drag inside the empty space (instead of relying on scrollbar dragging)

**Comment by jordanh** [comment]
One day!
