### ISSUE TITLE
A/B testing spec

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/action#7130]
# Goal
We want to be able to easily and quickly present the different versions of the app to different users and analyze their behaviour afterwards to confirm or reject a hypothesis.

Examples of these experiments include:
* changing the location or copy of the start meeting button
* changing the start page of the dashboard
* showing the user navigation hints
* showing a different new meeting dialog

## Sub-goals
* the results shall be analyzed with the existing analytics tools, i.e. Amplitude or data sanctum
* the experiment definition shall be available in data sanctum as well
* users from the same domain are grouped in the same segment to avoid confusion on the user side (avoid situations like Eric explains something to Hans but both see a different version of the product)

# Non-goals
## Analytics
We have existing tools and the A/B testing setup should only do the user segmentation and labelling.

## Splitting users based on certain criteria
Splitting users non-uniformly contradicts the experiment character where all groups should be selected uniformly.
However this does not contradict a use case where we have an orthogonal criterion to segment users based on application logic.
For example:
* app feature "Patient 0 dialog": only patient 0 users get shown a dialog
* experiment: group show patient 0 dialog and group do not show patient 0 dialog which will be applied to **all** users

# Out of scope
These features might be added later, but are not part of the first version
* other than normal distribution of users
* segmenting users without domain affinity

# Architecture

## Database
Experiment definition should be available in data sanctum, thus it's best to store it in a separate table.

See #6796 

## Setup
* mutation to create an experiment
* on experiment creation all users are segmented
* if a new user signs up, they will be assigned to a segment based on their domain

**Comment by Dschoordsch** [comment]
See also #6650 where some notes from initial discussions were added.

**Comment by avivapinchas** [comment]
Clarifying questions: 

> the results shall be analyzed with the existing analytics tools, i.e. Amplitude or data sanctum

Does that mean the data would be available for others to explore in either Amplitude or data sanctum, so non-devs and folks outside the squad could engage with that data? 

> the experiment definition shall be available in data sanctum as well

I take this to mean that what we're testing is stored in the data sanctum, is that right?

**Comment by jordanh** [comment]
Added comment on spec issue #6796: https://github.com/ParabolInc/parabol/issues/6796#issuecomment-1231956348

**Comment by Dschoordsch** [comment]
> Does that mean the data would be available for others to explore in either Amplitude or data sanctum, so non-devs and folks outside the squad could engage with that data?

Yes. The segmentation will be applied to the User object so will be part of the identify call to Amplitude. Since the data will also be in the User table, it will be in data sanctum accessible to everyone who can work with those tools.

> I take this to mean that what we're testing is stored in the data sanctum, is that right?
If we setup an A/B experiment we store
* the name
* name of the groups
* percentage of users for each group

This data should also be available in data sanctum to have the definition available in case it's needed.

**Comment by jmtaber129** [comment]
What's the dev experience like with this setup? I.e. if the experiment is created by executing a mutation, and we don't currently have a way to execute a mutation as a migration (nor should we), I imagine the step-by-step process is more complex than a simple "merge a PR", both to deploy an experiment to prod and to keep local experiment state consistent across engineers' dev envs.

I'm also interested in understanding how experiment state is exposed in order to show an experiment variant - e.g. if I'm creating an experiment to test optimal button placement called "start_meeting_button_placement", how do I fetch which bucket the current user is in for this experiment?

How/when are we sending experiment metadata to amplitude?

Are we including server-side experiments as part of this? E.g. slack notifications, emails, variations in GQL resolvers, etc.

What's the purpose of `randomSeed`? Shouldn't the default seeds of our PRNGs be good enough?

If we're assigning a variant to all users when the experiment is created, how should we run analysis on only users who saw the experiment?  E.g. adding new "Viewed experiment XYZ" segment events, etc.

https://github.com/ParabolInc/parabol/issues/6796 mentions that there will be an `experimentFlag` of the form `${experiment.name}_${experiment.group}`:
* Question: Does this mean that a given user can only be in one experiment at a time?
* Reaction: Assuming a user can be a part of multiple experiments, this seems like it would make grouping by experiment variants unnecessarily tedious, since we'd need to figure out which experiment flag is relevant to the experiment and then group by that flag specifically.

> Out of scope: other than normal distribution of users

This should be "other than uniform distribution", correct? I.e. this project is implementing uniform, not normal distributions?

## Suggested alternatives
Here are a few alternative approaches that might be worth considering. I don't have strong feelings on any of these, but I wanted to make sure we've considered alternative approaches.

### Setup
* Instead of percentages, use "parts of a whole", e.g. for an even ABC test instead of needing "33.33% A, 33.33% B, 33.33% C", we can do "1 part A, 1 part B, 1 part C".
* Represent an experiment by a single row in a table, with variant metadata being stored as an array (e.g. `[1,1,2]` for an ABC test with 25% A, 25% B, and 50% C) or json blob (e.g. `{"control": 1, "variant_name_2": 1, "another_variant_name": 1}`).
  * Pro: An experiment can be created by inserting a single row can be done via DB migration (see below)
  * Pro: Simplifies the data model
  * Con: We'd need to assign variants lazily, which is more complex
  * Pro: We'd need to assign variants lazily, which would implicitly exclude users who haven't been on the app during the experiment, which could ease analysis

### Dev experience
* Support adding an experiment as a migration
  * The experiment is reviewed as part of the CR process, alongside the code implementing the experiment variants.
  * The experiment is deployed when the PR is deployed
  * Experiments are created as part of normal migrations when a developer checks out a branch with the experiment.

### Data model
* Instead of storing an experiment flag directly in the "User" table (effectively denormalizing the org-level experiment onto users), what if we keep it associated with the org object only, and then resolve the experiment for a user in the graphql layer? That would guarantee org affinity, and potentially minimize bloat in the "User" table without added cleanup complexity

**Comment by Dschoordsch** [comment]
@jmtaber129 let's do it similarly to what you've suggested:
* add experiment via migration
* we add a helper for the migrations to assign the experiments to existing users
* one row per experiment
* let's not normalize the experiment flags on the organization, but add it to the user because that's easiest to access

**Comment by jordanh** [comment]
@Dschoordsch is it safe to close this issue now?

**Comment by Dschoordsch** [comment]
Yes
