### ISSUE TITLE
node dev piping broken

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#72]
## Issue - Bug

@mattkrick:
> piping is broken & i'm not sure why. When it auto-restarts, i get EADDRESSINUSE almost always. Also, it only worked in development, and we should be debugging server code in production.

@jordanh:
> This has been driving me nuts. Let's create an issue. I suspect it's because the SC worker process isn't exiting.
>
> I want to track this down either via a git bisect and a test script or adding a hook on exit that looks at node's run queue.

- **OS:** OSX
- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
So this is goofy. I tried to reproduce this on the airplane over to Germany and now I couldn't get it to break. Before I began I toasted an reinstalled `node_modules`. Is this still failing reliably for you @mattkrick?

**Comment by jordanh** [comment]
@mattkrick you pulled piping out of the codebase right? I bet it was related to why `npm run build:server` was failing. I wonder if it would work again if you re-added it?

**Comment by mattkrick** [comment]
Yup. TBH I don't miss it, but we can add in back in. If we do, we should turn it on only if a `DEPLOY` environment variable is false since it's only really useful when we're in `__PRODUCTION__` (if we're in dev mode that means waiting 15+ seconds for the server to restart & recompile the entire client webpack in memory).
