### ISSUE TITLE
Spinner Component

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#762]
Hey @ackernaut can you make a component for one of the spinners we have? We can iterate on it later, the main thing is we just need something to stick in that isn't a duck & isn't null.

**Comment by ackernaut** [comment]
👍

**Comment by ackernaut** [comment]
@mattkrick 

What are your thoughts about starting with one of these and polishing (props for color combos):
[http://codepen.io/mcraiganthony/pen/QNdqzy](http://codepen.io/mcraiganthony/pen/QNdqzy)

Otherwise does something generic like one of these get your attention?
[http://tobiasahlin.com/spinkit/](http://tobiasahlin.com/spinkit/)

**Comment by mattkrick** [comment]
i really like the 2nd one, i think that accelerated spin feels very familiar compared to apple/google products

**Comment by ackernaut** [comment]
@mattkrick Yep! I liked the 2nd one, too. Just wanted a 2nd opinion. I’ll start there, thanks!
