### ISSUE TITLE
Unarchive Teams

### ISSUE THREAD

**Issue by ndey96** [ParabolInc/action#801]
We should allow users to unarchive teams they have archived in the past. This constitutes:
- Adding a "Teams" tab to org settings and displaying all teams that belong to the org
- Teams which are archived should have an unarchive button

**Estimated effort:** 23 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
I'm not sure we need to see a list of all the teams under 1 org. Maybe we do. I just don't know.
Can you paint me a user story where this would be useful to an org leader? What kind of actions would they have? just an archive button? Could a team archive itself from their team settings?
Can an org leader archive a team that they do not belong to?

**Comment by ackernaut** [comment]
It’s hard to understand how archiving things may be valuable until we get more usage. I suppose if we are not giving an option to completely delete things then there may be a small value in digging around in old things. If we do start to build in insights/analytics then the old things may resurface when looking back in time. Instead of cluttering the active spaces they may live in an archive. Therefore it might be nice to have a direct way to navigate them. (Ready abstract response here.)

**Comment by jordanh** [comment]
@ackernaut I agree with your line of thinking here. I think we should deprioritize this until "The Future," unless we find that our intern runs out of things to do :)

**Comment by jordanh** [comment]
I added this to the [Equity for Effort](https://github.com/ParabolInc/action/projects) project board. If anybody from the community would like to bid on doing this work, just leave a comment here.

**Comment by jordanh** [comment]
This is a good one. We haven't had any user requests for it yet. Even though it's on E4E, going to close this one until it comes up again.
