### ISSUE TITLE
Option to disable Stripe active plan requirement

### ISSUE THREAD

**Issue by VRspace4** [ParabolInc/action#831]
## Issue - Enhancement
Can you guys implement an option to disable the Stripe integration requirement that's preventing the general community from testing just the Meatier part of the project?

"npm run quickstart" stops and says I need a valid Stripe API Key and now an active plan, "action-monthly".

**Comment by mattkrick** [comment]
that's a really good idea & something we've been talking about how to do internally since we implemented it. Unfortunately, it gets a little hairy in parts. For example, when you create your first team, we create that customer on stripe, and that call would return an error if a valid stripe account isn't created. While we could first check to see whether a stripe key exists, that's not very robust because in production if the key doesn't exist, i _really_ want it to throw an error.

I think the best way forward might be to instruct users to create a stripe account & then we could write a migration that adds the "action-monthly" plan to the account automatically. We'd be happy to consider a PR if that's something you'd like to try.

**Comment by jordanh** [comment]
An (the?) alternative would be to only mock stripe when `NODE_ENV !== 'production'`. Looking at the source, it looks like we'd need mocks for:

- [ ] `stripe.customers.retrieve(customerId)`
- [ ] `stripe.invoices.retrieve(invoiceId)`
- [ ] `stripe.invoices.update(invoiceId)`
- [ ] `stripe.invoices.retrieveLines(invoiceId, options)`
- [ ] `stripe.invoices.retrieveUpcoming(stripeId)`
- [ ] `stripe.invoiceItems.retrieve(invoiceItemId)`
- [ ] `stripe.invoiceItems.update(invoiceItemId)`
- [ ] `stripe.subscriptions.del(stripeSubscriptionId)`
- [ ] `stripe.subscriptions.retrieve(subscriptionId)`
- [ ] `stripe.subscriptions.update(subscriptionId)`

That's a lot of mocks... we'd also have to consider where/how to snapshot the returns of those calls too.

I like the idea of starting with a migration for the `action-monthly` plan and adding some documentation to the README. It's incrementally better DX.

We can post an E4E item to do the above mocks, as it's not on our critical path.

**Comment by mattkrick** [comment]
well there's a neat idea.

i'm already in the process of mocking all of these for our unit tests. someone could just change the references to `__mocks/stripe` or write a script that copies that folder into node_modules over the real stripe.

**Comment by jordanh** [comment]
And there is another neat idea.

Ok, blowing this out a bit more. What if we did something _crazy_ like a global require in `server/billing/stripe.js` that replaces the stripe client with a mock that uses snapshots? Any easy way to do that without having to copy over files?

**Comment by mattkrick** [comment]
we absolutely could, the only downside is that we'd have logic that is deployed in production that doesn't benefit us, but if we use an oldschool dynamic `require` instead of importing at the top it'd be pretty minimal.

**Comment by jordanh** [comment]
Just added this to our equity for effort program.

- **Estimated effort:** 3 + 10 bonus points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

If anybody in our community is interested in picking this up, please leave a comment with how many points you'll pick this up for. For _Equity for Effort_ program details see: https://github.com/ParabolInc/action/projects

**Comment by jordanh** [comment]
Closing now during scrub. Iceboxed.
