### ISSUE TITLE
Invitee on-boarding sprint.

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#84]
## Issue - Enhancement

Hot on the heels of #59, #74, #77 and #82. Comes this effort to on-board folks invited to Action by their team leader.

To complete this mission we'll need to implement:

- [x] Add invitee landing page
- [x] Add `/me/settings` duck, add `SET_ACTIVITY` and `CLEAR_ACTIVITY` actions
   - [x] `SET_ACTIVITY` has sets two fields: `currentActivity` and `nextPage`
   - [x] Add tests
- [x] Present user with auth0 lock, generate auth token
- [x] Once authenticated, call `TeamMember` mutation `acceptInvitation`
   - [x] Add user to `TeamMembers`
   - [x] Add `TODO:` convert other pending invitations for user to notifications
   - [x] Delete other pending invitation tokens for user
   - [x] Return `TeamMember` output object to client
   - [x] Ensure `TeamMembers` are not double-added on the backend
- [x] Toast user for signing up
- [x] Redirect to `/me/settings`
- [x] Update `/me/settings`
   - [x] Display message describing activity "Before we bring you to your fancy team dashboard..."
   - [x] Update onSubmit logic to redirect to `nextPage` if there is an active activity
- [x] Refactor lock logic into common utility
- [x] Update design of invitee landing page (@ackernaut)

That's it! We'll tackle bits from #74 after this one.

- **Estimated effort:** 3 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
Technical considerations:

- since we can't trust the `teamId` from the params, might as well make it something simpler like `/invitation/:tokenId`. 
- The `tokenId` is a base64 string that when decoded includes an `exp` property. We should make sure that's legit on the client before firing it off to the server
- the `tokenId` also includes an `id` prop that contains the email the invite was sent to. After the token is validated, we should `r.table('Invitation').getAll(tokenObj.id, {index: 'email'}).delete()` since multiple people could have invited the same email address.

**Comment by jordanh** [comment]
Rad! Yes. Much smarter!

**Comment by jordanh** [comment]
Updated the checklist battle-plan for this issue.

**Comment by ackernaut** [comment]
@jordanh What is the flow of arriving to the invitee landing page? First-time or existing user? This would be welcome views for new users? And do existing users arrive on the dashboard view for the team they accepted to join? Just making sure I am following correctly.

**Comment by jordanh** [comment]
@ackernaut hang on just a jiff and I'll have something for you to try and see
