### ISSUE TITLE
Uncaught TypeError: Cannot read property 'validateCardNumber' of undefined

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#848]
## Issue - Bug

I ran into a cute little buggy while debugging some segment stuff.

![image](https://cloud.githubusercontent.com/assets/103000/24177402/ad5998b4-0e78-11e7-85f3-db89db8b10f8.png)

Repro steps:

1. Navigate to billing settings, raise credit card number pop up
2. Repeatedly type 424242... in the card number box until the exception occurs

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
was this a showstopper?
this is usually because the stripe script has not loaded yet.
We load the stripe client async when the user opens that modal for the first time.
Rather than show a blank or a loading state, we just pretend it's already loaded & assume that they can't enter their billing info faster than a round trip to stripe.
that means it might not validate the first couple keystrokes, but hey who cares, at least they get to start typing immediately.

**Comment by jordanh** [comment]
It's only happening on dev, so not a showstopper
