### ISSUE TITLE
Standing Agenda Items

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#871]
## Issue - Enhancement

>we needs a "Standing Item" option in the Agenda column thingy--handy for metrics w/ links to regular 3rd party docs, etc

[Acceptance Criteria and Estimated Effort](https://github.com/ParabolInc/action/issues/871#issuecomment-385130695)

**Comment by ackernaut** [comment]
I think I may prefer an optional meeting phase as described by #330 —but recurring agenda items is an interesting idea as well!

**Comment by ackernaut** [comment]
…standing or “pinned” agenda items (esp. when combined with #669) may make for a nice set of pinned links that are helpful during the meeting (when reviewing web assets outside of the meeting UI)…

**Comment by ackernaut** [comment]
Here’s an idea…

Regular agenda items:

- Have a cog icon (or vertical ellipsis) when the item is hovered (otherwise the cog is hidden).
  - We show a thumb-tack icon with label “Pin Item”
  - We show a pencil icon with label “Edit” (only if not processed/current, or if pinned)
  - We show a times-circle icon with label “Delete” (only if not processed/current)
- Are ordered after any existing and newly pinned items.
- Only can be reordered with other regular items that have not been processed/current (range after pinned, after processed/current).

Pinned agenda items:

- Have a thumb-tack icon that is muted (to indicated that it is pinned) until the item is hovered (then shows at full opacity).
  - We show a thumb-tack icon with label “Remove Pin”
  - We show a pencil icon with label “Edit” (pinned items can always be changed)
  - We show a times-circle icon with label “Delete” (only if not processed/current)
- Are ordered before regular agenda items.
- If a regular item is pinned it automatically is reordered after any existing pinned items (say items[0-2] are pinned already so it becomes items[3]) or first if there are none. This is kind of like when a facilitator navigates ahead of the order (auto-reordering).
- Only can be manually reordered with other pinned items (say items[0-3]).

Other things to consider:

- We may linkify URLs in agenda items in the future. #669 
- We may add menus/shortcut to change the owner of the agenda item. #175 

<img width="714" alt="pinned agenda item concept 2x" src="https://user-images.githubusercontent.com/307286/27095732-5300ca24-5034-11e7-805e-ba4945fd9299.png">

**Comment by tayamueller** [comment]
I believe "standing agenda items" could eventually be replaced by an option to add custom modules to the current 3-item Meeting cycle: Check-In, Updates, Agenda.

**Comment by jordanh** [comment]
Removing this from the Sprint board until it's got clear acceptance criteria and a point rating. I'd like to see us do this one sooner rather than later. @tayamueller can you and @ackernaut discuss or meet and pair work this one?

**Comment by jordanh** [comment]
We got another request for this from The Development Factory, so I'm going to take a stab at writing acceptance criteria to drive prioritization.

## Acceptance Critieria
- A set of high-fidelity designs and new implementation issues created that:
   - Illustrate how an agenda item may be pinned or unpinned from the list of agenda items
   - Allow for the pinning or unpinning of items from the Team Dashboard and from within an Action Meeting

## Estimated effort: 11 points

**Comment by tayamueller** [comment]
agnostic abt the solution, but this is a VERY clear need. Terry's concept seems safe to try!

**Comment by mattkrick** [comment]
what's the difference between a custom phase & a pinned agenda item?
Can we explore the need a bit more from the customers?
This sounds a lot more like a custom phase than a pinned agenda item. 
take "metrics" for example.
today, we treat it as an agenda item, but what we _really_ want is a phase that has a link that opens our google doc.
maybe we combine the 2 concepts?

My tensions:
- it'll take a week to design & build
- adding another menu will make the UI more complex
- the only benefit is saving you from retyping 1 - 2 words

My proposal:
- custom phases are something we can charge for! after running 1 meeting, if i tell you you can get custom phases if you pay, you understand the offer.
- if we try to charge for "pinning", we'll get laughed at
- let's design how custom phases are built
- if this is part of the larger custom phases feature, great!
- if not, then we just saved a whole bunch of time

**Comment by jordanh** [comment]
Ok! Let's interrogate this a bit more together.

> what's the difference between a custom phase & a pinned agenda item?

**A custom phase** changes the structure of one of our meeting types. It is performed by all team members. It presents some information that is not accommodated by the UI/UX of our agenda processing functionality.

Example JTBD:
   * When its cultural to always begin a meeting by presenting the same information together (e.g. metrics, a checklist, etc.), I want to be able to add a custom permanent phase, so that we can adapt Parabol to our norms

**A pinned agenda item**:  it is used to save an agenda item between two or more meetings. Does not require customer information (e.g. a link) to be shared.

Example JTBD:
   * When we have to end the meeting early because some emergency cropped up, I want to be able to save our agenda items, so that I don't have to remember what we were going to talk about
   * When person X is not present but we're holding the meeting anyway, I want to pin their agenda items, so that they come back next meeting

I imagine we'd also weakly cover the need for custom phase items too, until we get around to doing that.

> Can we explore the need a bit more from the customers?

We've got a good degree of confidence here. Would you like to speak to a customer? Always happy to make that happen!

> My tensions:
> - it'll take a week to design & build

Can we break this down into smaller chunks? What would the burn-down be?

> - adding another menu will make the UI more complex

Yeah, this is good input. Ideally when @ackernaut refreshes his design we'll use the same menu for agenda item reassignment (something we should have anyway) as we would to pin an item

> - the only benefit is saving you from retyping 1 - 2 words

Given the JTBD above, do you still feel that way?

> My proposal:
> - custom phases are something we can charge for! after running 1 meeting, if i tell you you can get custom phases if you pay, you understand the offer, and the value add.
> - if we try to charge for "pinning", we'll get laughed at

True. I think this would be a free feature.

> - let's design how custom phases are built
> - if this is part of the larger custom phases feature, great!
> - if not, then we just saved a whole bunch of time

I think custom phases are something we should def. build, too. I think they address a separate (but related) user tensions. Could you open a design issue for how'd like it to work? We can design it out and A/B test between the two with customers. I'm all for refactoring the Action Meeting to the new meeting style and adding custom phases if it'll drive some conversions.

Let's refresh our design here. Then we can break it up into a burn down and prioritize against other things appropriately.

**Comment by mattkrick** [comment]
Both JTBD are for unhandled agenda items.
If people want to carry over unhandled agenda items, then we should carry over unhandled agenda items. we don't need pins to do that.
if a team finished 3 of 10 items, do you expect them to click items 4 - 10 and then click "pin" on each one? that's 14 clicks & a bunch of mouse movement!

if we carry over unhandled agenda items, then they can delete the items from the team dash by simply placing their mouse on the delete button of the first one & just rapid clicking 7 times, no mouse movement necessary.

why bloat the UI just to make them do twice the work?

**Comment by ackernaut** [comment]
I think another JTBD that may be valid from what we’ve heard from users is:

>I have a list of things I do want to go over every time. I don’t want to have to remember to add them every time.

- I’d see a pinned agenda item as a function of “humans are bad at remembering” and not a function of things that are unresolved from last meeting. I personally like taking a stance on list debt and having tension rise again. I think carrying over unprocessed agenda items could be a team setting appreciated by some, and I would not set it as the default.
- We have feedback about the need for recurring tasks with checklists for a similar JTBD, about remembering what to do and doing it repeatedly.
- I’d see a pinned agenda feature as a low-effort win for users because we can’t possibly spend design-and-build cycles on each custom phase when there will probably other things that will get prioritized over that. Even if we prioritized a custom phase, we would miss use cases: we have used recurring agenda topics in the last several meetings (metrics, sprint, release, calendar) and I have been conscientious about seeing how that feels. I diverge into thoughts about a custom phase…
- Granted those could all go into a Check-List phase item (teammates configure the Check-List phase with items: label + optional link which is updated over time and editable outside of the active meeting, too.). The team goes through the Check-List. I still think this may be more effort than the pinned items.
- Would users want to add take-away tasks when needs are triggered by Check-List items? Could we add tasks inline?

Either way I think clickable visual concepts could be cheap to make and test with users both around pinned agenda items and a first custom phase like a Check-List phase.

**Comment by mattkrick** [comment]
I guess I'm in the minority so i'll concede. FWIW, I'm strongly against this.

- do we have 5 paying users who want pinned agenda items and NOT custom phases? Every reference to a customer in this issue points to them wanting a custom phase. 
- Our strategy is to increase conversions. This does not help us reach our goal. In fact, it could hurt us. Why convert for custom phases when i could just pin an agenda item that gets me halfway there? 
- Our time could be better spent put towards a larger feature that can be sold or drive new user growth.
- The appeal of our product is simplicity. Sure, we could make agenda items editable, or let folks change the owner, or add links, or custom styles, or longer inputs, or pinning, or make it so you can drag them into project cards to populate the text, etc. Those are all good ideas! But I'd rather build 1 great feature instead of 10 good ones.

**Comment by ackernaut** [comment]
I’d like to make quick, current prototypes of both really and perhaps we can test some clickable prototypes with users, get feedback, esp. “would you convert to pro for a checklist phase if we developed it”? (just brainstorming here)

**Comment by jordanh** [comment]
@ackernaut go for it, seems like a good way to resolve this issue

**Comment by ackernaut** [comment]
Getting started!

**Comment by ackernaut** [comment]
[Design concept in Figma](https://www.figma.com/file/CexaOK4w42TNrfq8l6YInFfE/Agenda-Topics-Checklist-Phase)

**Comment by ackernaut** [comment]
I wanted to check in 1 more time before this issue was closed.

I designed a simple, low-effort concept illustrating the ability to pin, edit and delete agenda topics with a menu toggled by a vertical ellipsis. I also threw in a quick pass at a team checklist phase which would be the version we might offer on the pro tier. Instead of pinned agenda items, we offer a place to add and own items that the team reviews each week, with a rich editor per item.

I can write an implementation issue for the simple pinning and we can scrub it if we need to go back to visual design. One possible step in between would be to make the Figma concept clickable and share it with a few users who have requested it and see if that is what they had in mind. Not sure it’s a paid feature. Not sure how much effort we want to burn on it.

The team checklist is an early “extra credit” exploration and would probably need more user validation pre-code to see if it would be something folks would be willing to pay for as part of the paid tier.

[See Figma](https://www.figma.com/file/CexaOK4w42TNrfq8l6YInFfE/Agenda-Topics-Checklist-Phase)

@jordanh what’s it worth re: pinned items? Any more need for design? Should we test with users before implementing? Seeing how it is a simple menu affordance it would be safer IMO since it’s more of a utility, but the UX story in my mind is around recurring agenda topics meeting over meeting.

**Comment by ackernaut** [comment]
Update: we are currently getting a round of internal validation on the hi-fi concept, then we can move on to user validation on the design we agree to test/check per recent governance. Then we can write an implementation issue and link back.

**Comment by jordanh** [comment]
Updated AC:
- Generate A/B artifacts for external user testing
- New (implementation?) issue created

**Comment by ackernaut** [comment]
- Option A: enhance items with a menu that allows for inline editing of text, pinning or unpinning, and deletion (can get feedback from [clickable prototype](https://www.figma.com/proto/CexaOK4w42TNrfq8l6YInFfE/Agenda-Topics-Checklist-Phase?scaling=scale-down&node-id=38%3A4440))
- Option B: agenda items stay the same and a new checklist phase is added (perhaps as a pro feature) that allows for recurring items to be created with an owner, optional inline linking, and can have checked/focused state during the meeting (can get feedback on [static concept](https://www.figma.com/file/CexaOK4w42TNrfq8l6YInFfE?utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#1503908) )

**Comment by ackernaut** [comment]
@jordanh last comment ⬆️ updated and now has 2 clickable prototypes
