### ISSUE TITLE
remove react-textarea-autosize

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#895]
remember when the caret kept jumping to the end of the textarea for no reason? Found out it was caused by react-textarea-autosize. That's the same bugger that wouldn't update until we clicked inside of it. I don't like it. I'm nuking it.

Now the question is, how do we want to handle long projects? do we just clip? do we allow them to draw out the size of the text area? do we pop up a modal & let them type in a WYSIWYG text editor?

**Comment by ackernaut** [comment]
@mattkrick a couple of thoughts here:

1. I want to get the default height to be one line.
2. I still like the idea of increasing the height of a card to match the lines, but I know the design for cards will change a lot as we iterate on integrated projects.

Can we find a way to resize the `textarea` for now that isn’t _janky_?

Otherwise, I think that is ok to let the content height be natural and set the `textarea` to 3 or 4 lines.

**Comment by mattkrick** [comment]
yeah, i think the best way forward is to nail down a good card design that supports tags & integrations & all that jazz & then this problem will solve itself.
