### ISSUE TITLE
Various React PropTypes deprecations [add-tags]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#949]
## Issue - Bug

I am ok pushing this into the future if you'd like @mattkrick. I'm opening this to track. Getting the following deprecations.

First, on SSR:

```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
Warning: RouterContext: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
```

Next on the client:

```

webpack:///./~/fbjs/lib/warning.js?:36 Warning: RouterContext: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
printWarning @ webpack:///./~/fbjs/lib/warning.js?:36
chrome-extension://odepjlkgmleifdipoemkdalmakbemeaa/js/rangy.min.js:10 Rangy warning: DEPRECATED: createCssClassApplier in module ClassApplier is deprecated. Please use createClassApplier instead.
webpack:///../~/webpack-hot-middleware/client.js?:67 [HMR] connected
```

The call stack wasn't obvious as to where these warnings were coming from...

- **OS:** OSX
- **Browser:** Chrome

**Comment by mattkrick** [comment]
closing in favor of #918 since it will be on our roadmap to upgrade to react 16.

basically, propTypes are going away in favor of build-time solutions (typescript or flow). they'll still offer propTypes, just in a separate package. We can use a codemod to update all our files, i'm just waiting for the rest of the community to flush out any bugs in the codemod script.

the 2nd error has to do with us using an older version of react router, which is the meat n taters of #918.
