### ISSUE TITLE
Clicking on #tag from portal menu makes card disappear [add-tags]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#952]
## Issue - Bug

Here's a fun one! Reproduction steps:

1. Create a new card
2. Type content then type `#` to begin adding a tag
3. Click on the tag, the card disappears

- **OS:** OSX
- **Browser:** Chrome

**Comment by jordanh** [comment]
Clicking on emojis produces the same bug.

**Comment by mattkrick** [comment]
oh boy this is a fun one.
here's the logic flow:
- while the card is being edited, listen for a click on the document
- when a click is received, see if the click originated from the card (because you could change the status or team member before setting content)
- if the click did not originate from the card, then update the card (or delete it if there is no content)

we can't use an onBlur on the textarea because that gets called when you try to change the team member

we can't set a tabIndex on the card because that didn't work in safari

so, now that we're using portals, we need to make sure that the DOM element is a descendent of the card OR a descendent of the portal that is opened by the card.
