### ISSUE TITLE
Freemium model design cycle

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#962]
## Issue - Enhancement

We've been catching some signal (internally and externally) that forced conversions isn't likely the optimum model to nurture attachment to our product. This issue captures a design cycle we'll take to investigate incremental improvements.

Thoughts include:

- Free to use, except premium features are disabled on trial expiration:
   - Archive? Or, limit Archive history or search items returned (like Slack?)
   - Integrations?

- Extend trial by holding team meeting?

What other thoughts do you have?

- **Estimated effort:** 23 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Not sure how useful archive will be (in terms of a felt limitation), but perhaps it will be more helpful if we add search/filtering to a single kanban and/or list view.

I like the idea of limiting integrations. Perhaps integrations are limited in number or time. (Upgrade or the integration will be paused, cards archived, etc.)

- Limited number of teams, maybe just 1 team
- Discover, test and build partner and/or enterprise features that need to be paid for, otherwise everything else is free. (what folks can do with clients, large companies, etc.) Let the small teams (like startups/products/creatives) stay scrappy and love us and be our free “word-of-mouth” marketing.

**Comment by jordanh** [comment]
We implemented Freemium!
