### ISSUE TITLE
Cycle Check-In Questions Faster

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#964]
## Issue - Enhancement

Many users will be on multiple Team stand-up mtgs on Mondays & Tuesdays. Let's make sure the Check-In round questions cycle more frequently than daily so that users don't get the same question multiple times/day

**Comment by jordanh** [comment]
This issue is available for community contribution under our [Equity for Effort](https://focus.parabol.co/equity-for-effort-v2-0-7ca93e0a3968#.y9upisjz4) program. If you'd like to take this on, we'll onboard you to our code base and help you get started.

**Estimated effort**: 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
start from a random place in the index. & then just go from there.
