### ISSUE TITLE
Cashay props not updating?

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#97]
## Issue - Bug

This could very well be user error, but the cause wasn't immediately obvious to me.

Here's what's going on: while stubbing in the new _User Preferences_ view and form, I noticed that props updated by a Cashay mutation were not causing the top-level container to re-render.

@mattkrick do you know what's up?

Here's how to reproduce it:

   1. Pull down the `dashboard-scaffolding-#95` branch
   2. `npm install` && `npm db:migrate` && `npm run dev`
   3. Navigate to http://localhost:3000
   4. Sign in
   5. Navigate to: http://localhost:3000/me/settings
   6. Update the preferred name in the field and press the button
   7. Notice that the `UserHub` props do not update
   8. Hit reload, note  the updated `UserHub` props

Here's a screenshot of the failed state:

![image](https://cloud.githubusercontent.com/assets/103000/16626762/a87aca0a-43aa-11e6-887e-b50b9a396bf6.png)

- **OS:** OSX
- **Browser:** Chrome
- **Node version:** v6.2.0
- **NPM version:** 3.8.9
- **RethinkDB version:** rethinkdb 2.3.4 (CLANG 7.3.0 (clang-703.0.31))
- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
This is a 2 part problem. One is with Cashay, since it needed a "shallow + 1" object clone to trick react-redux into thinking it was a fresh one. That is fixed in Cashay v0.11.4.

The 2nd, less fun problem is that the very enjoyable `getAuthedUser` doesn't work. I loved that little helper because it was completely outside of the react lifecycle. But, for that very reason, it'll never be able to trigger a rerender, which means that pattern is garbage. The solution is to do like we're supposed to & stick `cashay.query` inside a mapStateToProps.

Will PR after a quick lunch.

**Comment by jordanh** [comment]
Confirmed fixed. Nice work sir!

PR #101 will close this issue.
