### ISSUE TITLE
Meeting overview, first-time check in question

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#999]
## Issue - Enhancement

Some of our questions are a little esoteric for some users. @tayamueller and I observed folks being stymied by "Heard any good advice lately?" Underlying this, the user doesn't understand the purpose of the check-in round, and how that question relates.

We might need a one-time modal that's like "this is your first meeting, here's what's going to happen," then when they hit check-in round using the most generic question ever, "what is on your mind, that might be keeping you from being fully present?"

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by dan-f** [comment]
Great point. I went to the start of a meeting locally to check my experience. A few notes:
- My eyes sort of gloss over in the meeting lobby. All the copy from "Is the whole team here?" down to "Today’s Facilitator: begin the Social Check-In!" sort of passes me by.
- When I get to the check-in round, I don't really know where I am. The check-in question takes front-and-center, and there feels like there's a lot of empty context surrounding it.
  - Perhaps we can make the meeting phase redundant at the top of the screen - something like "Social checkin - catch up with your teammates! Try this question out..."
  - Are the "Here" / "Not Here" buttons for me? For the person being checked-in? What if we changed the copy to "They're here" / "They're absent"?
- Perhaps part of this tension can be resolved if we make the different meeting phases _feel_ like distinct places. We could change the background color or something similar. It could also lend a sense of forward momentum to an otherwise trudge-y meeting.

**Comment by ackernaut** [comment]
In our current on-boarding prototype, users will see Bertie first, where he explains what is happening through copy, and then see a view to add their name. They will not get a check-in question. We could consider scoping the check-in questions for actual meeting number 1-3 to 3 “easier” questions, and then rotate “randomly” after that.
